//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/squeaky/core/src/main/java/co/touchlab/squeaky/field/types/ByteObjectType.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "android/database/Cursor.h"
#include "co/touchlab/squeaky/field/FieldType.h"
#include "co/touchlab/squeaky/field/SqlType.h"
#include "co/touchlab/squeaky/field/types/BaseDataType.h"
#include "co/touchlab/squeaky/field/types/ByteObjectType.h"
#include "java/lang/Byte.h"
#include "java/sql/SQLException.h"

@interface CoTouchlabSqueakyFieldTypesByteObjectType ()

- (instancetype)init;

@end

inline CoTouchlabSqueakyFieldTypesByteObjectType *CoTouchlabSqueakyFieldTypesByteObjectType_get_singleTon();
static CoTouchlabSqueakyFieldTypesByteObjectType *CoTouchlabSqueakyFieldTypesByteObjectType_singleTon;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyFieldTypesByteObjectType, singleTon, CoTouchlabSqueakyFieldTypesByteObjectType *)

__attribute__((unused)) static void CoTouchlabSqueakyFieldTypesByteObjectType_init(CoTouchlabSqueakyFieldTypesByteObjectType *self);

__attribute__((unused)) static CoTouchlabSqueakyFieldTypesByteObjectType *new_CoTouchlabSqueakyFieldTypesByteObjectType_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static CoTouchlabSqueakyFieldTypesByteObjectType *create_CoTouchlabSqueakyFieldTypesByteObjectType_init();

J2OBJC_INITIALIZED_DEFN(CoTouchlabSqueakyFieldTypesByteObjectType)

@implementation CoTouchlabSqueakyFieldTypesByteObjectType

+ (CoTouchlabSqueakyFieldTypesByteObjectType *)getSingleton {
  return CoTouchlabSqueakyFieldTypesByteObjectType_getSingleton();
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  CoTouchlabSqueakyFieldTypesByteObjectType_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithCoTouchlabSqueakyFieldSqlType:(CoTouchlabSqueakyFieldSqlType *)sqlType
                                    withIOSClassArray:(IOSObjectArray *)classes {
  CoTouchlabSqueakyFieldTypesByteObjectType_initWithCoTouchlabSqueakyFieldSqlType_withIOSClassArray_(self, sqlType, classes);
  return self;
}

- (id)parseDefaultStringWithCoTouchlabSqueakyFieldFieldType:(CoTouchlabSqueakyFieldFieldType *)fieldType
                                               withNSString:(NSString *)defaultStr {
  return JavaLangByte_valueOfWithByte_(JavaLangByte_parseByteWithNSString_(defaultStr));
}

- (id)resultToSqlArgWithCoTouchlabSqueakyFieldFieldType:(CoTouchlabSqueakyFieldFieldType *)fieldType
                              withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
                                                withInt:(jint)columnPos {
  return JavaLangByte_valueOfWithByte_((jbyte) [((id<AndroidDatabaseCursor>) nil_chk(results)) getShortWithInt:columnPos]);
}

- (jboolean)isEscapedValue {
  return false;
}

+ (void)initialize {
  if (self == [CoTouchlabSqueakyFieldTypesByteObjectType class]) {
    CoTouchlabSqueakyFieldTypesByteObjectType_singleTon = new_CoTouchlabSqueakyFieldTypesByteObjectType_init();
    J2OBJC_SET_INITIALIZED(CoTouchlabSqueakyFieldTypesByteObjectType)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getSingleton", NULL, "Lco.touchlab.squeaky.field.types.ByteObjectType;", 0x9, NULL, NULL },
    { "init", "ByteObjectType", NULL, 0x2, NULL, NULL },
    { "initWithCoTouchlabSqueakyFieldSqlType:withIOSClassArray:", "ByteObjectType", NULL, 0x4, NULL, NULL },
    { "parseDefaultStringWithCoTouchlabSqueakyFieldFieldType:withNSString:", "parseDefaultString", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "resultToSqlArgWithCoTouchlabSqueakyFieldFieldType:withAndroidDatabaseCursor:withInt:", "resultToSqlArg", "Ljava.lang.Object;", 0x1, "Ljava.sql.SQLException;", NULL },
    { "isEscapedValue", NULL, "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "singleTon", "singleTon", 0x1a, "Lco.touchlab.squeaky.field.types.ByteObjectType;", &CoTouchlabSqueakyFieldTypesByteObjectType_singleTon, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _CoTouchlabSqueakyFieldTypesByteObjectType = { 2, "ByteObjectType", "co.touchlab.squeaky.field.types", NULL, 0x1, 6, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_CoTouchlabSqueakyFieldTypesByteObjectType;
}

@end

CoTouchlabSqueakyFieldTypesByteObjectType *CoTouchlabSqueakyFieldTypesByteObjectType_getSingleton() {
  CoTouchlabSqueakyFieldTypesByteObjectType_initialize();
  return CoTouchlabSqueakyFieldTypesByteObjectType_singleTon;
}

void CoTouchlabSqueakyFieldTypesByteObjectType_init(CoTouchlabSqueakyFieldTypesByteObjectType *self) {
  CoTouchlabSqueakyFieldTypesBaseDataType_initWithCoTouchlabSqueakyFieldSqlType_withIOSClassArray_(self, JreLoadEnum(CoTouchlabSqueakyFieldSqlType, BYTE), [IOSObjectArray newArrayWithObjects:(id[]){ JavaLangByte_class_() } count:1 type:IOSClass_class_()]);
}

CoTouchlabSqueakyFieldTypesByteObjectType *new_CoTouchlabSqueakyFieldTypesByteObjectType_init() {
  CoTouchlabSqueakyFieldTypesByteObjectType *self = [CoTouchlabSqueakyFieldTypesByteObjectType alloc];
  CoTouchlabSqueakyFieldTypesByteObjectType_init(self);
  return self;
}

CoTouchlabSqueakyFieldTypesByteObjectType *create_CoTouchlabSqueakyFieldTypesByteObjectType_init() {
  return new_CoTouchlabSqueakyFieldTypesByteObjectType_init();
}

void CoTouchlabSqueakyFieldTypesByteObjectType_initWithCoTouchlabSqueakyFieldSqlType_withIOSClassArray_(CoTouchlabSqueakyFieldTypesByteObjectType *self, CoTouchlabSqueakyFieldSqlType *sqlType, IOSObjectArray *classes) {
  CoTouchlabSqueakyFieldTypesBaseDataType_initWithCoTouchlabSqueakyFieldSqlType_withIOSClassArray_(self, sqlType, classes);
}

CoTouchlabSqueakyFieldTypesByteObjectType *new_CoTouchlabSqueakyFieldTypesByteObjectType_initWithCoTouchlabSqueakyFieldSqlType_withIOSClassArray_(CoTouchlabSqueakyFieldSqlType *sqlType, IOSObjectArray *classes) {
  CoTouchlabSqueakyFieldTypesByteObjectType *self = [CoTouchlabSqueakyFieldTypesByteObjectType alloc];
  CoTouchlabSqueakyFieldTypesByteObjectType_initWithCoTouchlabSqueakyFieldSqlType_withIOSClassArray_(self, sqlType, classes);
  return self;
}

CoTouchlabSqueakyFieldTypesByteObjectType *create_CoTouchlabSqueakyFieldTypesByteObjectType_initWithCoTouchlabSqueakyFieldSqlType_withIOSClassArray_(CoTouchlabSqueakyFieldSqlType *sqlType, IOSObjectArray *classes) {
  return new_CoTouchlabSqueakyFieldTypesByteObjectType_initWithCoTouchlabSqueakyFieldSqlType_withIOSClassArray_(sqlType, classes);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(CoTouchlabSqueakyFieldTypesByteObjectType)
