//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/dagger/core/src/main/java/dagger/internal/MapProviderFactory.java
//

#include "J2ObjC_source.h"
#include "dagger/internal/Collections.h"
#include "dagger/internal/MapProviderFactory.h"
#include "java/lang/NullPointerException.h"
#include "java/util/Collections.h"
#include "java/util/LinkedHashMap.h"
#include "java/util/Map.h"
#include "javax/inject/Provider.h"

@interface DaggerInternalMapProviderFactory () {
 @public
  id<JavaUtilMap> contributingMap_;
}

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)contributingMap;

@end

J2OBJC_FIELD_SETTER(DaggerInternalMapProviderFactory, contributingMap_, id<JavaUtilMap>)

inline DaggerInternalMapProviderFactory *DaggerInternalMapProviderFactory_get_EMPTY();
static DaggerInternalMapProviderFactory *DaggerInternalMapProviderFactory_EMPTY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(DaggerInternalMapProviderFactory, EMPTY, DaggerInternalMapProviderFactory *)

__attribute__((unused)) static void DaggerInternalMapProviderFactory_initWithJavaUtilMap_(DaggerInternalMapProviderFactory *self, id<JavaUtilMap> contributingMap);

__attribute__((unused)) static DaggerInternalMapProviderFactory *new_DaggerInternalMapProviderFactory_initWithJavaUtilMap_(id<JavaUtilMap> contributingMap) NS_RETURNS_RETAINED;

__attribute__((unused)) static DaggerInternalMapProviderFactory *create_DaggerInternalMapProviderFactory_initWithJavaUtilMap_(id<JavaUtilMap> contributingMap);

@interface DaggerInternalMapProviderFactory_Builder () {
 @public
  JavaUtilLinkedHashMap *mapBuilder_;
}

- (instancetype)initWithInt:(jint)size;

@end

J2OBJC_FIELD_SETTER(DaggerInternalMapProviderFactory_Builder, mapBuilder_, JavaUtilLinkedHashMap *)

__attribute__((unused)) static void DaggerInternalMapProviderFactory_Builder_initWithInt_(DaggerInternalMapProviderFactory_Builder *self, jint size);

__attribute__((unused)) static DaggerInternalMapProviderFactory_Builder *new_DaggerInternalMapProviderFactory_Builder_initWithInt_(jint size) NS_RETURNS_RETAINED;

__attribute__((unused)) static DaggerInternalMapProviderFactory_Builder *create_DaggerInternalMapProviderFactory_Builder_initWithInt_(jint size);

J2OBJC_INITIALIZED_DEFN(DaggerInternalMapProviderFactory)

@implementation DaggerInternalMapProviderFactory

+ (DaggerInternalMapProviderFactory_Builder *)builderWithInt:(jint)size {
  return DaggerInternalMapProviderFactory_builderWithInt_(size);
}

+ (DaggerInternalMapProviderFactory *)empty {
  return DaggerInternalMapProviderFactory_empty();
}

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)contributingMap {
  DaggerInternalMapProviderFactory_initWithJavaUtilMap_(self, contributingMap);
  return self;
}

- (id<JavaUtilMap>)get {
  return self->contributingMap_;
}

+ (void)initialize {
  if (self == [DaggerInternalMapProviderFactory class]) {
    DaggerInternalMapProviderFactory_EMPTY = new_DaggerInternalMapProviderFactory_initWithJavaUtilMap_(JavaUtilCollections_emptyMap());
    J2OBJC_SET_INITIALIZED(DaggerInternalMapProviderFactory)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "builderWithInt:", "builder", "Ldagger.internal.MapProviderFactory$Builder;", 0x9, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>(I)Ldagger/internal/MapProviderFactory$Builder<TK;TV;>;" },
    { "empty", NULL, "Ldagger.internal.MapProviderFactory;", 0x9, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>()Ldagger/internal/MapProviderFactory<TK;TV;>;" },
    { "initWithJavaUtilMap:", "MapProviderFactory", NULL, 0x2, NULL, "(Ljava/util/Map<TK;Ljavax/inject/Provider<TV;>;>;)V" },
    { "get", NULL, "Ljava.util.Map;", 0x1, NULL, "()Ljava/util/Map<TK;Ljavax/inject/Provider<TV;>;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "EMPTY", "EMPTY", 0x1a, "Ldagger.internal.MapProviderFactory;", &DaggerInternalMapProviderFactory_EMPTY, "Ldagger/internal/MapProviderFactory<Ljava/lang/Object;Ljava/lang/Object;>;", .constantValue.asLong = 0 },
    { "contributingMap_", NULL, 0x12, "Ljava.util.Map;", NULL, "Ljava/util/Map<TK;Ljavax/inject/Provider<TV;>;>;", .constantValue.asLong = 0 },
  };
  static const char *inner_classes[] = {"Ldagger.internal.MapProviderFactory$Builder;"};
  static const J2ObjcClassInfo _DaggerInternalMapProviderFactory = { 2, "MapProviderFactory", "dagger.internal", NULL, 0x11, 4, methods, 2, fields, 0, NULL, 1, inner_classes, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;Ldagger/internal/Factory<Ljava/util/Map<TK;Ljavax/inject/Provider<TV;>;>;>;" };
  return &_DaggerInternalMapProviderFactory;
}

@end

DaggerInternalMapProviderFactory_Builder *DaggerInternalMapProviderFactory_builderWithInt_(jint size) {
  DaggerInternalMapProviderFactory_initialize();
  return new_DaggerInternalMapProviderFactory_Builder_initWithInt_(size);
}

DaggerInternalMapProviderFactory *DaggerInternalMapProviderFactory_empty() {
  DaggerInternalMapProviderFactory_initialize();
  return DaggerInternalMapProviderFactory_EMPTY;
}

void DaggerInternalMapProviderFactory_initWithJavaUtilMap_(DaggerInternalMapProviderFactory *self, id<JavaUtilMap> contributingMap) {
  NSObject_init(self);
  self->contributingMap_ = JavaUtilCollections_unmodifiableMapWithJavaUtilMap_(contributingMap);
}

DaggerInternalMapProviderFactory *new_DaggerInternalMapProviderFactory_initWithJavaUtilMap_(id<JavaUtilMap> contributingMap) {
  DaggerInternalMapProviderFactory *self = [DaggerInternalMapProviderFactory alloc];
  DaggerInternalMapProviderFactory_initWithJavaUtilMap_(self, contributingMap);
  return self;
}

DaggerInternalMapProviderFactory *create_DaggerInternalMapProviderFactory_initWithJavaUtilMap_(id<JavaUtilMap> contributingMap) {
  return new_DaggerInternalMapProviderFactory_initWithJavaUtilMap_(contributingMap);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DaggerInternalMapProviderFactory)

@implementation DaggerInternalMapProviderFactory_Builder

- (instancetype)initWithInt:(jint)size {
  DaggerInternalMapProviderFactory_Builder_initWithInt_(self, size);
  return self;
}

- (DaggerInternalMapProviderFactory *)build {
  return new_DaggerInternalMapProviderFactory_initWithJavaUtilMap_(self->mapBuilder_);
}

- (DaggerInternalMapProviderFactory_Builder *)putWithId:(id)key
                                withJavaxInjectProvider:(id<JavaxInjectProvider>)providerOfValue {
  if (key == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"The key is null");
  }
  if (providerOfValue == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"The provider of the value is null");
  }
  (void) [((JavaUtilLinkedHashMap *) nil_chk(self->mapBuilder_)) putWithId:key withId:providerOfValue];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithInt:", "Builder", NULL, 0x2, NULL, NULL },
    { "build", NULL, "Ldagger.internal.MapProviderFactory;", 0x1, NULL, "()Ldagger/internal/MapProviderFactory<TK;TV;>;" },
    { "putWithId:withJavaxInjectProvider:", "put", "Ldagger.internal.MapProviderFactory$Builder;", 0x1, NULL, "(TK;Ljavax/inject/Provider<TV;>;)Ldagger/internal/MapProviderFactory$Builder<TK;TV;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "mapBuilder_", NULL, 0x12, "Ljava.util.LinkedHashMap;", NULL, "Ljava/util/LinkedHashMap<TK;Ljavax/inject/Provider<TV;>;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _DaggerInternalMapProviderFactory_Builder = { 2, "Builder", "dagger.internal", "MapProviderFactory", 0x19, 3, methods, 1, fields, 0, NULL, 0, NULL, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_DaggerInternalMapProviderFactory_Builder;
}

@end

void DaggerInternalMapProviderFactory_Builder_initWithInt_(DaggerInternalMapProviderFactory_Builder *self, jint size) {
  NSObject_init(self);
  self->mapBuilder_ = DaggerInternalCollections_newLinkedHashMapWithExpectedSizeWithInt_(size);
}

DaggerInternalMapProviderFactory_Builder *new_DaggerInternalMapProviderFactory_Builder_initWithInt_(jint size) {
  DaggerInternalMapProviderFactory_Builder *self = [DaggerInternalMapProviderFactory_Builder alloc];
  DaggerInternalMapProviderFactory_Builder_initWithInt_(self, size);
  return self;
}

DaggerInternalMapProviderFactory_Builder *create_DaggerInternalMapProviderFactory_Builder_initWithInt_(jint size) {
  return new_DaggerInternalMapProviderFactory_Builder_initWithInt_(size);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DaggerInternalMapProviderFactory_Builder)
