//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/dagger/core/src/main/java/dagger/internal/ScopedProvider.java
//

#include "J2ObjC_header.h"

#pragma push_macro("DaggerInternalScopedProvider_INCLUDE_ALL")
#ifdef DaggerInternalScopedProvider_RESTRICT
#define DaggerInternalScopedProvider_INCLUDE_ALL 0
#else
#define DaggerInternalScopedProvider_INCLUDE_ALL 1
#endif
#undef DaggerInternalScopedProvider_RESTRICT

#if !defined (DaggerInternalScopedProvider_) && (DaggerInternalScopedProvider_INCLUDE_ALL || defined(DaggerInternalScopedProvider_INCLUDE))
#define DaggerInternalScopedProvider_

#define JavaxInjectProvider_RESTRICT 1
#define JavaxInjectProvider_INCLUDE 1
#include "javax/inject/Provider.h"

#define DaggerLazy_RESTRICT 1
#define DaggerLazy_INCLUDE 1
#include "dagger/Lazy.h"

@protocol DaggerInternalFactory;

@interface DaggerInternalScopedProvider : NSObject < JavaxInjectProvider, DaggerLazy >

#pragma mark Public

+ (id<JavaxInjectProvider>)createWithDaggerInternalFactory:(id<DaggerInternalFactory>)factory;

- (id)get;

@end

J2OBJC_STATIC_INIT(DaggerInternalScopedProvider)

FOUNDATION_EXPORT id<JavaxInjectProvider> DaggerInternalScopedProvider_createWithDaggerInternalFactory_(id<DaggerInternalFactory> factory);

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalScopedProvider)

#endif

#pragma pop_macro("DaggerInternalScopedProvider_INCLUDE_ALL")
