//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/RxJava/src/main/java/rx/internal/operators/OnSubscribeJoin.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL")
#ifdef RxInternalOperatorsOnSubscribeJoin_RESTRICT
#define RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL 0
#else
#define RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL 1
#endif
#undef RxInternalOperatorsOnSubscribeJoin_RESTRICT

#if !defined (RxInternalOperatorsOnSubscribeJoin_) && (RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL || defined(RxInternalOperatorsOnSubscribeJoin_INCLUDE))
#define RxInternalOperatorsOnSubscribeJoin_

#define RxObservable_RESTRICT 1
#define RxObservable_OnSubscribe_INCLUDE 1
#include "rx/Observable.h"

@class RxObservable;
@class RxSubscriber;
@protocol RxFunctionsFunc1;
@protocol RxFunctionsFunc2;

@interface RxInternalOperatorsOnSubscribeJoin : NSObject < RxObservable_OnSubscribe > {
 @public
  RxObservable *left_;
  RxObservable *right_;
  id<RxFunctionsFunc1> leftDurationSelector_;
  id<RxFunctionsFunc1> rightDurationSelector_;
  id<RxFunctionsFunc2> resultSelector_;
}

#pragma mark Public

- (instancetype)initWithRxObservable:(RxObservable *)left
                    withRxObservable:(RxObservable *)right
                withRxFunctionsFunc1:(id<RxFunctionsFunc1>)leftDurationSelector
                withRxFunctionsFunc1:(id<RxFunctionsFunc1>)rightDurationSelector
                withRxFunctionsFunc2:(id<RxFunctionsFunc2>)resultSelector;

- (void)callWithId:(RxSubscriber *)t1;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOnSubscribeJoin)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin, left_, RxObservable *)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin, right_, RxObservable *)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin, leftDurationSelector_, id<RxFunctionsFunc1>)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin, rightDurationSelector_, id<RxFunctionsFunc1>)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin, resultSelector_, id<RxFunctionsFunc2>)

FOUNDATION_EXPORT void RxInternalOperatorsOnSubscribeJoin_initWithRxObservable_withRxObservable_withRxFunctionsFunc1_withRxFunctionsFunc1_withRxFunctionsFunc2_(RxInternalOperatorsOnSubscribeJoin *self, RxObservable *left, RxObservable *right, id<RxFunctionsFunc1> leftDurationSelector, id<RxFunctionsFunc1> rightDurationSelector, id<RxFunctionsFunc2> resultSelector);

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin *new_RxInternalOperatorsOnSubscribeJoin_initWithRxObservable_withRxObservable_withRxFunctionsFunc1_withRxFunctionsFunc1_withRxFunctionsFunc2_(RxObservable *left, RxObservable *right, id<RxFunctionsFunc1> leftDurationSelector, id<RxFunctionsFunc1> rightDurationSelector, id<RxFunctionsFunc2> resultSelector) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin *create_RxInternalOperatorsOnSubscribeJoin_initWithRxObservable_withRxObservable_withRxFunctionsFunc1_withRxFunctionsFunc1_withRxFunctionsFunc2_(RxObservable *left, RxObservable *right, id<RxFunctionsFunc1> leftDurationSelector, id<RxFunctionsFunc1> rightDurationSelector, id<RxFunctionsFunc2> resultSelector);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOnSubscribeJoin)

#endif

#if !defined (RxInternalOperatorsOnSubscribeJoin_ResultSink_) && (RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL || defined(RxInternalOperatorsOnSubscribeJoin_ResultSink_INCLUDE))
#define RxInternalOperatorsOnSubscribeJoin_ResultSink_

@class RxInternalOperatorsOnSubscribeJoin;
@class RxSubscriber;
@class RxSubscriptionsCompositeSubscription;
@protocol JavaUtilMap;

@interface RxInternalOperatorsOnSubscribeJoin_ResultSink : NSObject {
 @public
  RxSubscriptionsCompositeSubscription *group_;
  RxSubscriber *subscriber_;
  id guard_;
  jboolean leftDone_;
  jint leftId_;
  id<JavaUtilMap> leftMap_;
  jboolean rightDone_;
  jint rightId_;
  id<JavaUtilMap> rightMap_;
}

#pragma mark Public

- (instancetype)initWithRxInternalOperatorsOnSubscribeJoin:(RxInternalOperatorsOnSubscribeJoin *)outer$
                                          withRxSubscriber:(RxSubscriber *)subscriber;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOnSubscribeJoin_ResultSink)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin_ResultSink, group_, RxSubscriptionsCompositeSubscription *)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin_ResultSink, subscriber_, RxSubscriber *)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin_ResultSink, guard_, id)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin_ResultSink, leftMap_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeJoin_ResultSink, rightMap_, id<JavaUtilMap>)

FOUNDATION_EXPORT void RxInternalOperatorsOnSubscribeJoin_ResultSink_initWithRxInternalOperatorsOnSubscribeJoin_withRxSubscriber_(RxInternalOperatorsOnSubscribeJoin_ResultSink *self, RxInternalOperatorsOnSubscribeJoin *outer$, RxSubscriber *subscriber);

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink *new_RxInternalOperatorsOnSubscribeJoin_ResultSink_initWithRxInternalOperatorsOnSubscribeJoin_withRxSubscriber_(RxInternalOperatorsOnSubscribeJoin *outer$, RxSubscriber *subscriber) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink *create_RxInternalOperatorsOnSubscribeJoin_ResultSink_initWithRxInternalOperatorsOnSubscribeJoin_withRxSubscriber_(RxInternalOperatorsOnSubscribeJoin *outer$, RxSubscriber *subscriber);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOnSubscribeJoin_ResultSink)

#endif

#if !defined (RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_) && (RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL || defined(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_INCLUDE))
#define RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_

#define RxSubscriber_RESTRICT 1
#define RxSubscriber_INCLUDE 1
#include "rx/Subscriber.h"

@class RxInternalOperatorsOnSubscribeJoin_ResultSink;
@protocol RxSubscription;

@interface RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber : RxSubscriber

#pragma mark Public

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;
#ifdef J2OBJC_RENAME_ALIASES
#define onErrorWithJavaLangThrowable onErrorWithNSException
#endif // J2OBJC_RENAME_ALIASES

- (void)onNextWithId:(id)args;

#pragma mark Protected

- (void)expireWithInt:(jint)id_
   withRxSubscription:(id<RxSubscription>)resource;

#pragma mark Package-Private

- (instancetype)initWithRxInternalOperatorsOnSubscribeJoin_ResultSink:(RxInternalOperatorsOnSubscribeJoin_ResultSink *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber)

FOUNDATION_EXPORT void RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber *self, RxInternalOperatorsOnSubscribeJoin_ResultSink *outer$);

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber *new_RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_(RxInternalOperatorsOnSubscribeJoin_ResultSink *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber *create_RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_(RxInternalOperatorsOnSubscribeJoin_ResultSink *outer$);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber)

#endif

#if !defined (RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber_) && (RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL || defined(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber_INCLUDE))
#define RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber_

#define RxSubscriber_RESTRICT 1
#define RxSubscriber_INCLUDE 1
#include "rx/Subscriber.h"

@class RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber;

@interface RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber : RxSubscriber {
 @public
  jint id__;
  jboolean once_;
}

#pragma mark Public

- (instancetype)initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber:(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber *)outer$
                                                                             withInt:(jint)id_;

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;
#ifdef J2OBJC_RENAME_ALIASES
#define onErrorWithJavaLangThrowable onErrorWithNSException
#endif // J2OBJC_RENAME_ALIASES

- (void)onNextWithId:(id)args;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber)

FOUNDATION_EXPORT void RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_withInt_(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber *self, RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber *outer$, jint id_);

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber *new_RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_withInt_(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber *outer$, jint id_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber *create_RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_withInt_(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber *outer$, jint id_);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOnSubscribeJoin_ResultSink_LeftSubscriber_LeftDurationSubscriber)

#endif

#if !defined (RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_) && (RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL || defined(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_INCLUDE))
#define RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_

#define RxSubscriber_RESTRICT 1
#define RxSubscriber_INCLUDE 1
#include "rx/Subscriber.h"

@class RxInternalOperatorsOnSubscribeJoin_ResultSink;
@protocol RxSubscription;

@interface RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber : RxSubscriber

#pragma mark Public

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;
#ifdef J2OBJC_RENAME_ALIASES
#define onErrorWithJavaLangThrowable onErrorWithNSException
#endif // J2OBJC_RENAME_ALIASES

- (void)onNextWithId:(id)args;

#pragma mark Package-Private

- (instancetype)initWithRxInternalOperatorsOnSubscribeJoin_ResultSink:(RxInternalOperatorsOnSubscribeJoin_ResultSink *)outer$;

- (void)expireWithInt:(jint)id_
   withRxSubscription:(id<RxSubscription>)resource;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber)

FOUNDATION_EXPORT void RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber *self, RxInternalOperatorsOnSubscribeJoin_ResultSink *outer$);

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber *new_RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_(RxInternalOperatorsOnSubscribeJoin_ResultSink *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber *create_RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_(RxInternalOperatorsOnSubscribeJoin_ResultSink *outer$);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber)

#endif

#if !defined (RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber_) && (RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL || defined(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber_INCLUDE))
#define RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber_

#define RxSubscriber_RESTRICT 1
#define RxSubscriber_INCLUDE 1
#include "rx/Subscriber.h"

@class RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber;

@interface RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber : RxSubscriber {
 @public
  jint id__;
  jboolean once_;
}

#pragma mark Public

- (instancetype)initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber:(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber *)outer$
                                                                              withInt:(jint)id_;

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;
#ifdef J2OBJC_RENAME_ALIASES
#define onErrorWithJavaLangThrowable onErrorWithNSException
#endif // J2OBJC_RENAME_ALIASES

- (void)onNextWithId:(id)args;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber)

FOUNDATION_EXPORT void RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_withInt_(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber *self, RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber *outer$, jint id_);

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber *new_RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_withInt_(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber *outer$, jint id_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber *create_RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber_initWithRxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_withInt_(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber *outer$, jint id_);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOnSubscribeJoin_ResultSink_RightSubscriber_RightDurationSubscriber)

#endif

#pragma pop_macro("RxInternalOperatorsOnSubscribeJoin_INCLUDE_ALL")
