//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/RxJava/src/main/java/rx/internal/operators/OperatorToObservableSortedList.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/Comparable.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/util/ArrayList.h"
#include "java/util/Collections.h"
#include "java/util/Comparator.h"
#include "java/util/List.h"
#include "rx/Subscriber.h"
#include "rx/functions/Func2.h"
#include "rx/internal/operators/OperatorToObservableSortedList.h"

@interface RxInternalOperatorsOperatorToObservableSortedList () {
 @public
  id<RxFunctionsFunc2> sortFunction_;
}

@end

J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorToObservableSortedList, sortFunction_, id<RxFunctionsFunc2>)

inline id<RxFunctionsFunc2> RxInternalOperatorsOperatorToObservableSortedList_get_defaultSortFunction();
inline id<RxFunctionsFunc2> RxInternalOperatorsOperatorToObservableSortedList_set_defaultSortFunction(id<RxFunctionsFunc2> value);
static id<RxFunctionsFunc2> RxInternalOperatorsOperatorToObservableSortedList_defaultSortFunction;
J2OBJC_STATIC_FIELD_OBJ(RxInternalOperatorsOperatorToObservableSortedList, defaultSortFunction, id<RxFunctionsFunc2>)

@interface RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction : NSObject < RxFunctionsFunc2 >

- (JavaLangInteger *)callWithId:(id)t1
                         withId:(id)t2;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction)

__attribute__((unused)) static void RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init(RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction *self);

__attribute__((unused)) static RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction *new_RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction *create_RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init();

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction)

@interface RxInternalOperatorsOperatorToObservableSortedList_$1 : RxSubscriber {
 @public
  RxInternalOperatorsOperatorToObservableSortedList *this$0_;
  id<JavaUtilList> list_;
  RxSubscriber *val$o_;
}

- (void)onStart;

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;
#ifdef J2OBJC_RENAME_ALIASES
#define onErrorWithJavaLangThrowable onErrorWithNSException
#endif // J2OBJC_RENAME_ALIASES

- (void)onNextWithId:(id)value;

- (instancetype)initWithRxInternalOperatorsOperatorToObservableSortedList:(RxInternalOperatorsOperatorToObservableSortedList *)outer$
                                                         withRxSubscriber:(RxSubscriber *)capture$0
                                                         withRxSubscriber:(RxSubscriber *)arg$0;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOperatorToObservableSortedList_$1)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorToObservableSortedList_$1, this$0_, RxInternalOperatorsOperatorToObservableSortedList *)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorToObservableSortedList_$1, list_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorToObservableSortedList_$1, val$o_, RxSubscriber *)

__attribute__((unused)) static void RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorToObservableSortedList_$1 *self, RxInternalOperatorsOperatorToObservableSortedList *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0);

__attribute__((unused)) static RxInternalOperatorsOperatorToObservableSortedList_$1 *new_RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorToObservableSortedList *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static RxInternalOperatorsOperatorToObservableSortedList_$1 *create_RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorToObservableSortedList *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOperatorToObservableSortedList_$1)

@interface RxInternalOperatorsOperatorToObservableSortedList_$1_$1 : NSObject < JavaUtilComparator > {
 @public
  RxInternalOperatorsOperatorToObservableSortedList_$1 *this$0_;
}

- (jint)compareWithId:(id)o1
               withId:(id)o2;

- (instancetype)initWithRxInternalOperatorsOperatorToObservableSortedList_$1:(RxInternalOperatorsOperatorToObservableSortedList_$1 *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOperatorToObservableSortedList_$1_$1)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorToObservableSortedList_$1_$1, this$0_, RxInternalOperatorsOperatorToObservableSortedList_$1 *)

__attribute__((unused)) static void RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(RxInternalOperatorsOperatorToObservableSortedList_$1_$1 *self, RxInternalOperatorsOperatorToObservableSortedList_$1 *outer$);

__attribute__((unused)) static RxInternalOperatorsOperatorToObservableSortedList_$1_$1 *new_RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(RxInternalOperatorsOperatorToObservableSortedList_$1 *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static RxInternalOperatorsOperatorToObservableSortedList_$1_$1 *create_RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(RxInternalOperatorsOperatorToObservableSortedList_$1 *outer$);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOperatorToObservableSortedList_$1_$1)

J2OBJC_INITIALIZED_DEFN(RxInternalOperatorsOperatorToObservableSortedList)

@implementation RxInternalOperatorsOperatorToObservableSortedList

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RxInternalOperatorsOperatorToObservableSortedList_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithRxFunctionsFunc2:(id<RxFunctionsFunc2>)sortFunction {
  RxInternalOperatorsOperatorToObservableSortedList_initWithRxFunctionsFunc2_(self, sortFunction);
  return self;
}

- (RxSubscriber *)callWithId:(RxSubscriber *)o {
  return new_RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(self, o, o);
}

+ (void)initialize {
  if (self == [RxInternalOperatorsOperatorToObservableSortedList class]) {
    RxInternalOperatorsOperatorToObservableSortedList_defaultSortFunction = new_RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init();
    J2OBJC_SET_INITIALIZED(RxInternalOperatorsOperatorToObservableSortedList)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "OperatorToObservableSortedList", NULL, 0x1, NULL, NULL },
    { "initWithRxFunctionsFunc2:", "OperatorToObservableSortedList", NULL, 0x1, NULL, "(Lrx/functions/Func2<-TT;-TT;Ljava/lang/Integer;>;)V" },
    { "callWithId:", "call", "Lrx.Subscriber;", 0x1, NULL, "(Lrx/Subscriber<-Ljava/util/List<TT;>;>;)Lrx/Subscriber<-TT;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "sortFunction_", NULL, 0x12, "Lrx.functions.Func2;", NULL, "Lrx/functions/Func2<-TT;-TT;Ljava/lang/Integer;>;", .constantValue.asLong = 0 },
    { "defaultSortFunction", "defaultSortFunction", 0xa, "Lrx.functions.Func2;", &RxInternalOperatorsOperatorToObservableSortedList_defaultSortFunction, NULL, .constantValue.asLong = 0 },
  };
  static const char *inner_classes[] = {"Lrx.internal.operators.OperatorToObservableSortedList$DefaultComparableFunction;"};
  static const J2ObjcClassInfo _RxInternalOperatorsOperatorToObservableSortedList = { 2, "OperatorToObservableSortedList", "rx.internal.operators", NULL, 0x11, 3, methods, 2, fields, 0, NULL, 1, inner_classes, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;Lrx/Observable$Operator<Ljava/util/List<TT;>;TT;>;" };
  return &_RxInternalOperatorsOperatorToObservableSortedList;
}

@end

void RxInternalOperatorsOperatorToObservableSortedList_init(RxInternalOperatorsOperatorToObservableSortedList *self) {
  NSObject_init(self);
  self->sortFunction_ = RxInternalOperatorsOperatorToObservableSortedList_defaultSortFunction;
}

RxInternalOperatorsOperatorToObservableSortedList *new_RxInternalOperatorsOperatorToObservableSortedList_init() {
  RxInternalOperatorsOperatorToObservableSortedList *self = [RxInternalOperatorsOperatorToObservableSortedList alloc];
  RxInternalOperatorsOperatorToObservableSortedList_init(self);
  return self;
}

RxInternalOperatorsOperatorToObservableSortedList *create_RxInternalOperatorsOperatorToObservableSortedList_init() {
  return new_RxInternalOperatorsOperatorToObservableSortedList_init();
}

void RxInternalOperatorsOperatorToObservableSortedList_initWithRxFunctionsFunc2_(RxInternalOperatorsOperatorToObservableSortedList *self, id<RxFunctionsFunc2> sortFunction) {
  NSObject_init(self);
  self->sortFunction_ = sortFunction;
}

RxInternalOperatorsOperatorToObservableSortedList *new_RxInternalOperatorsOperatorToObservableSortedList_initWithRxFunctionsFunc2_(id<RxFunctionsFunc2> sortFunction) {
  RxInternalOperatorsOperatorToObservableSortedList *self = [RxInternalOperatorsOperatorToObservableSortedList alloc];
  RxInternalOperatorsOperatorToObservableSortedList_initWithRxFunctionsFunc2_(self, sortFunction);
  return self;
}

RxInternalOperatorsOperatorToObservableSortedList *create_RxInternalOperatorsOperatorToObservableSortedList_initWithRxFunctionsFunc2_(id<RxFunctionsFunc2> sortFunction) {
  return new_RxInternalOperatorsOperatorToObservableSortedList_initWithRxFunctionsFunc2_(sortFunction);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOperatorToObservableSortedList)

@implementation RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction

- (JavaLangInteger *)callWithId:(id)t1
                         withId:(id)t2 {
  id<JavaLangComparable> c1 = (id<JavaLangComparable>) cast_check(t1, JavaLangComparable_class_());
  id<JavaLangComparable> c2 = (id<JavaLangComparable>) cast_check(t2, JavaLangComparable_class_());
  return JavaLangInteger_valueOfWithInt_([((id<JavaLangComparable>) nil_chk(c1)) compareToWithId:c2]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "callWithId:withId:", "call", "Ljava.lang.Integer;", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x2, NULL, NULL },
  };
  static const J2ObjcClassInfo _RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction = { 2, "DefaultComparableFunction", "rx.internal.operators", "OperatorToObservableSortedList", 0xa, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "Ljava/lang/Object;Lrx/functions/Func2<Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Integer;>;" };
  return &_RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction;
}

@end

void RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init(RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction *self) {
  NSObject_init(self);
}

RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction *new_RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init() {
  RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction *self = [RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction alloc];
  RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init(self);
  return self;
}

RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction *create_RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init() {
  return new_RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction_init();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOperatorToObservableSortedList_DefaultComparableFunction)

@implementation RxInternalOperatorsOperatorToObservableSortedList_$1

- (void)onStart {
  [self requestWithLong:JavaLangLong_MAX_VALUE];
}

- (void)onCompleted {
  @try {
    JavaUtilCollections_sortWithJavaUtilList_withJavaUtilComparator_(list_, new_RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(self));
    [((RxSubscriber *) nil_chk(val$o_)) onNextWithId:JavaUtilCollections_unmodifiableListWithJavaUtilList_(list_)];
    [val$o_ onCompleted];
  }
  @catch (NSException *e) {
    [self onErrorWithNSException:e];
  }
}

- (void)onErrorWithNSException:(NSException *)e {
  [((RxSubscriber *) nil_chk(val$o_)) onErrorWithNSException:e];
}

- (void)onNextWithId:(id)value {
  [((id<JavaUtilList>) nil_chk(list_)) addWithId:value];
}

- (instancetype)initWithRxInternalOperatorsOperatorToObservableSortedList:(RxInternalOperatorsOperatorToObservableSortedList *)outer$
                                                         withRxSubscriber:(RxSubscriber *)capture$0
                                                         withRxSubscriber:(RxSubscriber *)arg$0 {
  RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(self, outer$, capture$0, arg$0);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onStart", NULL, "V", 0x1, NULL, NULL },
    { "onCompleted", NULL, "V", 0x1, NULL, NULL },
    { "onErrorWithNSException:", "onError", "V", 0x1, NULL, NULL },
    { "onNextWithId:", "onNext", "V", 0x1, NULL, "(TT;)V" },
    { "initWithRxInternalOperatorsOperatorToObservableSortedList:withRxSubscriber:withRxSubscriber:", "", NULL, 0x0, NULL, "(Lrx/internal/operators/OperatorToObservableSortedList;Lrx/Subscriber<-Ljava/util/List<TT;>;>;Lrx/Subscriber<*>;)V" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lrx.internal.operators.OperatorToObservableSortedList;", NULL, NULL, .constantValue.asLong = 0 },
    { "list_", NULL, 0x10, "Ljava.util.List;", NULL, "Ljava/util/List<TT;>;", .constantValue.asLong = 0 },
    { "val$o_", NULL, 0x1012, "Lrx.Subscriber;", NULL, "Lrx/Subscriber<-Ljava/util/List<TT;>;>;", .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"TT;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "RxInternalOperatorsOperatorToObservableSortedList", "callWithId:" };
  static const J2ObjcClassInfo _RxInternalOperatorsOperatorToObservableSortedList_$1 = { 2, "", "rx.internal.operators", "OperatorToObservableSortedList", 0x8008, 5, methods, 3, fields, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lrx/Subscriber<TT;>;" };
  return &_RxInternalOperatorsOperatorToObservableSortedList_$1;
}

@end

void RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorToObservableSortedList_$1 *self, RxInternalOperatorsOperatorToObservableSortedList *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0) {
  self->this$0_ = outer$;
  self->val$o_ = capture$0;
  RxSubscriber_initWithRxSubscriber_(self, arg$0);
  self->list_ = new_JavaUtilArrayList_init();
}

RxInternalOperatorsOperatorToObservableSortedList_$1 *new_RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorToObservableSortedList *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0) {
  RxInternalOperatorsOperatorToObservableSortedList_$1 *self = [RxInternalOperatorsOperatorToObservableSortedList_$1 alloc];
  RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(self, outer$, capture$0, arg$0);
  return self;
}

RxInternalOperatorsOperatorToObservableSortedList_$1 *create_RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorToObservableSortedList *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0) {
  return new_RxInternalOperatorsOperatorToObservableSortedList_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_withRxSubscriber_withRxSubscriber_(outer$, capture$0, arg$0);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOperatorToObservableSortedList_$1)

@implementation RxInternalOperatorsOperatorToObservableSortedList_$1_$1

- (jint)compareWithId:(id)o1
               withId:(id)o2 {
  return [((JavaLangInteger *) nil_chk([((id<RxFunctionsFunc2>) nil_chk(this$0_->this$0_->sortFunction_)) callWithId:o1 withId:o2])) intValue];
}

- (instancetype)initWithRxInternalOperatorsOperatorToObservableSortedList_$1:(RxInternalOperatorsOperatorToObservableSortedList_$1 *)outer$ {
  RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "compareWithId:withId:", "compare", "I", 0x1, NULL, "(TT;TT;)I" },
    { "initWithRxInternalOperatorsOperatorToObservableSortedList_$1:", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lrx.internal.operators.OperatorToObservableSortedList$1;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "RxInternalOperatorsOperatorToObservableSortedList_$1", "onCompleted" };
  static const J2ObjcClassInfo _RxInternalOperatorsOperatorToObservableSortedList_$1_$1 = { 2, "", "rx.internal.operators", "OperatorToObservableSortedList$", 0x8008, 2, methods, 1, fields, 0, NULL, 0, NULL, &enclosing_method, "Ljava/lang/Object;Ljava/util/Comparator<TT;>;" };
  return &_RxInternalOperatorsOperatorToObservableSortedList_$1_$1;
}

@end

void RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(RxInternalOperatorsOperatorToObservableSortedList_$1_$1 *self, RxInternalOperatorsOperatorToObservableSortedList_$1 *outer$) {
  self->this$0_ = outer$;
  NSObject_init(self);
}

RxInternalOperatorsOperatorToObservableSortedList_$1_$1 *new_RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(RxInternalOperatorsOperatorToObservableSortedList_$1 *outer$) {
  RxInternalOperatorsOperatorToObservableSortedList_$1_$1 *self = [RxInternalOperatorsOperatorToObservableSortedList_$1_$1 alloc];
  RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(self, outer$);
  return self;
}

RxInternalOperatorsOperatorToObservableSortedList_$1_$1 *create_RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(RxInternalOperatorsOperatorToObservableSortedList_$1 *outer$) {
  return new_RxInternalOperatorsOperatorToObservableSortedList_$1_$1_initWithRxInternalOperatorsOperatorToObservableSortedList_$1_(outer$);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOperatorToObservableSortedList_$1_$1)
