//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/RxJava/src/main/java/rx/internal/operators/OperatorOnBackpressureBuffer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RxInternalOperatorsOperatorOnBackpressureBuffer_INCLUDE_ALL")
#ifdef RxInternalOperatorsOperatorOnBackpressureBuffer_RESTRICT
#define RxInternalOperatorsOperatorOnBackpressureBuffer_INCLUDE_ALL 0
#else
#define RxInternalOperatorsOperatorOnBackpressureBuffer_INCLUDE_ALL 1
#endif
#undef RxInternalOperatorsOperatorOnBackpressureBuffer_RESTRICT

#if !defined (RxInternalOperatorsOperatorOnBackpressureBuffer_) && (RxInternalOperatorsOperatorOnBackpressureBuffer_INCLUDE_ALL || defined(RxInternalOperatorsOperatorOnBackpressureBuffer_INCLUDE))
#define RxInternalOperatorsOperatorOnBackpressureBuffer_

#define RxObservable_RESTRICT 1
#define RxObservable_Operator_INCLUDE 1
#include "rx/Observable.h"

@class RxSubscriber;

@interface RxInternalOperatorsOperatorOnBackpressureBuffer : NSObject < RxObservable_Operator >

#pragma mark Public

- (instancetype)init;

- (RxSubscriber *)callWithId:(RxSubscriber *)child;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOperatorOnBackpressureBuffer)

FOUNDATION_EXPORT void RxInternalOperatorsOperatorOnBackpressureBuffer_init(RxInternalOperatorsOperatorOnBackpressureBuffer *self);

FOUNDATION_EXPORT RxInternalOperatorsOperatorOnBackpressureBuffer *new_RxInternalOperatorsOperatorOnBackpressureBuffer_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOperatorOnBackpressureBuffer *create_RxInternalOperatorsOperatorOnBackpressureBuffer_init();

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOperatorOnBackpressureBuffer)

#endif

#pragma pop_macro("RxInternalOperatorsOperatorOnBackpressureBuffer_INCLUDE_ALL")
