./copyoutput.sh androidbase/trans/lib/build/
./copyoutput.sh commons-io/trans/commons-io/build/
./copyoutput.sh commons-lang3/trans/commons-lang3/build/
./copyoutput.sh cupboard/trans/cupboard/build/
./copyoutput.sh dagger/trans/core/build/
./copyoutput.sh eventbus/trans/eb/build/
./copyoutput.sh greendao/trans/greendao/build/
./copyoutput.sh gson/trans/gson/build/
./copyoutput.sh intellij/trans/intellij/build/
./copyoutput.sh magicthreads/trans/magicthreads/build/
./copyoutput.sh retrofit/trans/retrofit/build/
./copyoutput.sh rxandroid/trans/rxandroid/build/
./copyoutput.sh rxjava/trans/rxjava/build/
./copyoutput.sh squeaky/trans/core/build/
./copyoutput.sh squeaky/trans/query/build/
./copyoutput.sh truth/trans/core/build/
