//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/EventBus/EventBus/src/de/greenrobot/event/EventBusException.java
//

#include "J2ObjC_source.h"
#include "de/greenrobot/event/EventBusException.h"
#include "java/lang/RuntimeException.h"

inline jlong DeGreenrobotEventEventBusException_get_serialVersionUID();
#define DeGreenrobotEventEventBusException_serialVersionUID -2912559384646531479LL
J2OBJC_STATIC_FIELD_CONSTANT(DeGreenrobotEventEventBusException, serialVersionUID, jlong)

@implementation DeGreenrobotEventEventBusException

- (instancetype)initWithNSString:(NSString *)detailMessage {
  DeGreenrobotEventEventBusException_initWithNSString_(self, detailMessage);
  return self;
}

- (instancetype)initWithNSException:(NSException *)throwable {
  DeGreenrobotEventEventBusException_initWithNSException_(self, throwable);
  return self;
}

- (instancetype)initWithNSString:(NSString *)detailMessage
                 withNSException:(NSException *)throwable {
  DeGreenrobotEventEventBusException_initWithNSString_withNSException_(self, detailMessage, throwable);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "EventBusException", NULL, 0x1, NULL, NULL },
    { "initWithNSException:", "EventBusException", NULL, 0x1, NULL, NULL },
    { "initWithNSString:withNSException:", "EventBusException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = DeGreenrobotEventEventBusException_serialVersionUID },
  };
  static const J2ObjcClassInfo _DeGreenrobotEventEventBusException = { 2, "EventBusException", "de.greenrobot.event", NULL, 0x1, 3, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_DeGreenrobotEventEventBusException;
}

@end

void DeGreenrobotEventEventBusException_initWithNSString_(DeGreenrobotEventEventBusException *self, NSString *detailMessage) {
  JavaLangRuntimeException_initWithNSString_(self, detailMessage);
}

DeGreenrobotEventEventBusException *new_DeGreenrobotEventEventBusException_initWithNSString_(NSString *detailMessage) {
  DeGreenrobotEventEventBusException *self = [DeGreenrobotEventEventBusException alloc];
  DeGreenrobotEventEventBusException_initWithNSString_(self, detailMessage);
  return self;
}

DeGreenrobotEventEventBusException *create_DeGreenrobotEventEventBusException_initWithNSString_(NSString *detailMessage) {
  return new_DeGreenrobotEventEventBusException_initWithNSString_(detailMessage);
}

void DeGreenrobotEventEventBusException_initWithNSException_(DeGreenrobotEventEventBusException *self, NSException *throwable) {
  JavaLangRuntimeException_initWithNSException_(self, throwable);
}

DeGreenrobotEventEventBusException *new_DeGreenrobotEventEventBusException_initWithNSException_(NSException *throwable) {
  DeGreenrobotEventEventBusException *self = [DeGreenrobotEventEventBusException alloc];
  DeGreenrobotEventEventBusException_initWithNSException_(self, throwable);
  return self;
}

DeGreenrobotEventEventBusException *create_DeGreenrobotEventEventBusException_initWithNSException_(NSException *throwable) {
  return new_DeGreenrobotEventEventBusException_initWithNSException_(throwable);
}

void DeGreenrobotEventEventBusException_initWithNSString_withNSException_(DeGreenrobotEventEventBusException *self, NSString *detailMessage, NSException *throwable) {
  JavaLangRuntimeException_initWithNSString_withNSException_(self, detailMessage, throwable);
}

DeGreenrobotEventEventBusException *new_DeGreenrobotEventEventBusException_initWithNSString_withNSException_(NSString *detailMessage, NSException *throwable) {
  DeGreenrobotEventEventBusException *self = [DeGreenrobotEventEventBusException alloc];
  DeGreenrobotEventEventBusException_initWithNSString_withNSException_(self, detailMessage, throwable);
  return self;
}

DeGreenrobotEventEventBusException *create_DeGreenrobotEventEventBusException_initWithNSString_withNSException_(NSString *detailMessage, NSException *throwable) {
  return new_DeGreenrobotEventEventBusException_initWithNSString_withNSException_(detailMessage, throwable);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DeGreenrobotEventEventBusException)
