//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/EventBus/EventBus/src/de/greenrobot/event/NoSubscriberEvent.java
//

#include "J2ObjC_source.h"
#include "de/greenrobot/event/EventBus.h"
#include "de/greenrobot/event/NoSubscriberEvent.h"

@implementation DeGreenrobotEventNoSubscriberEvent

- (instancetype)initWithDeGreenrobotEventEventBus:(DeGreenrobotEventEventBus *)eventBus
                                           withId:(id)originalEvent {
  DeGreenrobotEventNoSubscriberEvent_initWithDeGreenrobotEventEventBus_withId_(self, eventBus, originalEvent);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithDeGreenrobotEventEventBus:withId:", "NoSubscriberEvent", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "eventBus_", NULL, 0x11, "Lde.greenrobot.event.EventBus;", NULL, NULL, .constantValue.asLong = 0 },
    { "originalEvent_", NULL, 0x11, "Ljava.lang.Object;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _DeGreenrobotEventNoSubscriberEvent = { 2, "NoSubscriberEvent", "de.greenrobot.event", NULL, 0x11, 1, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_DeGreenrobotEventNoSubscriberEvent;
}

@end

void DeGreenrobotEventNoSubscriberEvent_initWithDeGreenrobotEventEventBus_withId_(DeGreenrobotEventNoSubscriberEvent *self, DeGreenrobotEventEventBus *eventBus, id originalEvent) {
  NSObject_init(self);
  self->eventBus_ = eventBus;
  self->originalEvent_ = originalEvent;
}

DeGreenrobotEventNoSubscriberEvent *new_DeGreenrobotEventNoSubscriberEvent_initWithDeGreenrobotEventEventBus_withId_(DeGreenrobotEventEventBus *eventBus, id originalEvent) {
  DeGreenrobotEventNoSubscriberEvent *self = [DeGreenrobotEventNoSubscriberEvent alloc];
  DeGreenrobotEventNoSubscriberEvent_initWithDeGreenrobotEventEventBus_withId_(self, eventBus, originalEvent);
  return self;
}

DeGreenrobotEventNoSubscriberEvent *create_DeGreenrobotEventNoSubscriberEvent_initWithDeGreenrobotEventEventBus_withId_(DeGreenrobotEventEventBus *eventBus, id originalEvent) {
  return new_DeGreenrobotEventNoSubscriberEvent_initWithDeGreenrobotEventEventBus_withId_(eventBus, originalEvent);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DeGreenrobotEventNoSubscriberEvent)
