//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/okhttp/okhttp/src/main/java/com/squareup/okhttp/internal/Network.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComSquareupOkhttpInternalNetwork_INCLUDE_ALL")
#ifdef ComSquareupOkhttpInternalNetwork_RESTRICT
#define ComSquareupOkhttpInternalNetwork_INCLUDE_ALL 0
#else
#define ComSquareupOkhttpInternalNetwork_INCLUDE_ALL 1
#endif
#undef ComSquareupOkhttpInternalNetwork_RESTRICT

#if !defined (ComSquareupOkhttpInternalNetwork_) && (ComSquareupOkhttpInternalNetwork_INCLUDE_ALL || defined(ComSquareupOkhttpInternalNetwork_INCLUDE))
#define ComSquareupOkhttpInternalNetwork_

@class IOSObjectArray;

@protocol ComSquareupOkhttpInternalNetwork < NSObject, JavaObject >

- (IOSObjectArray *)resolveInetAddressesWithNSString:(NSString *)host;

@end

@interface ComSquareupOkhttpInternalNetwork : NSObject

@end

J2OBJC_STATIC_INIT(ComSquareupOkhttpInternalNetwork)

inline id<ComSquareupOkhttpInternalNetwork> ComSquareupOkhttpInternalNetwork_get_DEFAULT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<ComSquareupOkhttpInternalNetwork> ComSquareupOkhttpInternalNetwork_DEFAULT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComSquareupOkhttpInternalNetwork, DEFAULT, id<ComSquareupOkhttpInternalNetwork>)

J2OBJC_TYPE_LITERAL_HEADER(ComSquareupOkhttpInternalNetwork)

#endif

#pragma pop_macro("ComSquareupOkhttpInternalNetwork_INCLUDE_ALL")
