//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/okhttp/okhttp/src/main/java/com/squareup/okhttp/internal/Version.java
//

#include "J2ObjC_source.h"
#include "com/squareup/okhttp/internal/Version.h"

@interface ComSquareupOkhttpInternalVersion ()

- (instancetype)init;

@end

__attribute__((unused)) static void ComSquareupOkhttpInternalVersion_init(ComSquareupOkhttpInternalVersion *self);

__attribute__((unused)) static ComSquareupOkhttpInternalVersion *new_ComSquareupOkhttpInternalVersion_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComSquareupOkhttpInternalVersion *create_ComSquareupOkhttpInternalVersion_init();

@implementation ComSquareupOkhttpInternalVersion

+ (NSString *)userAgent {
  return ComSquareupOkhttpInternalVersion_userAgent();
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComSquareupOkhttpInternalVersion_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "userAgent", NULL, "Ljava.lang.String;", 0x9, NULL, NULL },
    { "init", "Version", NULL, 0x2, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComSquareupOkhttpInternalVersion = { 2, "Version", "com.squareup.okhttp.internal", NULL, 0x1, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComSquareupOkhttpInternalVersion;
}

@end

NSString *ComSquareupOkhttpInternalVersion_userAgent() {
  ComSquareupOkhttpInternalVersion_initialize();
  return @"okhttp/2.2.0";
}

void ComSquareupOkhttpInternalVersion_init(ComSquareupOkhttpInternalVersion *self) {
  NSObject_init(self);
}

ComSquareupOkhttpInternalVersion *new_ComSquareupOkhttpInternalVersion_init() {
  ComSquareupOkhttpInternalVersion *self = [ComSquareupOkhttpInternalVersion alloc];
  ComSquareupOkhttpInternalVersion_init(self);
  return self;
}

ComSquareupOkhttpInternalVersion *create_ComSquareupOkhttpInternalVersion_init() {
  return new_ComSquareupOkhttpInternalVersion_init();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComSquareupOkhttpInternalVersion)
