//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/squeaky/core/src/main/java/co/touchlab/squeaky/table/DatabaseQuery.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "co/touchlab/squeaky/table/DatabaseQuery.h"

@interface CoTouchlabSqueakyTableDatabaseQuery : NSObject

@end

@implementation CoTouchlabSqueakyTableDatabaseQuery

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "fromQuery", "fromQuery", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "fromQueryDefault", "fromQuery", "Ljava.lang.String;", 0x100a, NULL, NULL },
  };
  static const J2ObjcClassInfo _CoTouchlabSqueakyTableDatabaseQuery = { 2, "DatabaseQuery", "co.touchlab.squeaky.table", NULL, 0x2609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_CoTouchlabSqueakyTableDatabaseQuery;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(CoTouchlabSqueakyTableDatabaseQuery)
