//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/androidbase/AndroidBase/lib/src/main/java/android/database/CursorIndexOutOfBoundsException.java
//

#include "J2ObjC_source.h"
#include "android/database/CursorIndexOutOfBoundsException.h"
#include "java/lang/IndexOutOfBoundsException.h"

@implementation AndroidDatabaseCursorIndexOutOfBoundsException

- (instancetype)initWithInt:(jint)index
                    withInt:(jint)size {
  AndroidDatabaseCursorIndexOutOfBoundsException_initWithInt_withInt_(self, index, size);
  return self;
}

- (instancetype)initWithNSString:(NSString *)message {
  AndroidDatabaseCursorIndexOutOfBoundsException_initWithNSString_(self, message);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithInt:withInt:", "CursorIndexOutOfBoundsException", NULL, 0x1, NULL, NULL },
    { "initWithNSString:", "CursorIndexOutOfBoundsException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _AndroidDatabaseCursorIndexOutOfBoundsException = { 2, "CursorIndexOutOfBoundsException", "android.database", NULL, 0x1, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_AndroidDatabaseCursorIndexOutOfBoundsException;
}

@end

void AndroidDatabaseCursorIndexOutOfBoundsException_initWithInt_withInt_(AndroidDatabaseCursorIndexOutOfBoundsException *self, jint index, jint size) {
  JavaLangIndexOutOfBoundsException_initWithNSString_(self, JreStrcat("$I$I", @"Index ", index, @" requested, with a size of ", size));
}

AndroidDatabaseCursorIndexOutOfBoundsException *new_AndroidDatabaseCursorIndexOutOfBoundsException_initWithInt_withInt_(jint index, jint size) {
  J2OBJC_NEW_IMPL(AndroidDatabaseCursorIndexOutOfBoundsException, initWithInt_withInt_, index, size)
}

AndroidDatabaseCursorIndexOutOfBoundsException *create_AndroidDatabaseCursorIndexOutOfBoundsException_initWithInt_withInt_(jint index, jint size) {
  J2OBJC_CREATE_IMPL(AndroidDatabaseCursorIndexOutOfBoundsException, initWithInt_withInt_, index, size)
}

void AndroidDatabaseCursorIndexOutOfBoundsException_initWithNSString_(AndroidDatabaseCursorIndexOutOfBoundsException *self, NSString *message) {
  JavaLangIndexOutOfBoundsException_initWithNSString_(self, message);
}

AndroidDatabaseCursorIndexOutOfBoundsException *new_AndroidDatabaseCursorIndexOutOfBoundsException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(AndroidDatabaseCursorIndexOutOfBoundsException, initWithNSString_, message)
}

AndroidDatabaseCursorIndexOutOfBoundsException *create_AndroidDatabaseCursorIndexOutOfBoundsException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(AndroidDatabaseCursorIndexOutOfBoundsException, initWithNSString_, message)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidDatabaseCursorIndexOutOfBoundsException)
