//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/dagger/core/src/main/java/dagger/internal/Factory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("DaggerInternalFactory_INCLUDE_ALL")
#ifdef DaggerInternalFactory_RESTRICT
#define DaggerInternalFactory_INCLUDE_ALL 0
#else
#define DaggerInternalFactory_INCLUDE_ALL 1
#endif
#undef DaggerInternalFactory_RESTRICT

#if !defined (DaggerInternalFactory_) && (DaggerInternalFactory_INCLUDE_ALL || defined(DaggerInternalFactory_INCLUDE))
#define DaggerInternalFactory_

#define JavaxInjectProvider_RESTRICT 1
#define JavaxInjectProvider_INCLUDE 1
#include "javax/inject/Provider.h"

@protocol DaggerInternalFactory < JavaxInjectProvider, NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalFactory)

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalFactory)

#endif

#pragma pop_macro("DaggerInternalFactory_INCLUDE_ALL")
