source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GsonFramework2_Example', :exclusive => true do
  pod 'GsonFramework2', :path => '../'
end

target 'GsonFramework2_Tests', :exclusive => true do
  pod 'GsonFramework2', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
