//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/gson/gson/src/main/java/com/google/gson/internal/$Gson$Preconditions.java
//

#include "J2ObjC_source.h"
#include "com/google/gson/internal/$Gson$Preconditions.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/NullPointerException.h"
#include "java/lang/UnsupportedOperationException.h"

@interface ComGoogleGsonInternal$Gson$Preconditions ()

- (instancetype)init;

@end

__attribute__((unused)) static void ComGoogleGsonInternal$Gson$Preconditions_init(ComGoogleGsonInternal$Gson$Preconditions *self);

__attribute__((unused)) static ComGoogleGsonInternal$Gson$Preconditions *new_ComGoogleGsonInternal$Gson$Preconditions_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleGsonInternal$Gson$Preconditions *create_ComGoogleGsonInternal$Gson$Preconditions_init();

@implementation ComGoogleGsonInternal$Gson$Preconditions

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonInternal$Gson$Preconditions_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (id)checkNotNullWithId:(id)obj {
  return ComGoogleGsonInternal$Gson$Preconditions_checkNotNullWithId_(obj);
}

+ (void)checkArgumentWithBoolean:(jboolean)condition {
  ComGoogleGsonInternal$Gson$Preconditions_checkArgumentWithBoolean_(condition);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "$Gson$Preconditions", NULL, 0x2, NULL, NULL },
    { "checkNotNullWithId:", "checkNotNull", "TT;", 0x9, NULL, "<T:Ljava/lang/Object;>(TT;)TT;" },
    { "checkArgumentWithBoolean:", "checkArgument", "V", 0x9, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternal$Gson$Preconditions = { 2, "$Gson$Preconditions", "com.google.gson.internal", NULL, 0x11, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonInternal$Gson$Preconditions;
}

@end

void ComGoogleGsonInternal$Gson$Preconditions_init(ComGoogleGsonInternal$Gson$Preconditions *self) {
  NSObject_init(self);
  @throw new_JavaLangUnsupportedOperationException_init();
}

ComGoogleGsonInternal$Gson$Preconditions *new_ComGoogleGsonInternal$Gson$Preconditions_init() {
  ComGoogleGsonInternal$Gson$Preconditions *self = [ComGoogleGsonInternal$Gson$Preconditions alloc];
  ComGoogleGsonInternal$Gson$Preconditions_init(self);
  return self;
}

ComGoogleGsonInternal$Gson$Preconditions *create_ComGoogleGsonInternal$Gson$Preconditions_init() {
  return new_ComGoogleGsonInternal$Gson$Preconditions_init();
}

id ComGoogleGsonInternal$Gson$Preconditions_checkNotNullWithId_(id obj) {
  ComGoogleGsonInternal$Gson$Preconditions_initialize();
  if (obj == nil) {
    @throw new_JavaLangNullPointerException_init();
  }
  return obj;
}

void ComGoogleGsonInternal$Gson$Preconditions_checkArgumentWithBoolean_(jboolean condition) {
  ComGoogleGsonInternal$Gson$Preconditions_initialize();
  if (!condition) {
    @throw new_JavaLangIllegalArgumentException_init();
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternal$Gson$Preconditions)
