//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/gson/gson/src/main/java/com/google/gson/internal/UnsafeAllocator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleGsonInternalUnsafeAllocator_INCLUDE_ALL")
#ifdef ComGoogleGsonInternalUnsafeAllocator_RESTRICT
#define ComGoogleGsonInternalUnsafeAllocator_INCLUDE_ALL 0
#else
#define ComGoogleGsonInternalUnsafeAllocator_INCLUDE_ALL 1
#endif
#undef ComGoogleGsonInternalUnsafeAllocator_RESTRICT

#if !defined (ComGoogleGsonInternalUnsafeAllocator_) && (ComGoogleGsonInternalUnsafeAllocator_INCLUDE_ALL || defined(ComGoogleGsonInternalUnsafeAllocator_INCLUDE))
#define ComGoogleGsonInternalUnsafeAllocator_

@class IOSClass;

@interface ComGoogleGsonInternalUnsafeAllocator : NSObject

#pragma mark Public

- (instancetype)init;

+ (ComGoogleGsonInternalUnsafeAllocator *)create;

- (id)newInstanceWithIOSClass:(IOSClass *)c OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalUnsafeAllocator)

FOUNDATION_EXPORT ComGoogleGsonInternalUnsafeAllocator *ComGoogleGsonInternalUnsafeAllocator_create();

FOUNDATION_EXPORT void ComGoogleGsonInternalUnsafeAllocator_init(ComGoogleGsonInternalUnsafeAllocator *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalUnsafeAllocator)

#endif

#pragma pop_macro("ComGoogleGsonInternalUnsafeAllocator_INCLUDE_ALL")
