//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/RxJava/src/main/java/rx/functions/Func5.java
//

#include "J2ObjC_source.h"
#include "rx/functions/Func5.h"

@interface RxFunctionsFunc5 : NSObject

@end

@implementation RxFunctionsFunc5

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "callWithId:withId:withId:withId:withId:", "call", "TR;", 0x401, NULL, "(TT1;TT2;TT3;TT4;TT5;)TR;" },
  };
  static const J2ObjcClassInfo _RxFunctionsFunc5 = { 2, "Func5", "rx.functions", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "<T1:Ljava/lang/Object;T2:Ljava/lang/Object;T3:Ljava/lang/Object;T4:Ljava/lang/Object;T5:Ljava/lang/Object;R:Ljava/lang/Object;>Ljava/lang/Object;Lrx/functions/Function;" };
  return &_RxFunctionsFunc5;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RxFunctionsFunc5)
