//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/androidbase/AndroidBase/lib/src/main/java/android/annotation/NonNull.java
//

#include "J2ObjC_header.h"

#pragma push_macro("AndroidAnnotationNonNull_INCLUDE_ALL")
#ifdef AndroidAnnotationNonNull_RESTRICT
#define AndroidAnnotationNonNull_INCLUDE_ALL 0
#else
#define AndroidAnnotationNonNull_INCLUDE_ALL 1
#endif
#undef AndroidAnnotationNonNull_RESTRICT

#if !defined (AndroidAnnotationNonNull_) && (AndroidAnnotationNonNull_INCLUDE_ALL || defined(AndroidAnnotationNonNull_INCLUDE))
#define AndroidAnnotationNonNull_

#define JavaLangAnnotationAnnotation_RESTRICT 1
#define JavaLangAnnotationAnnotation_INCLUDE 1
#include "java/lang/annotation/Annotation.h"

@protocol AndroidAnnotationNonNull < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidAnnotationNonNull)

J2OBJC_TYPE_LITERAL_HEADER(AndroidAnnotationNonNull)

#endif

#pragma pop_macro("AndroidAnnotationNonNull_INCLUDE_ALL")
