//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/okhttp/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpTransport.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComSquareupOkhttpInternalHttpHttpTransport_INCLUDE_ALL")
#ifdef ComSquareupOkhttpInternalHttpHttpTransport_RESTRICT
#define ComSquareupOkhttpInternalHttpHttpTransport_INCLUDE_ALL 0
#else
#define ComSquareupOkhttpInternalHttpHttpTransport_INCLUDE_ALL 1
#endif
#undef ComSquareupOkhttpInternalHttpHttpTransport_RESTRICT

#if !defined (ComSquareupOkhttpInternalHttpHttpTransport_) && (ComSquareupOkhttpInternalHttpHttpTransport_INCLUDE_ALL || defined(ComSquareupOkhttpInternalHttpHttpTransport_INCLUDE))
#define ComSquareupOkhttpInternalHttpHttpTransport_

#define ComSquareupOkhttpInternalHttpTransport_RESTRICT 1
#define ComSquareupOkhttpInternalHttpTransport_INCLUDE 1
#include "com/squareup/okhttp/internal/http/Transport.h"

@class ComSquareupOkhttpInternalHttpHttpConnection;
@class ComSquareupOkhttpInternalHttpHttpEngine;
@class ComSquareupOkhttpInternalHttpRetryableSink;
@class ComSquareupOkhttpRequest;
@class ComSquareupOkhttpResponse;
@class ComSquareupOkhttpResponseBody;
@class ComSquareupOkhttpResponse_Builder;
@protocol OkioSink;

@interface ComSquareupOkhttpInternalHttpHttpTransport : NSObject < ComSquareupOkhttpInternalHttpTransport >

#pragma mark Public

- (instancetype)initWithComSquareupOkhttpInternalHttpHttpEngine:(ComSquareupOkhttpInternalHttpHttpEngine *)httpEngine
                withComSquareupOkhttpInternalHttpHttpConnection:(ComSquareupOkhttpInternalHttpHttpConnection *)httpConnection;

- (jboolean)canReuseConnection;

- (id<OkioSink>)createRequestBodyWithComSquareupOkhttpRequest:(ComSquareupOkhttpRequest *)request
                                                     withLong:(jlong)contentLength;

- (void)disconnectWithComSquareupOkhttpInternalHttpHttpEngine:(ComSquareupOkhttpInternalHttpHttpEngine *)engine;

- (void)finishRequest;

- (ComSquareupOkhttpResponseBody *)openResponseBodyWithComSquareupOkhttpResponse:(ComSquareupOkhttpResponse *)response;

- (ComSquareupOkhttpResponse_Builder *)readResponseHeaders;

- (void)releaseConnectionOnIdle;

- (void)writeRequestBodyWithComSquareupOkhttpInternalHttpRetryableSink:(ComSquareupOkhttpInternalHttpRetryableSink *)requestBody;

- (void)writeRequestHeadersWithComSquareupOkhttpRequest:(ComSquareupOkhttpRequest *)request;

@end

J2OBJC_EMPTY_STATIC_INIT(ComSquareupOkhttpInternalHttpHttpTransport)

FOUNDATION_EXPORT void ComSquareupOkhttpInternalHttpHttpTransport_initWithComSquareupOkhttpInternalHttpHttpEngine_withComSquareupOkhttpInternalHttpHttpConnection_(ComSquareupOkhttpInternalHttpHttpTransport *self, ComSquareupOkhttpInternalHttpHttpEngine *httpEngine, ComSquareupOkhttpInternalHttpHttpConnection *httpConnection);

FOUNDATION_EXPORT ComSquareupOkhttpInternalHttpHttpTransport *new_ComSquareupOkhttpInternalHttpHttpTransport_initWithComSquareupOkhttpInternalHttpHttpEngine_withComSquareupOkhttpInternalHttpHttpConnection_(ComSquareupOkhttpInternalHttpHttpEngine *httpEngine, ComSquareupOkhttpInternalHttpHttpConnection *httpConnection) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComSquareupOkhttpInternalHttpHttpTransport *create_ComSquareupOkhttpInternalHttpHttpTransport_initWithComSquareupOkhttpInternalHttpHttpEngine_withComSquareupOkhttpInternalHttpHttpConnection_(ComSquareupOkhttpInternalHttpHttpEngine *httpEngine, ComSquareupOkhttpInternalHttpHttpConnection *httpConnection);

J2OBJC_TYPE_LITERAL_HEADER(ComSquareupOkhttpInternalHttpHttpTransport)

#endif

#pragma pop_macro("ComSquareupOkhttpInternalHttpHttpTransport_INCLUDE_ALL")
