//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/squidb/squidb/src/com/yahoo/squidb/utility/SquidUtilities.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComYahooSquidbUtilitySquidUtilities_INCLUDE_ALL")
#ifdef ComYahooSquidbUtilitySquidUtilities_RESTRICT
#define ComYahooSquidbUtilitySquidUtilities_INCLUDE_ALL 0
#else
#define ComYahooSquidbUtilitySquidUtilities_INCLUDE_ALL 1
#endif
#undef ComYahooSquidbUtilitySquidUtilities_RESTRICT

#if !defined (ComYahooSquidbUtilitySquidUtilities_) && (ComYahooSquidbUtilitySquidUtilities_INCLUDE_ALL || defined(ComYahooSquidbUtilitySquidUtilities_INCLUDE))
#define ComYahooSquidbUtilitySquidUtilities_

@class ComYahooSquidbDataSquidDatabase;
@class IOSObjectArray;
@class JavaLangStringBuilder;
@protocol ComYahooSquidbDataICursor;
@protocol JavaUtilCollection;

@interface ComYahooSquidbUtilitySquidUtilities : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection
                   withNSObjectArray:(IOSObjectArray *)objects;

+ (void)copyDatabaseWithComYahooSquidbDataSquidDatabase:(ComYahooSquidbDataSquidDatabase *)database
                                           withNSString:(NSString *)toFolder OBJC_METHOD_FAMILY_NONE;

+ (void)dumpCurrentRowWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor;

+ (void)dumpCurrentRowWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                                            withInt:(jint)maxColumnWidth;

+ (void)dumpCurrentRowWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                                            withInt:(jint)maxColumnWidth
                          withJavaLangStringBuilder:(JavaLangStringBuilder *)builder;

+ (void)dumpCurrentRowWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                          withJavaLangStringBuilder:(JavaLangStringBuilder *)builder;

+ (void)dumpCursorWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor;

+ (void)dumpCursorWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                                        withInt:(jint)maxColumnWidth;

+ (void)dumpCursorWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                                        withInt:(jint)maxColumnWidth
                      withJavaLangStringBuilder:(JavaLangStringBuilder *)builder;

+ (void)dumpCursorWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                      withJavaLangStringBuilder:(JavaLangStringBuilder *)builder;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbUtilitySquidUtilities)

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCursorWithComYahooSquidbDataICursor_(id<ComYahooSquidbDataICursor> cursor);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCursorWithComYahooSquidbDataICursor_withInt_(id<ComYahooSquidbDataICursor> cursor, jint maxColumnWidth);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCursorWithComYahooSquidbDataICursor_withJavaLangStringBuilder_(id<ComYahooSquidbDataICursor> cursor, JavaLangStringBuilder *builder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCursorWithComYahooSquidbDataICursor_withInt_withJavaLangStringBuilder_(id<ComYahooSquidbDataICursor> cursor, jint maxColumnWidth, JavaLangStringBuilder *builder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCurrentRowWithComYahooSquidbDataICursor_(id<ComYahooSquidbDataICursor> cursor);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCurrentRowWithComYahooSquidbDataICursor_withInt_(id<ComYahooSquidbDataICursor> cursor, jint maxColumnWidth);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCurrentRowWithComYahooSquidbDataICursor_withJavaLangStringBuilder_(id<ComYahooSquidbDataICursor> cursor, JavaLangStringBuilder *builder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCurrentRowWithComYahooSquidbDataICursor_withInt_withJavaLangStringBuilder_(id<ComYahooSquidbDataICursor> cursor, jint maxColumnWidth, JavaLangStringBuilder *builder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_addAllWithJavaUtilCollection_withNSObjectArray_(id<JavaUtilCollection> collection, IOSObjectArray *objects);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_copyDatabaseWithComYahooSquidbDataSquidDatabase_withNSString_(ComYahooSquidbDataSquidDatabase *database, NSString *toFolder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_init(ComYahooSquidbUtilitySquidUtilities *self);

FOUNDATION_EXPORT ComYahooSquidbUtilitySquidUtilities *new_ComYahooSquidbUtilitySquidUtilities_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbUtilitySquidUtilities *create_ComYahooSquidbUtilitySquidUtilities_init();

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbUtilitySquidUtilities)

#endif

#pragma pop_macro("ComYahooSquidbUtilitySquidUtilities_INCLUDE_ALL")
