//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/RxJava/src/main/java/rx/Producer.java
//

#include "J2ObjC_source.h"
#include "rx/Producer.h"

@interface RxProducer : NSObject

@end

@implementation RxProducer

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "requestWithLong:", "request", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _RxProducer = { 2, "Producer", "rx", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_RxProducer;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RxProducer)
