//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/gson/gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/google/gson/internal/LinkedTreeMap.h"
#include "java/io/ObjectStreamException.h"
#include "java/lang/ClassCastException.h"
#include "java/lang/Comparable.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/Math.h"
#include "java/lang/NullPointerException.h"
#include "java/util/AbstractMap.h"
#include "java/util/AbstractSet.h"
#include "java/util/Comparator.h"
#include "java/util/ConcurrentModificationException.h"
#include "java/util/Iterator.h"
#include "java/util/LinkedHashMap.h"
#include "java/util/Map.h"
#include "java/util/NoSuchElementException.h"
#include "java/util/Set.h"

#pragma clang diagnostic ignored "-Wprotocol"

@interface DPGSInternalLinkedTreeMap () {
 @public
  DPGSInternalLinkedTreeMap_EntrySet *entrySet_;
  DPGSInternalLinkedTreeMap_KeySet *keySet_LinkedTreeMap_;
}

- (jboolean)equalWithId:(id)a
                 withId:(id)b;

- (void)replaceInParentWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)node
                       withDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)replacement;

- (void)rebalanceWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)unbalanced
                                        withBoolean:(jboolean)insert;

- (void)rotateLeftWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)root;

- (void)rotateRightWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)root;

- (id)writeReplace;

@end

J2OBJC_FIELD_SETTER(DPGSInternalLinkedTreeMap, entrySet_, DPGSInternalLinkedTreeMap_EntrySet *)
J2OBJC_FIELD_SETTER(DPGSInternalLinkedTreeMap, keySet_LinkedTreeMap_, DPGSInternalLinkedTreeMap_KeySet *)

inline id<JavaUtilComparator> DPGSInternalLinkedTreeMap_get_NATURAL_ORDER();
static id<JavaUtilComparator> DPGSInternalLinkedTreeMap_NATURAL_ORDER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(DPGSInternalLinkedTreeMap, NATURAL_ORDER, id<JavaUtilComparator>)

__attribute__((unused)) static jboolean DPGSInternalLinkedTreeMap_equalWithId_withId_(DPGSInternalLinkedTreeMap *self, id a, id b);

__attribute__((unused)) static void DPGSInternalLinkedTreeMap_replaceInParentWithDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(DPGSInternalLinkedTreeMap *self, DPGSInternalLinkedTreeMap_Node *node, DPGSInternalLinkedTreeMap_Node *replacement);

__attribute__((unused)) static void DPGSInternalLinkedTreeMap_rebalanceWithDPGSInternalLinkedTreeMap_Node_withBoolean_(DPGSInternalLinkedTreeMap *self, DPGSInternalLinkedTreeMap_Node *unbalanced, jboolean insert);

__attribute__((unused)) static void DPGSInternalLinkedTreeMap_rotateLeftWithDPGSInternalLinkedTreeMap_Node_(DPGSInternalLinkedTreeMap *self, DPGSInternalLinkedTreeMap_Node *root);

__attribute__((unused)) static void DPGSInternalLinkedTreeMap_rotateRightWithDPGSInternalLinkedTreeMap_Node_(DPGSInternalLinkedTreeMap *self, DPGSInternalLinkedTreeMap_Node *root);

@interface DPGSInternalLinkedTreeMap_LinkedTreeMapIterator : NSObject < JavaUtilIterator > {
 @public
  DPGSInternalLinkedTreeMap *this$0_;
  DPGSInternalLinkedTreeMap_Node *next_;
  DPGSInternalLinkedTreeMap_Node *lastReturned_;
  jint expectedModCount_;
}

- (instancetype)initWithDPGSInternalLinkedTreeMap:(DPGSInternalLinkedTreeMap *)outer$;

- (jboolean)hasNext;

- (DPGSInternalLinkedTreeMap_Node *)nextNode;

- (void)remove;

@end

J2OBJC_EMPTY_STATIC_INIT(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator)

J2OBJC_FIELD_SETTER(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator, this$0_, DPGSInternalLinkedTreeMap *)
J2OBJC_FIELD_SETTER(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator, next_, DPGSInternalLinkedTreeMap_Node *)
J2OBJC_FIELD_SETTER(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator, lastReturned_, DPGSInternalLinkedTreeMap_Node *)

__attribute__((unused)) static void DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_initWithDPGSInternalLinkedTreeMap_(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator *self, DPGSInternalLinkedTreeMap *outer$);

__attribute__((unused)) static DPGSInternalLinkedTreeMap_Node *DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator *self);

J2OBJC_TYPE_LITERAL_HEADER(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator)

@interface DPGSInternalLinkedTreeMap_EntrySet () {
 @public
  DPGSInternalLinkedTreeMap *this$0_;
}

@end

J2OBJC_FIELD_SETTER(DPGSInternalLinkedTreeMap_EntrySet, this$0_, DPGSInternalLinkedTreeMap *)

@interface DPGSInternalLinkedTreeMap_EntrySet_$1 : DPGSInternalLinkedTreeMap_LinkedTreeMapIterator

- (id<JavaUtilMap_Entry>)next;

- (instancetype)initWithDPGSInternalLinkedTreeMap_EntrySet:(DPGSInternalLinkedTreeMap_EntrySet *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(DPGSInternalLinkedTreeMap_EntrySet_$1)

__attribute__((unused)) static void DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(DPGSInternalLinkedTreeMap_EntrySet_$1 *self, DPGSInternalLinkedTreeMap_EntrySet *outer$);

__attribute__((unused)) static DPGSInternalLinkedTreeMap_EntrySet_$1 *new_DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(DPGSInternalLinkedTreeMap_EntrySet *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static DPGSInternalLinkedTreeMap_EntrySet_$1 *create_DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(DPGSInternalLinkedTreeMap_EntrySet *outer$);

J2OBJC_TYPE_LITERAL_HEADER(DPGSInternalLinkedTreeMap_EntrySet_$1)

@interface DPGSInternalLinkedTreeMap_KeySet () {
 @public
  DPGSInternalLinkedTreeMap *this$0_;
}

@end

J2OBJC_FIELD_SETTER(DPGSInternalLinkedTreeMap_KeySet, this$0_, DPGSInternalLinkedTreeMap *)

@interface DPGSInternalLinkedTreeMap_KeySet_$1 : DPGSInternalLinkedTreeMap_LinkedTreeMapIterator

- (id)next;

- (instancetype)initWithDPGSInternalLinkedTreeMap_KeySet:(DPGSInternalLinkedTreeMap_KeySet *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(DPGSInternalLinkedTreeMap_KeySet_$1)

__attribute__((unused)) static void DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(DPGSInternalLinkedTreeMap_KeySet_$1 *self, DPGSInternalLinkedTreeMap_KeySet *outer$);

__attribute__((unused)) static DPGSInternalLinkedTreeMap_KeySet_$1 *new_DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(DPGSInternalLinkedTreeMap_KeySet *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static DPGSInternalLinkedTreeMap_KeySet_$1 *create_DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(DPGSInternalLinkedTreeMap_KeySet *outer$);

J2OBJC_TYPE_LITERAL_HEADER(DPGSInternalLinkedTreeMap_KeySet_$1)

@interface DPGSInternalLinkedTreeMap_$1 : NSObject < JavaUtilComparator >

- (jint)compareWithId:(id<JavaLangComparable>)a
               withId:(id<JavaLangComparable>)b;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(DPGSInternalLinkedTreeMap_$1)

__attribute__((unused)) static void DPGSInternalLinkedTreeMap_$1_init(DPGSInternalLinkedTreeMap_$1 *self);

__attribute__((unused)) static DPGSInternalLinkedTreeMap_$1 *new_DPGSInternalLinkedTreeMap_$1_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static DPGSInternalLinkedTreeMap_$1 *create_DPGSInternalLinkedTreeMap_$1_init();

J2OBJC_TYPE_LITERAL_HEADER(DPGSInternalLinkedTreeMap_$1)

J2OBJC_INITIALIZED_DEFN(DPGSInternalLinkedTreeMap)

@implementation DPGSInternalLinkedTreeMap

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  DPGSInternalLinkedTreeMap_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)comparator {
  DPGSInternalLinkedTreeMap_initWithJavaUtilComparator_(self, comparator);
  return self;
}

- (jint)size {
  return size_;
}

- (id)getWithId:(id)key {
  DPGSInternalLinkedTreeMap_Node *node = [self findByObjectWithId:key];
  return node != nil ? node->value_ : nil;
}

- (jboolean)containsKeyWithId:(id)key {
  return [self findByObjectWithId:key] != nil;
}

- (id)putWithId:(id)key
         withId:(id)value {
  if (key == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"key == null");
  }
  DPGSInternalLinkedTreeMap_Node *created = [self findWithId:key withBoolean:true];
  id result = ((id) ((DPGSInternalLinkedTreeMap_Node *) nil_chk(created))->value_);
  created->value_ = value;
  return result;
}

- (void)clear {
  root_ = nil;
  size_ = 0;
  modCount_++;
  DPGSInternalLinkedTreeMap_Node *header = self->header_;
  ((DPGSInternalLinkedTreeMap_Node *) nil_chk(header))->next_ = header->prev_ = header;
}

- (id)removeWithId:(id)key {
  DPGSInternalLinkedTreeMap_Node *node = [self removeInternalByKeyWithId:key];
  return node != nil ? node->value_ : nil;
}

- (DPGSInternalLinkedTreeMap_Node *)findWithId:(id)key
                                   withBoolean:(jboolean)create {
  id<JavaUtilComparator> comparator = self->comparator_;
  DPGSInternalLinkedTreeMap_Node *nearest = root_;
  jint comparison = 0;
  if (nearest != nil) {
    id<JavaLangComparable> comparableKey = (comparator == (id) DPGSInternalLinkedTreeMap_NATURAL_ORDER) ? (id<JavaLangComparable>) cast_check(key, JavaLangComparable_class_()) : nil;
    while (true) {
      comparison = (comparableKey != nil) ? [comparableKey compareToWithId:nearest->key_] : [((id<JavaUtilComparator>) nil_chk(comparator)) compareWithId:key withId:((id) nearest->key_)];
      if (comparison == 0) {
        return nearest;
      }
      DPGSInternalLinkedTreeMap_Node *child = (comparison < 0) ? nearest->left_ : nearest->right_;
      if (child == nil) {
        break;
      }
      nearest = child;
    }
  }
  if (!create) {
    return nil;
  }
  DPGSInternalLinkedTreeMap_Node *header = self->header_;
  DPGSInternalLinkedTreeMap_Node *created;
  if (nearest == nil) {
    if (comparator == (id) DPGSInternalLinkedTreeMap_NATURAL_ORDER && !([JavaLangComparable_class_() isInstance:key])) {
      @throw new_JavaLangClassCastException_initWithNSString_(JreStrcat("$$", [[((id) nil_chk(key)) getClass] getName], @" is not Comparable"));
    }
    created = new_DPGSInternalLinkedTreeMap_Node_initWithDPGSInternalLinkedTreeMap_Node_withId_withDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(nearest, key, header, ((DPGSInternalLinkedTreeMap_Node *) nil_chk(header))->prev_);
    root_ = created;
  }
  else {
    created = new_DPGSInternalLinkedTreeMap_Node_initWithDPGSInternalLinkedTreeMap_Node_withId_withDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(nearest, key, header, ((DPGSInternalLinkedTreeMap_Node *) nil_chk(header))->prev_);
    if (comparison < 0) {
      nearest->left_ = created;
    }
    else {
      nearest->right_ = created;
    }
    DPGSInternalLinkedTreeMap_rebalanceWithDPGSInternalLinkedTreeMap_Node_withBoolean_(self, nearest, true);
  }
  size_++;
  modCount_++;
  return created;
}

- (DPGSInternalLinkedTreeMap_Node *)findByObjectWithId:(id)key {
  @try {
    return key != nil ? [self findWithId:key withBoolean:false] : nil;
  }
  @catch (JavaLangClassCastException *e) {
    return nil;
  }
}

- (DPGSInternalLinkedTreeMap_Node *)findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)entry_ {
  DPGSInternalLinkedTreeMap_Node *mine = [self findByObjectWithId:[((id<JavaUtilMap_Entry>) nil_chk(entry_)) getKey]];
  jboolean valuesEqual = mine != nil && DPGSInternalLinkedTreeMap_equalWithId_withId_(self, mine->value_, [entry_ getValue]);
  return valuesEqual ? mine : nil;
}

- (jboolean)equalWithId:(id)a
                 withId:(id)b {
  return DPGSInternalLinkedTreeMap_equalWithId_withId_(self, a, b);
}

- (void)removeInternalWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)node
                                             withBoolean:(jboolean)unlink {
  if (unlink) {
    ((DPGSInternalLinkedTreeMap_Node *) nil_chk(((DPGSInternalLinkedTreeMap_Node *) nil_chk(node))->prev_))->next_ = node->next_;
    ((DPGSInternalLinkedTreeMap_Node *) nil_chk(node->next_))->prev_ = node->prev_;
  }
  DPGSInternalLinkedTreeMap_Node *left = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(node))->left_;
  DPGSInternalLinkedTreeMap_Node *right = node->right_;
  DPGSInternalLinkedTreeMap_Node *originalParent = node->parent_;
  if (left != nil && right != nil) {
    DPGSInternalLinkedTreeMap_Node *adjacent = (left->height_ > right->height_) ? [left last] : [right first];
    [self removeInternalWithDPGSInternalLinkedTreeMap_Node:adjacent withBoolean:false];
    jint leftHeight = 0;
    left = node->left_;
    if (left != nil) {
      leftHeight = left->height_;
      adjacent->left_ = left;
      left->parent_ = adjacent;
      node->left_ = nil;
    }
    jint rightHeight = 0;
    right = node->right_;
    if (right != nil) {
      rightHeight = right->height_;
      adjacent->right_ = right;
      right->parent_ = adjacent;
      node->right_ = nil;
    }
    adjacent->height_ = JavaLangMath_maxWithInt_withInt_(leftHeight, rightHeight) + 1;
    DPGSInternalLinkedTreeMap_replaceInParentWithDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(self, node, adjacent);
    return;
  }
  else if (left != nil) {
    DPGSInternalLinkedTreeMap_replaceInParentWithDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(self, node, left);
    node->left_ = nil;
  }
  else if (right != nil) {
    DPGSInternalLinkedTreeMap_replaceInParentWithDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(self, node, right);
    node->right_ = nil;
  }
  else {
    DPGSInternalLinkedTreeMap_replaceInParentWithDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(self, node, nil);
  }
  DPGSInternalLinkedTreeMap_rebalanceWithDPGSInternalLinkedTreeMap_Node_withBoolean_(self, originalParent, false);
  size_--;
  modCount_++;
}

- (DPGSInternalLinkedTreeMap_Node *)removeInternalByKeyWithId:(id)key {
  DPGSInternalLinkedTreeMap_Node *node = [self findByObjectWithId:key];
  if (node != nil) {
    [self removeInternalWithDPGSInternalLinkedTreeMap_Node:node withBoolean:true];
  }
  return node;
}

- (void)replaceInParentWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)node
                       withDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)replacement {
  DPGSInternalLinkedTreeMap_replaceInParentWithDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(self, node, replacement);
}

- (void)rebalanceWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)unbalanced
                                        withBoolean:(jboolean)insert {
  DPGSInternalLinkedTreeMap_rebalanceWithDPGSInternalLinkedTreeMap_Node_withBoolean_(self, unbalanced, insert);
}

- (void)rotateLeftWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)root {
  DPGSInternalLinkedTreeMap_rotateLeftWithDPGSInternalLinkedTreeMap_Node_(self, root);
}

- (void)rotateRightWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)root {
  DPGSInternalLinkedTreeMap_rotateRightWithDPGSInternalLinkedTreeMap_Node_(self, root);
}

- (id<JavaUtilSet>)entrySet {
  DPGSInternalLinkedTreeMap_EntrySet *result = entrySet_;
  return result != nil ? result : (entrySet_ = new_DPGSInternalLinkedTreeMap_EntrySet_initWithDPGSInternalLinkedTreeMap_(self));
}

- (id<JavaUtilSet>)keySet {
  DPGSInternalLinkedTreeMap_KeySet *result = keySet_LinkedTreeMap_;
  return result != nil ? result : (keySet_LinkedTreeMap_ = new_DPGSInternalLinkedTreeMap_KeySet_initWithDPGSInternalLinkedTreeMap_(self));
}

- (id)writeReplace {
  return new_JavaUtilLinkedHashMap_initWithJavaUtilMap_(self);
}

+ (void)initialize {
  if (self == [DPGSInternalLinkedTreeMap class]) {
    DPGSInternalLinkedTreeMap_NATURAL_ORDER = new_DPGSInternalLinkedTreeMap_$1_init();
    J2OBJC_SET_INITIALIZED(DPGSInternalLinkedTreeMap)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "LinkedTreeMap", NULL, 0x1, NULL, NULL },
    { "initWithJavaUtilComparator:", "LinkedTreeMap", NULL, 0x1, NULL, "(Ljava/util/Comparator<-TK;>;)V" },
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "getWithId:", "get", "TV;", 0x1, NULL, "(Ljava/lang/Object;)TV;" },
    { "containsKeyWithId:", "containsKey", "Z", 0x1, NULL, NULL },
    { "putWithId:withId:", "put", "TV;", 0x1, NULL, "(TK;TV;)TV;" },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "removeWithId:", "remove", "TV;", 0x1, NULL, "(Ljava/lang/Object;)TV;" },
    { "findWithId:withBoolean:", "find", "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x0, NULL, "(TK;Z)Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;" },
    { "findByObjectWithId:", "findByObject", "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x0, NULL, "(Ljava/lang/Object;)Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;" },
    { "findByEntryWithJavaUtilMap_Entry:", "findByEntry", "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x0, NULL, "(Ljava/util/Map$Entry<**>;)Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;" },
    { "equalWithId:withId:", "equal", "Z", 0x2, NULL, NULL },
    { "removeInternalWithDPGSInternalLinkedTreeMap_Node:withBoolean:", "removeInternal", "V", 0x0, NULL, "(Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;Z)V" },
    { "removeInternalByKeyWithId:", "removeInternalByKey", "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x0, NULL, "(Ljava/lang/Object;)Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;" },
    { "replaceInParentWithDPGSInternalLinkedTreeMap_Node:withDPGSInternalLinkedTreeMap_Node:", "replaceInParent", "V", 0x2, NULL, "(Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;)V" },
    { "rebalanceWithDPGSInternalLinkedTreeMap_Node:withBoolean:", "rebalance", "V", 0x2, NULL, "(Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;Z)V" },
    { "rotateLeftWithDPGSInternalLinkedTreeMap_Node:", "rotateLeft", "V", 0x2, NULL, "(Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;)V" },
    { "rotateRightWithDPGSInternalLinkedTreeMap_Node:", "rotateRight", "V", 0x2, NULL, "(Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;)V" },
    { "entrySet", NULL, "Ljava.util.Set;", 0x1, NULL, "()Ljava/util/Set<Ljava/util/Map$Entry<TK;TV;>;>;" },
    { "keySet", NULL, "Ljava.util.Set;", 0x1, NULL, "()Ljava/util/Set<TK;>;" },
    { "writeReplace", NULL, "Ljava.lang.Object;", 0x2, "Ljava.io.ObjectStreamException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "NATURAL_ORDER", "NATURAL_ORDER", 0x1a, "Ljava.util.Comparator;", &DPGSInternalLinkedTreeMap_NATURAL_ORDER, "Ljava/util/Comparator<Ljava/lang/Comparable;>;", .constantValue.asLong = 0 },
    { "comparator_", NULL, 0x0, "Ljava.util.Comparator;", NULL, "Ljava/util/Comparator<-TK;>;", .constantValue.asLong = 0 },
    { "root_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "size_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "modCount_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "header_", NULL, 0x10, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "entrySet_", NULL, 0x2, "Lcom.google.gson.internal.LinkedTreeMap$EntrySet;", NULL, NULL, .constantValue.asLong = 0 },
    { "keySet_LinkedTreeMap_", "keySet", 0x2, "Lcom.google.gson.internal.LinkedTreeMap$KeySet;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"TK;", "TV;"};
  static const char *inner_classes[] = {"Lcom.google.gson.internal.LinkedTreeMap$Node;", "Lcom.google.gson.internal.LinkedTreeMap$LinkedTreeMapIterator;", "Lcom.google.gson.internal.LinkedTreeMap$EntrySet;", "Lcom.google.gson.internal.LinkedTreeMap$KeySet;"};
  static const J2ObjcClassInfo _DPGSInternalLinkedTreeMap = { 2, "LinkedTreeMap", "com.google.gson.internal", NULL, 0x11, 21, methods, 8, fields, 2, superclass_type_args, 4, inner_classes, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/util/AbstractMap<TK;TV;>;Ljava/io/Serializable;" };
  return &_DPGSInternalLinkedTreeMap;
}

@end

void DPGSInternalLinkedTreeMap_init(DPGSInternalLinkedTreeMap *self) {
  DPGSInternalLinkedTreeMap_initWithJavaUtilComparator_(self, DPGSInternalLinkedTreeMap_NATURAL_ORDER);
}

DPGSInternalLinkedTreeMap *new_DPGSInternalLinkedTreeMap_init() {
  DPGSInternalLinkedTreeMap *self = [DPGSInternalLinkedTreeMap alloc];
  DPGSInternalLinkedTreeMap_init(self);
  return self;
}

DPGSInternalLinkedTreeMap *create_DPGSInternalLinkedTreeMap_init() {
  return new_DPGSInternalLinkedTreeMap_init();
}

void DPGSInternalLinkedTreeMap_initWithJavaUtilComparator_(DPGSInternalLinkedTreeMap *self, id<JavaUtilComparator> comparator) {
  JavaUtilAbstractMap_init(self);
  self->size_ = 0;
  self->modCount_ = 0;
  self->header_ = new_DPGSInternalLinkedTreeMap_Node_init();
  self->comparator_ = comparator != nil ? ((id) comparator) : ((id) DPGSInternalLinkedTreeMap_NATURAL_ORDER);
}

DPGSInternalLinkedTreeMap *new_DPGSInternalLinkedTreeMap_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) {
  DPGSInternalLinkedTreeMap *self = [DPGSInternalLinkedTreeMap alloc];
  DPGSInternalLinkedTreeMap_initWithJavaUtilComparator_(self, comparator);
  return self;
}

DPGSInternalLinkedTreeMap *create_DPGSInternalLinkedTreeMap_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) {
  return new_DPGSInternalLinkedTreeMap_initWithJavaUtilComparator_(comparator);
}

jboolean DPGSInternalLinkedTreeMap_equalWithId_withId_(DPGSInternalLinkedTreeMap *self, id a, id b) {
  return a == b || (a != nil && [a isEqual:b]);
}

void DPGSInternalLinkedTreeMap_replaceInParentWithDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(DPGSInternalLinkedTreeMap *self, DPGSInternalLinkedTreeMap_Node *node, DPGSInternalLinkedTreeMap_Node *replacement) {
  DPGSInternalLinkedTreeMap_Node *parent = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(node))->parent_;
  node->parent_ = nil;
  if (replacement != nil) {
    replacement->parent_ = parent;
  }
  if (parent != nil) {
    if (parent->left_ == node) {
      parent->left_ = replacement;
    }
    else {
      JreAssert((parent->right_ == node), (@"com/google/gson/internal/LinkedTreeMap.java:295 condition failed: assert (parent.right == node);"));
      parent->right_ = replacement;
    }
  }
  else {
    self->root_ = replacement;
  }
}

void DPGSInternalLinkedTreeMap_rebalanceWithDPGSInternalLinkedTreeMap_Node_withBoolean_(DPGSInternalLinkedTreeMap *self, DPGSInternalLinkedTreeMap_Node *unbalanced, jboolean insert) {
  for (DPGSInternalLinkedTreeMap_Node *node = unbalanced; node != nil; node = node->parent_) {
    DPGSInternalLinkedTreeMap_Node *left = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(node))->left_;
    DPGSInternalLinkedTreeMap_Node *right = node->right_;
    jint leftHeight = left != nil ? left->height_ : 0;
    jint rightHeight = right != nil ? right->height_ : 0;
    jint delta = leftHeight - rightHeight;
    if (delta == -2) {
      DPGSInternalLinkedTreeMap_Node *rightLeft = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(right))->left_;
      DPGSInternalLinkedTreeMap_Node *rightRight = right->right_;
      jint rightRightHeight = rightRight != nil ? rightRight->height_ : 0;
      jint rightLeftHeight = rightLeft != nil ? rightLeft->height_ : 0;
      jint rightDelta = rightLeftHeight - rightRightHeight;
      if (rightDelta == -1 || (rightDelta == 0 && !insert)) {
        DPGSInternalLinkedTreeMap_rotateLeftWithDPGSInternalLinkedTreeMap_Node_(self, node);
      }
      else {
        JreAssert((rightDelta == 1), (@"com/google/gson/internal/LinkedTreeMap.java:328 condition failed: assert (rightDelta == 1);"));
        DPGSInternalLinkedTreeMap_rotateRightWithDPGSInternalLinkedTreeMap_Node_(self, right);
        DPGSInternalLinkedTreeMap_rotateLeftWithDPGSInternalLinkedTreeMap_Node_(self, node);
      }
      if (insert) {
        break;
      }
    }
    else if (delta == 2) {
      DPGSInternalLinkedTreeMap_Node *leftLeft = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(left))->left_;
      DPGSInternalLinkedTreeMap_Node *leftRight = left->right_;
      jint leftRightHeight = leftRight != nil ? leftRight->height_ : 0;
      jint leftLeftHeight = leftLeft != nil ? leftLeft->height_ : 0;
      jint leftDelta = leftLeftHeight - leftRightHeight;
      if (leftDelta == 1 || (leftDelta == 0 && !insert)) {
        DPGSInternalLinkedTreeMap_rotateRightWithDPGSInternalLinkedTreeMap_Node_(self, node);
      }
      else {
        JreAssert((leftDelta == -1), (@"com/google/gson/internal/LinkedTreeMap.java:346 condition failed: assert (leftDelta == -1);"));
        DPGSInternalLinkedTreeMap_rotateLeftWithDPGSInternalLinkedTreeMap_Node_(self, left);
        DPGSInternalLinkedTreeMap_rotateRightWithDPGSInternalLinkedTreeMap_Node_(self, node);
      }
      if (insert) {
        break;
      }
    }
    else if (delta == 0) {
      node->height_ = leftHeight + 1;
      if (insert) {
        break;
      }
    }
    else {
      JreAssert(((delta == -1 || delta == 1)), (@"com/google/gson/internal/LinkedTreeMap.java:361 condition failed: assert (delta == -1 || delta == 1);"));
      node->height_ = JavaLangMath_maxWithInt_withInt_(leftHeight, rightHeight) + 1;
      if (!insert) {
        break;
      }
    }
  }
}

void DPGSInternalLinkedTreeMap_rotateLeftWithDPGSInternalLinkedTreeMap_Node_(DPGSInternalLinkedTreeMap *self, DPGSInternalLinkedTreeMap_Node *root) {
  DPGSInternalLinkedTreeMap_Node *left = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(root))->left_;
  DPGSInternalLinkedTreeMap_Node *pivot = root->right_;
  DPGSInternalLinkedTreeMap_Node *pivotLeft = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(pivot))->left_;
  DPGSInternalLinkedTreeMap_Node *pivotRight = pivot->right_;
  root->right_ = pivotLeft;
  if (pivotLeft != nil) {
    pivotLeft->parent_ = root;
  }
  DPGSInternalLinkedTreeMap_replaceInParentWithDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(self, root, pivot);
  pivot->left_ = root;
  root->parent_ = pivot;
  root->height_ = JavaLangMath_maxWithInt_withInt_(left != nil ? left->height_ : 0, pivotLeft != nil ? pivotLeft->height_ : 0) + 1;
  pivot->height_ = JavaLangMath_maxWithInt_withInt_(root->height_, pivotRight != nil ? pivotRight->height_ : 0) + 1;
}

void DPGSInternalLinkedTreeMap_rotateRightWithDPGSInternalLinkedTreeMap_Node_(DPGSInternalLinkedTreeMap *self, DPGSInternalLinkedTreeMap_Node *root) {
  DPGSInternalLinkedTreeMap_Node *pivot = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(root))->left_;
  DPGSInternalLinkedTreeMap_Node *right = root->right_;
  DPGSInternalLinkedTreeMap_Node *pivotLeft = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(pivot))->left_;
  DPGSInternalLinkedTreeMap_Node *pivotRight = pivot->right_;
  root->left_ = pivotRight;
  if (pivotRight != nil) {
    pivotRight->parent_ = root;
  }
  DPGSInternalLinkedTreeMap_replaceInParentWithDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(self, root, pivot);
  pivot->right_ = root;
  root->parent_ = pivot;
  root->height_ = JavaLangMath_maxWithInt_withInt_(right != nil ? right->height_ : 0, pivotRight != nil ? pivotRight->height_ : 0) + 1;
  pivot->height_ = JavaLangMath_maxWithInt_withInt_(root->height_, pivotLeft != nil ? pivotLeft->height_ : 0) + 1;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSInternalLinkedTreeMap)

@implementation DPGSInternalLinkedTreeMap_Node

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  DPGSInternalLinkedTreeMap_Node_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)parent
                                                withId:(id)key
                    withDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)next
                    withDPGSInternalLinkedTreeMap_Node:(DPGSInternalLinkedTreeMap_Node *)prev {
  DPGSInternalLinkedTreeMap_Node_initWithDPGSInternalLinkedTreeMap_Node_withId_withDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(self, parent, key, next, prev);
  return self;
}

- (id)getKey {
  return key_;
}

- (id)getValue {
  return value_;
}

- (id)setValueWithId:(id)value {
  id oldValue = self->value_;
  self->value_ = value;
  return oldValue;
}

- (jboolean)isEqual:(id)o {
  if ([JavaUtilMap_Entry_class_() isInstance:o]) {
    id<JavaUtilMap_Entry> other = (id<JavaUtilMap_Entry>) cast_check(o, JavaUtilMap_Entry_class_());
    return (key_ == nil ? [((id<JavaUtilMap_Entry>) nil_chk(other)) getKey] == nil : [key_ isEqual:[((id<JavaUtilMap_Entry>) nil_chk(other)) getKey]]) && (value_ == nil ? [other getValue] == nil : [value_ isEqual:[other getValue]]);
  }
  return false;
}

- (NSUInteger)hash {
  return (key_ == nil ? 0 : ((jint) [key_ hash])) ^ (value_ == nil ? 0 : ((jint) [value_ hash]));
}

- (NSString *)description {
  return JreStrcat("@C@", key_, '=', value_);
}

- (DPGSInternalLinkedTreeMap_Node *)first {
  DPGSInternalLinkedTreeMap_Node *node = self;
  DPGSInternalLinkedTreeMap_Node *child = node->left_;
  while (child != nil) {
    node = child;
    child = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(node))->left_;
  }
  return node;
}

- (DPGSInternalLinkedTreeMap_Node *)last {
  DPGSInternalLinkedTreeMap_Node *node = self;
  DPGSInternalLinkedTreeMap_Node *child = node->right_;
  while (child != nil) {
    node = child;
    child = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(node))->right_;
  }
  return node;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Node", NULL, 0x0, NULL, NULL },
    { "initWithDPGSInternalLinkedTreeMap_Node:withId:withDPGSInternalLinkedTreeMap_Node:withDPGSInternalLinkedTreeMap_Node:", "Node", NULL, 0x0, NULL, "(Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;TK;Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;)V" },
    { "getKey", NULL, "TK;", 0x1, NULL, "()TK;" },
    { "getValue", NULL, "TV;", 0x1, NULL, "()TV;" },
    { "setValueWithId:", "setValue", "TV;", 0x1, NULL, "(TV;)TV;" },
    { "isEqual:", "equals", "Z", 0x1, NULL, NULL },
    { "hash", "hashCode", "I", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "first", NULL, "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x1, NULL, "()Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;" },
    { "last", NULL, "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x1, NULL, "()Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "parent_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "left_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "right_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "next_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "prev_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "key_", NULL, 0x10, "TK;", NULL, "TK;", .constantValue.asLong = 0 },
    { "value_", NULL, 0x0, "TV;", NULL, "TV;", .constantValue.asLong = 0 },
    { "height_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _DPGSInternalLinkedTreeMap_Node = { 2, "Node", "com.google.gson.internal", "LinkedTreeMap", 0x18, 10, methods, 8, fields, 0, NULL, 0, NULL, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/Map$Entry<TK;TV;>;" };
  return &_DPGSInternalLinkedTreeMap_Node;
}

@end

void DPGSInternalLinkedTreeMap_Node_init(DPGSInternalLinkedTreeMap_Node *self) {
  NSObject_init(self);
  self->key_ = nil;
  self->next_ = self->prev_ = self;
}

DPGSInternalLinkedTreeMap_Node *new_DPGSInternalLinkedTreeMap_Node_init() {
  DPGSInternalLinkedTreeMap_Node *self = [DPGSInternalLinkedTreeMap_Node alloc];
  DPGSInternalLinkedTreeMap_Node_init(self);
  return self;
}

DPGSInternalLinkedTreeMap_Node *create_DPGSInternalLinkedTreeMap_Node_init() {
  return new_DPGSInternalLinkedTreeMap_Node_init();
}

void DPGSInternalLinkedTreeMap_Node_initWithDPGSInternalLinkedTreeMap_Node_withId_withDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(DPGSInternalLinkedTreeMap_Node *self, DPGSInternalLinkedTreeMap_Node *parent, id key, DPGSInternalLinkedTreeMap_Node *next, DPGSInternalLinkedTreeMap_Node *prev) {
  NSObject_init(self);
  self->parent_ = parent;
  self->key_ = key;
  self->height_ = 1;
  self->next_ = next;
  self->prev_ = prev;
  ((DPGSInternalLinkedTreeMap_Node *) nil_chk(prev))->next_ = self;
  ((DPGSInternalLinkedTreeMap_Node *) nil_chk(next))->prev_ = self;
}

DPGSInternalLinkedTreeMap_Node *new_DPGSInternalLinkedTreeMap_Node_initWithDPGSInternalLinkedTreeMap_Node_withId_withDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(DPGSInternalLinkedTreeMap_Node *parent, id key, DPGSInternalLinkedTreeMap_Node *next, DPGSInternalLinkedTreeMap_Node *prev) {
  DPGSInternalLinkedTreeMap_Node *self = [DPGSInternalLinkedTreeMap_Node alloc];
  DPGSInternalLinkedTreeMap_Node_initWithDPGSInternalLinkedTreeMap_Node_withId_withDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(self, parent, key, next, prev);
  return self;
}

DPGSInternalLinkedTreeMap_Node *create_DPGSInternalLinkedTreeMap_Node_initWithDPGSInternalLinkedTreeMap_Node_withId_withDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(DPGSInternalLinkedTreeMap_Node *parent, id key, DPGSInternalLinkedTreeMap_Node *next, DPGSInternalLinkedTreeMap_Node *prev) {
  return new_DPGSInternalLinkedTreeMap_Node_initWithDPGSInternalLinkedTreeMap_Node_withId_withDPGSInternalLinkedTreeMap_Node_withDPGSInternalLinkedTreeMap_Node_(parent, key, next, prev);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSInternalLinkedTreeMap_Node)

@implementation DPGSInternalLinkedTreeMap_LinkedTreeMapIterator

- (instancetype)initWithDPGSInternalLinkedTreeMap:(DPGSInternalLinkedTreeMap *)outer$ {
  DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_initWithDPGSInternalLinkedTreeMap_(self, outer$);
  return self;
}

- (jboolean)hasNext {
  return next_ != this$0_->header_;
}

- (DPGSInternalLinkedTreeMap_Node *)nextNode {
  return DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(self);
}

- (void)remove {
  if (lastReturned_ == nil) {
    @throw new_JavaLangIllegalStateException_init();
  }
  [this$0_ removeInternalWithDPGSInternalLinkedTreeMap_Node:lastReturned_ withBoolean:true];
  lastReturned_ = nil;
  expectedModCount_ = this$0_->modCount_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithDPGSInternalLinkedTreeMap:", "LinkedTreeMapIterator", NULL, 0x0, NULL, NULL },
    { "hasNext", NULL, "Z", 0x11, NULL, NULL },
    { "nextNode", NULL, "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x10, NULL, "()Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;" },
    { "remove", NULL, "V", 0x11, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.LinkedTreeMap;", NULL, NULL, .constantValue.asLong = 0 },
    { "next_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "lastReturned_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "expectedModCount_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _DPGSInternalLinkedTreeMap_LinkedTreeMapIterator = { 2, "LinkedTreeMapIterator", "com.google.gson.internal", "LinkedTreeMap", 0x402, 4, methods, 4, fields, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/Iterator<TT;>;" };
  return &_DPGSInternalLinkedTreeMap_LinkedTreeMapIterator;
}

@end

void DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_initWithDPGSInternalLinkedTreeMap_(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator *self, DPGSInternalLinkedTreeMap *outer$) {
  self->this$0_ = outer$;
  NSObject_init(self);
  self->next_ = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(outer$->header_))->next_;
  self->lastReturned_ = nil;
  self->expectedModCount_ = outer$->modCount_;
}

DPGSInternalLinkedTreeMap_Node *DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator *self) {
  DPGSInternalLinkedTreeMap_Node *e = self->next_;
  if (e == self->this$0_->header_) {
    @throw new_JavaUtilNoSuchElementException_init();
  }
  if (self->this$0_->modCount_ != self->expectedModCount_) {
    @throw new_JavaUtilConcurrentModificationException_init();
  }
  self->next_ = ((DPGSInternalLinkedTreeMap_Node *) nil_chk(e))->next_;
  return self->lastReturned_ = e;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator)

@implementation DPGSInternalLinkedTreeMap_EntrySet

- (jint)size {
  return this$0_->size_;
}

- (id<JavaUtilIterator>)iterator {
  return new_DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(self);
}

- (jboolean)containsWithId:(id)o {
  return [JavaUtilMap_Entry_class_() isInstance:o] && [this$0_ findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>) cast_check(o, JavaUtilMap_Entry_class_())] != nil;
}

- (jboolean)removeWithId:(id)o {
  if (!([JavaUtilMap_Entry_class_() isInstance:o])) {
    return false;
  }
  DPGSInternalLinkedTreeMap_Node *node = [this$0_ findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>) cast_check(o, JavaUtilMap_Entry_class_())];
  if (node == nil) {
    return false;
  }
  [this$0_ removeInternalWithDPGSInternalLinkedTreeMap_Node:node withBoolean:true];
  return true;
}

- (void)clear {
  [this$0_ clear];
}

- (instancetype)initWithDPGSInternalLinkedTreeMap:(DPGSInternalLinkedTreeMap *)outer$ {
  DPGSInternalLinkedTreeMap_EntrySet_initWithDPGSInternalLinkedTreeMap_(self, outer$);
  return self;
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "iterator", NULL, "Ljava.util.Iterator;", 0x1, NULL, "()Ljava/util/Iterator<Ljava/util/Map$Entry<TK;TV;>;>;" },
    { "containsWithId:", "contains", "Z", 0x1, NULL, NULL },
    { "removeWithId:", "remove", "Z", 0x1, NULL, NULL },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "initWithDPGSInternalLinkedTreeMap:", "init", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.LinkedTreeMap;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Ljava.util.Map$Entry;"};
  static const J2ObjcClassInfo _DPGSInternalLinkedTreeMap_EntrySet = { 2, "EntrySet", "com.google.gson.internal", "LinkedTreeMap", 0x0, 6, methods, 1, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/util/AbstractSet<Ljava/util/Map$Entry<TK;TV;>;>;" };
  return &_DPGSInternalLinkedTreeMap_EntrySet;
}

@end

void DPGSInternalLinkedTreeMap_EntrySet_initWithDPGSInternalLinkedTreeMap_(DPGSInternalLinkedTreeMap_EntrySet *self, DPGSInternalLinkedTreeMap *outer$) {
  self->this$0_ = outer$;
  JavaUtilAbstractSet_init(self);
}

DPGSInternalLinkedTreeMap_EntrySet *new_DPGSInternalLinkedTreeMap_EntrySet_initWithDPGSInternalLinkedTreeMap_(DPGSInternalLinkedTreeMap *outer$) {
  DPGSInternalLinkedTreeMap_EntrySet *self = [DPGSInternalLinkedTreeMap_EntrySet alloc];
  DPGSInternalLinkedTreeMap_EntrySet_initWithDPGSInternalLinkedTreeMap_(self, outer$);
  return self;
}

DPGSInternalLinkedTreeMap_EntrySet *create_DPGSInternalLinkedTreeMap_EntrySet_initWithDPGSInternalLinkedTreeMap_(DPGSInternalLinkedTreeMap *outer$) {
  return new_DPGSInternalLinkedTreeMap_EntrySet_initWithDPGSInternalLinkedTreeMap_(outer$);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSInternalLinkedTreeMap_EntrySet)

@implementation DPGSInternalLinkedTreeMap_EntrySet_$1

- (id<JavaUtilMap_Entry>)next {
  return DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(self);
}

- (instancetype)initWithDPGSInternalLinkedTreeMap_EntrySet:(DPGSInternalLinkedTreeMap_EntrySet *)outer$ {
  DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "Ljava.util.Map$Entry;", 0x1, NULL, "()Ljava/util/Map$Entry<TK;TV;>;" },
    { "initWithDPGSInternalLinkedTreeMap_EntrySet:", "", NULL, 0x0, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.util.Map$Entry;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "DPGSInternalLinkedTreeMap_EntrySet", "iterator" };
  static const J2ObjcClassInfo _DPGSInternalLinkedTreeMap_EntrySet_$1 = { 2, "", "com.google.gson.internal", "LinkedTreeMap$EntrySet", 0x8008, 2, methods, 0, NULL, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/internal/LinkedTreeMap$LinkedTreeMapIterator<Ljava/util/Map$Entry<TK;TV;>;>;" };
  return &_DPGSInternalLinkedTreeMap_EntrySet_$1;
}

@end

void DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(DPGSInternalLinkedTreeMap_EntrySet_$1 *self, DPGSInternalLinkedTreeMap_EntrySet *outer$) {
  DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_initWithDPGSInternalLinkedTreeMap_(self, outer$->this$0_);
}

DPGSInternalLinkedTreeMap_EntrySet_$1 *new_DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(DPGSInternalLinkedTreeMap_EntrySet *outer$) {
  DPGSInternalLinkedTreeMap_EntrySet_$1 *self = [DPGSInternalLinkedTreeMap_EntrySet_$1 alloc];
  DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(self, outer$);
  return self;
}

DPGSInternalLinkedTreeMap_EntrySet_$1 *create_DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(DPGSInternalLinkedTreeMap_EntrySet *outer$) {
  return new_DPGSInternalLinkedTreeMap_EntrySet_$1_initWithDPGSInternalLinkedTreeMap_EntrySet_(outer$);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSInternalLinkedTreeMap_EntrySet_$1)

@implementation DPGSInternalLinkedTreeMap_KeySet

- (jint)size {
  return this$0_->size_;
}

- (id<JavaUtilIterator>)iterator {
  return new_DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(self);
}

- (jboolean)containsWithId:(id)o {
  return [this$0_ containsKeyWithId:o];
}

- (jboolean)removeWithId:(id)key {
  return [this$0_ removeInternalByKeyWithId:key] != nil;
}

- (void)clear {
  [this$0_ clear];
}

- (instancetype)initWithDPGSInternalLinkedTreeMap:(DPGSInternalLinkedTreeMap *)outer$ {
  DPGSInternalLinkedTreeMap_KeySet_initWithDPGSInternalLinkedTreeMap_(self, outer$);
  return self;
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "iterator", NULL, "Ljava.util.Iterator;", 0x1, NULL, "()Ljava/util/Iterator<TK;>;" },
    { "containsWithId:", "contains", "Z", 0x1, NULL, NULL },
    { "removeWithId:", "remove", "Z", 0x1, NULL, NULL },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "initWithDPGSInternalLinkedTreeMap:", "init", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.LinkedTreeMap;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"TK;"};
  static const J2ObjcClassInfo _DPGSInternalLinkedTreeMap_KeySet = { 2, "KeySet", "com.google.gson.internal", "LinkedTreeMap", 0x10, 6, methods, 1, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/util/AbstractSet<TK;>;" };
  return &_DPGSInternalLinkedTreeMap_KeySet;
}

@end

void DPGSInternalLinkedTreeMap_KeySet_initWithDPGSInternalLinkedTreeMap_(DPGSInternalLinkedTreeMap_KeySet *self, DPGSInternalLinkedTreeMap *outer$) {
  self->this$0_ = outer$;
  JavaUtilAbstractSet_init(self);
}

DPGSInternalLinkedTreeMap_KeySet *new_DPGSInternalLinkedTreeMap_KeySet_initWithDPGSInternalLinkedTreeMap_(DPGSInternalLinkedTreeMap *outer$) {
  DPGSInternalLinkedTreeMap_KeySet *self = [DPGSInternalLinkedTreeMap_KeySet alloc];
  DPGSInternalLinkedTreeMap_KeySet_initWithDPGSInternalLinkedTreeMap_(self, outer$);
  return self;
}

DPGSInternalLinkedTreeMap_KeySet *create_DPGSInternalLinkedTreeMap_KeySet_initWithDPGSInternalLinkedTreeMap_(DPGSInternalLinkedTreeMap *outer$) {
  return new_DPGSInternalLinkedTreeMap_KeySet_initWithDPGSInternalLinkedTreeMap_(outer$);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSInternalLinkedTreeMap_KeySet)

@implementation DPGSInternalLinkedTreeMap_KeySet_$1

- (id)next {
  return ((id) ((DPGSInternalLinkedTreeMap_Node *) nil_chk(DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(self)))->key_);
}

- (instancetype)initWithDPGSInternalLinkedTreeMap_KeySet:(DPGSInternalLinkedTreeMap_KeySet *)outer$ {
  DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "TK;", 0x1, NULL, "()TK;" },
    { "initWithDPGSInternalLinkedTreeMap_KeySet:", "", NULL, 0x0, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"TK;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "DPGSInternalLinkedTreeMap_KeySet", "iterator" };
  static const J2ObjcClassInfo _DPGSInternalLinkedTreeMap_KeySet_$1 = { 2, "", "com.google.gson.internal", "LinkedTreeMap$KeySet", 0x8008, 2, methods, 0, NULL, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/internal/LinkedTreeMap$LinkedTreeMapIterator<TK;>;" };
  return &_DPGSInternalLinkedTreeMap_KeySet_$1;
}

@end

void DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(DPGSInternalLinkedTreeMap_KeySet_$1 *self, DPGSInternalLinkedTreeMap_KeySet *outer$) {
  DPGSInternalLinkedTreeMap_LinkedTreeMapIterator_initWithDPGSInternalLinkedTreeMap_(self, outer$->this$0_);
}

DPGSInternalLinkedTreeMap_KeySet_$1 *new_DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(DPGSInternalLinkedTreeMap_KeySet *outer$) {
  DPGSInternalLinkedTreeMap_KeySet_$1 *self = [DPGSInternalLinkedTreeMap_KeySet_$1 alloc];
  DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(self, outer$);
  return self;
}

DPGSInternalLinkedTreeMap_KeySet_$1 *create_DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(DPGSInternalLinkedTreeMap_KeySet *outer$) {
  return new_DPGSInternalLinkedTreeMap_KeySet_$1_initWithDPGSInternalLinkedTreeMap_KeySet_(outer$);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSInternalLinkedTreeMap_KeySet_$1)

@implementation DPGSInternalLinkedTreeMap_$1

- (jint)compareWithId:(id<JavaLangComparable>)a
               withId:(id<JavaLangComparable>)b {
  return [((id<JavaLangComparable>) nil_chk(a)) compareToWithId:b];
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  DPGSInternalLinkedTreeMap_$1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "compareWithId:withId:", "compare", "I", 0x1, NULL, NULL },
    { "init", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcClassInfo _DPGSInternalLinkedTreeMap_$1 = { 2, "", "com.google.gson.internal", "LinkedTreeMap", 0x8008, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "Ljava/lang/Object;Ljava/util/Comparator<Ljava/lang/Comparable;>;" };
  return &_DPGSInternalLinkedTreeMap_$1;
}

@end

void DPGSInternalLinkedTreeMap_$1_init(DPGSInternalLinkedTreeMap_$1 *self) {
  NSObject_init(self);
}

DPGSInternalLinkedTreeMap_$1 *new_DPGSInternalLinkedTreeMap_$1_init() {
  DPGSInternalLinkedTreeMap_$1 *self = [DPGSInternalLinkedTreeMap_$1 alloc];
  DPGSInternalLinkedTreeMap_$1_init(self);
  return self;
}

DPGSInternalLinkedTreeMap_$1 *create_DPGSInternalLinkedTreeMap_$1_init() {
  return new_DPGSInternalLinkedTreeMap_$1_init();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSInternalLinkedTreeMap_$1)
