//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/RxJava/src/main/java/rx/schedulers/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RxSchedulersPackage_info_INCLUDE_ALL")
#ifdef RxSchedulersPackage_info_RESTRICT
#define RxSchedulersPackage_info_INCLUDE_ALL 0
#else
#define RxSchedulersPackage_info_INCLUDE_ALL 1
#endif
#undef RxSchedulersPackage_info_RESTRICT

#pragma pop_macro("RxSchedulersPackage_info_INCLUDE_ALL")
