//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/squidb/squidb/src/com/yahoo/squidb/sql/BinaryCriterion.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComYahooSquidbSqlBinaryCriterion_INCLUDE_ALL")
#ifdef ComYahooSquidbSqlBinaryCriterion_RESTRICT
#define ComYahooSquidbSqlBinaryCriterion_INCLUDE_ALL 0
#else
#define ComYahooSquidbSqlBinaryCriterion_INCLUDE_ALL 1
#endif
#undef ComYahooSquidbSqlBinaryCriterion_RESTRICT

#if !defined (ComYahooSquidbSqlBinaryCriterion_) && (ComYahooSquidbSqlBinaryCriterion_INCLUDE_ALL || defined(ComYahooSquidbSqlBinaryCriterion_INCLUDE))
#define ComYahooSquidbSqlBinaryCriterion_

#define ComYahooSquidbSqlCriterion_RESTRICT 1
#define ComYahooSquidbSqlCriterion_INCLUDE 1
#include "com/yahoo/squidb/sql/Criterion.h"

@class ComYahooSquidbSqlField;
@class ComYahooSquidbSqlOperator;
@class ComYahooSquidbSqlSqlBuilder;
@class JavaLangStringBuilder;

@interface ComYahooSquidbSqlBinaryCriterion : ComYahooSquidbSqlCriterion {
 @public
  ComYahooSquidbSqlField *field_;
  id value_;
}

#pragma mark Public

- (ComYahooSquidbSqlCriterion *)negate;

#pragma mark Protected

- (void)afterPopulateOperatorWithComYahooSquidbSqlSqlBuilder:(ComYahooSquidbSqlSqlBuilder *)builder
                                                 withBoolean:(jboolean)forSqlValidation;

- (void)beforePopulateOperatorWithComYahooSquidbSqlSqlBuilder:(ComYahooSquidbSqlSqlBuilder *)builder
                                                  withBoolean:(jboolean)forSqlValidation;

- (ComYahooSquidbSqlBinaryCriterion *)constructNegatedCriterionWithComYahooSquidbSqlOperator:(ComYahooSquidbSqlOperator *)negatedOperator;

- (void)populateWithComYahooSquidbSqlSqlBuilder:(ComYahooSquidbSqlSqlBuilder *)builder
                                    withBoolean:(jboolean)forSqlValidation;

- (void)populateOperatorWithJavaLangStringBuilder:(JavaLangStringBuilder *)sql;

#pragma mark Package-Private

- (instancetype)initWithComYahooSquidbSqlField:(ComYahooSquidbSqlField *)expression
                 withComYahooSquidbSqlOperator:(ComYahooSquidbSqlOperator *)operator_
                                        withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbSqlBinaryCriterion)

J2OBJC_FIELD_SETTER(ComYahooSquidbSqlBinaryCriterion, field_, ComYahooSquidbSqlField *)
J2OBJC_FIELD_SETTER(ComYahooSquidbSqlBinaryCriterion, value_, id)

FOUNDATION_EXPORT void ComYahooSquidbSqlBinaryCriterion_initWithComYahooSquidbSqlField_withComYahooSquidbSqlOperator_withId_(ComYahooSquidbSqlBinaryCriterion *self, ComYahooSquidbSqlField *expression, ComYahooSquidbSqlOperator *operator_, id value);

FOUNDATION_EXPORT ComYahooSquidbSqlBinaryCriterion *new_ComYahooSquidbSqlBinaryCriterion_initWithComYahooSquidbSqlField_withComYahooSquidbSqlOperator_withId_(ComYahooSquidbSqlField *expression, ComYahooSquidbSqlOperator *operator_, id value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbSqlBinaryCriterion *create_ComYahooSquidbSqlBinaryCriterion_initWithComYahooSquidbSqlField_withComYahooSquidbSqlOperator_withId_(ComYahooSquidbSqlField *expression, ComYahooSquidbSqlOperator *operator_, id value);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbSqlBinaryCriterion)

#endif

#pragma pop_macro("ComYahooSquidbSqlBinaryCriterion_INCLUDE_ALL")
