//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/squidb/squidb/src/com/yahoo/squidb/sql/Operator.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/yahoo/squidb/sql/Operator.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"

@interface ComYahooSquidbSqlOperator () {
 @public
  NSString *operator__;
}

@end

J2OBJC_FIELD_SETTER(ComYahooSquidbSqlOperator, operator__, NSString *)

inline id<JavaUtilMap> ComYahooSquidbSqlOperator_get_contraryRegistry();
static id<JavaUtilMap> ComYahooSquidbSqlOperator_contraryRegistry;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComYahooSquidbSqlOperator, contraryRegistry, id<JavaUtilMap>)

__attribute__((unused)) static void ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(ComYahooSquidbSqlOperator *self, NSString *operator_, NSString *__name, jint __ordinal);

__attribute__((unused)) static ComYahooSquidbSqlOperator *new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(NSString *operator_, NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

J2OBJC_INITIALIZED_DEFN(ComYahooSquidbSqlOperator)

ComYahooSquidbSqlOperator *ComYahooSquidbSqlOperator_values_[21];

@implementation ComYahooSquidbSqlOperator

- (ComYahooSquidbSqlOperator *)getContrary {
  return [((id<JavaUtilMap>) nil_chk(ComYahooSquidbSqlOperator_contraryRegistry)) getWithId:self];
}

- (NSString *)description {
  return self->operator__;
}

+ (IOSObjectArray *)values {
  return ComYahooSquidbSqlOperator_values();
}

+ (ComYahooSquidbSqlOperator *)valueOfWithNSString:(NSString *)name {
  return ComYahooSquidbSqlOperator_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (void)initialize {
  if (self == [ComYahooSquidbSqlOperator class]) {
    JreEnum(ComYahooSquidbSqlOperator, eq) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@"=", @"eq", 0);
    JreEnum(ComYahooSquidbSqlOperator, neq) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@"<>", @"neq", 1);
    JreEnum(ComYahooSquidbSqlOperator, is) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" IS ", @"is", 2);
    JreEnum(ComYahooSquidbSqlOperator, isNot) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" IS NOT ", @"isNot", 3);
    JreEnum(ComYahooSquidbSqlOperator, gt) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@">", @"gt", 4);
    JreEnum(ComYahooSquidbSqlOperator, lt) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@"<", @"lt", 5);
    JreEnum(ComYahooSquidbSqlOperator, gte) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@">=", @"gte", 6);
    JreEnum(ComYahooSquidbSqlOperator, lte) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@"<=", @"lte", 7);
    JreEnum(ComYahooSquidbSqlOperator, and) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" AND ", @"and", 8);
    JreEnum(ComYahooSquidbSqlOperator, or) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" OR ", @"or", 9);
    JreEnum(ComYahooSquidbSqlOperator, not) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" NOT ", @"not", 10);
    JreEnum(ComYahooSquidbSqlOperator, exists) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" EXISTS ", @"exists", 11);
    JreEnum(ComYahooSquidbSqlOperator, like) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" LIKE ", @"like", 12);
    JreEnum(ComYahooSquidbSqlOperator, notLike) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" NOT LIKE ", @"notLike", 13);
    JreEnum(ComYahooSquidbSqlOperator, in) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" IN ", @"in", 14);
    JreEnum(ComYahooSquidbSqlOperator, notIn) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" NOT IN ", @"notIn", 15);
    JreEnum(ComYahooSquidbSqlOperator, between) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" BETWEEN ", @"between", 16);
    JreEnum(ComYahooSquidbSqlOperator, notBetween) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" NOT BETWEEN ", @"notBetween", 17);
    JreEnum(ComYahooSquidbSqlOperator, glob) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" GLOB ", @"glob", 18);
    JreEnum(ComYahooSquidbSqlOperator, notGlob) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" NOT GLOB ", @"notGlob", 19);
    JreEnum(ComYahooSquidbSqlOperator, match) = new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(@" MATCH ", @"match", 20);
    ComYahooSquidbSqlOperator_contraryRegistry = new_JavaUtilHashMap_init();
    {
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, eq) withId:JreEnum(ComYahooSquidbSqlOperator, neq)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, neq) withId:JreEnum(ComYahooSquidbSqlOperator, eq)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, is) withId:JreEnum(ComYahooSquidbSqlOperator, isNot)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, isNot) withId:JreEnum(ComYahooSquidbSqlOperator, is)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, gt) withId:JreEnum(ComYahooSquidbSqlOperator, lte)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, lte) withId:JreEnum(ComYahooSquidbSqlOperator, gt)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, lt) withId:JreEnum(ComYahooSquidbSqlOperator, gte)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, gte) withId:JreEnum(ComYahooSquidbSqlOperator, lt)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, like) withId:JreEnum(ComYahooSquidbSqlOperator, notLike)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, notLike) withId:JreEnum(ComYahooSquidbSqlOperator, like)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, in) withId:JreEnum(ComYahooSquidbSqlOperator, notIn)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, notIn) withId:JreEnum(ComYahooSquidbSqlOperator, in)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, between) withId:JreEnum(ComYahooSquidbSqlOperator, notBetween)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, notBetween) withId:JreEnum(ComYahooSquidbSqlOperator, between)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, glob) withId:JreEnum(ComYahooSquidbSqlOperator, notGlob)];
      (void) [ComYahooSquidbSqlOperator_contraryRegistry putWithId:JreEnum(ComYahooSquidbSqlOperator, notGlob) withId:JreEnum(ComYahooSquidbSqlOperator, glob)];
    }
    J2OBJC_SET_INITIALIZED(ComYahooSquidbSqlOperator)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getContrary", NULL, "Lcom.yahoo.squidb.sql.Operator;", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "eq", "eq", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, eq), NULL, .constantValue.asLong = 0 },
    { "neq", "neq", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, neq), NULL, .constantValue.asLong = 0 },
    { "is", "is", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, is), NULL, .constantValue.asLong = 0 },
    { "isNot", "isNot", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, isNot), NULL, .constantValue.asLong = 0 },
    { "gt", "gt", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, gt), NULL, .constantValue.asLong = 0 },
    { "lt", "lt", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, lt), NULL, .constantValue.asLong = 0 },
    { "gte", "gte", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, gte), NULL, .constantValue.asLong = 0 },
    { "lte", "lte", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, lte), NULL, .constantValue.asLong = 0 },
    { "and", "and", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, and), NULL, .constantValue.asLong = 0 },
    { "or", "or", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, or), NULL, .constantValue.asLong = 0 },
    { "not", "not", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, not), NULL, .constantValue.asLong = 0 },
    { "exists", "exists", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, exists), NULL, .constantValue.asLong = 0 },
    { "like", "like", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, like), NULL, .constantValue.asLong = 0 },
    { "notLike", "notLike", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, notLike), NULL, .constantValue.asLong = 0 },
    { "in", "in", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, in), NULL, .constantValue.asLong = 0 },
    { "notIn", "notIn", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, notIn), NULL, .constantValue.asLong = 0 },
    { "between", "between", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, between), NULL, .constantValue.asLong = 0 },
    { "notBetween", "notBetween", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, notBetween), NULL, .constantValue.asLong = 0 },
    { "glob", "glob", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, glob), NULL, .constantValue.asLong = 0 },
    { "notGlob", "notGlob", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, notGlob), NULL, .constantValue.asLong = 0 },
    { "match", "match", 0x4019, "Lcom.yahoo.squidb.sql.Operator;", &JreEnum(ComYahooSquidbSqlOperator, match), NULL, .constantValue.asLong = 0 },
    { "contraryRegistry", "contraryRegistry", 0x1a, "Ljava.util.Map;", &ComYahooSquidbSqlOperator_contraryRegistry, "Ljava/util/Map<Lcom/yahoo/squidb/sql/Operator;Lcom/yahoo/squidb/sql/Operator;>;", .constantValue.asLong = 0 },
    { "operator__", "operator", 0x12, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lcom.yahoo.squidb.sql.Operator;"};
  static const J2ObjcClassInfo _ComYahooSquidbSqlOperator = { 2, "Operator", "com.yahoo.squidb.sql", NULL, 0x4011, 2, methods, 23, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lcom/yahoo/squidb/sql/Operator;>;" };
  return &_ComYahooSquidbSqlOperator;
}

@end

void ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(ComYahooSquidbSqlOperator *self, NSString *operator_, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  self->operator__ = operator_;
}

ComYahooSquidbSqlOperator *new_ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(NSString *operator_, NSString *__name, jint __ordinal) {
  ComYahooSquidbSqlOperator *self = [ComYahooSquidbSqlOperator alloc];
  ComYahooSquidbSqlOperator_initWithNSString_withNSString_withInt_(self, operator_, __name, __ordinal);
  return self;
}

IOSObjectArray *ComYahooSquidbSqlOperator_values() {
  ComYahooSquidbSqlOperator_initialize();
  return [IOSObjectArray arrayWithObjects:ComYahooSquidbSqlOperator_values_ count:21 type:ComYahooSquidbSqlOperator_class_()];
}

ComYahooSquidbSqlOperator *ComYahooSquidbSqlOperator_valueOfWithNSString_(NSString *name) {
  ComYahooSquidbSqlOperator_initialize();
  for (int i = 0; i < 21; i++) {
    ComYahooSquidbSqlOperator *e = ComYahooSquidbSqlOperator_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

ComYahooSquidbSqlOperator *ComYahooSquidbSqlOperator_fromOrdinal(NSUInteger ordinal) {
  ComYahooSquidbSqlOperator_initialize();
  if (ordinal >= 21) {
    return nil;
  }
  return ComYahooSquidbSqlOperator_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComYahooSquidbSqlOperator)
