//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/okio/okio/src/main/java/okio/BufferedSink.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/io/IOException.h"
#include "java/io/OutputStream.h"
#include "java/nio/charset/Charset.h"
#include "okio/Buffer.h"
#include "okio/BufferedSink.h"
#include "okio/ByteString.h"
#include "okio/Source.h"

@interface OkioBufferedSink : NSObject

@end

@implementation OkioBufferedSink

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "buffer", NULL, "Lokio.Buffer;", 0x401, NULL, NULL },
    { "writeWithOkioByteString:", "write", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeWithByteArray:", "write", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeWithByteArray:withInt:withInt:", "write", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeAllWithOkioSource:", "writeAll", "J", 0x401, "Ljava.io.IOException;", NULL },
    { "writeWithOkioSource:withLong:", "write", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeUtf8WithNSString:", "writeUtf8", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeStringWithNSString:withJavaNioCharsetCharset:", "writeString", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeByteWithInt:", "writeByte", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeShortWithInt:", "writeShort", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeShortLeWithInt:", "writeShortLe", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeIntWithInt:", "writeInt", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeIntLeWithInt:", "writeIntLe", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeLongWithLong:", "writeLong", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "writeLongLeWithLong:", "writeLongLe", "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "emitCompleteSegments", NULL, "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "emit", NULL, "Lokio.BufferedSink;", 0x401, "Ljava.io.IOException;", NULL },
    { "outputStream", NULL, "Ljava.io.OutputStream;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OkioBufferedSink = { 2, "BufferedSink", "okio", NULL, 0x609, 18, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OkioBufferedSink;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OkioBufferedSink)
