//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/retrofit/retrofit/src/main/java/retrofit/http/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RetrofitHttpPackage_info_INCLUDE_ALL")
#ifdef RetrofitHttpPackage_info_RESTRICT
#define RetrofitHttpPackage_info_INCLUDE_ALL 0
#else
#define RetrofitHttpPackage_info_INCLUDE_ALL 1
#endif
#undef RetrofitHttpPackage_info_RESTRICT

#pragma pop_macro("RetrofitHttpPackage_info_INCLUDE_ALL")
