//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/gson/gson/src/main/java/com/google/gson/JsonNull.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleGsonJsonNull_INCLUDE_ALL")
#ifdef ComGoogleGsonJsonNull_RESTRICT
#define ComGoogleGsonJsonNull_INCLUDE_ALL 0
#else
#define ComGoogleGsonJsonNull_INCLUDE_ALL 1
#endif
#undef ComGoogleGsonJsonNull_RESTRICT

#if !defined (ComGoogleGsonJsonNull_) && (ComGoogleGsonJsonNull_INCLUDE_ALL || defined(ComGoogleGsonJsonNull_INCLUDE))
#define ComGoogleGsonJsonNull_

#define ComGoogleGsonJsonElement_RESTRICT 1
#define ComGoogleGsonJsonElement_INCLUDE 1
#include "com/google/gson/JsonElement.h"

@interface ComGoogleGsonJsonNull : ComGoogleGsonJsonElement

#pragma mark Public

- (instancetype)init;

- (jboolean)isEqual:(id)other;

- (NSUInteger)hash;

#pragma mark Package-Private

- (ComGoogleGsonJsonNull *)deepCopy;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonJsonNull)

inline ComGoogleGsonJsonNull *ComGoogleGsonJsonNull_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleGsonJsonNull *ComGoogleGsonJsonNull_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleGsonJsonNull, INSTANCE, ComGoogleGsonJsonNull *)

FOUNDATION_EXPORT void ComGoogleGsonJsonNull_init(ComGoogleGsonJsonNull *self);

FOUNDATION_EXPORT ComGoogleGsonJsonNull *new_ComGoogleGsonJsonNull_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonJsonNull *create_ComGoogleGsonJsonNull_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonNull)

#endif

#pragma pop_macro("ComGoogleGsonJsonNull_INCLUDE_ALL")
