//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/RxJava/src/main/java/rx/internal/util/PlatformDependent.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/ClassLoader.h"
#include "java/lang/Exception.h"
#include "java/lang/SecurityManager.h"
#include "java/lang/System.h"
#include "java/security/AccessController.h"
#include "java/security/PrivilegedAction.h"
#include "rx/internal/util/PlatformDependent.h"

@interface RxInternalUtilPlatformDependent ()

+ (jboolean)isAndroid0;

@end

inline jboolean RxInternalUtilPlatformDependent_get_IS_ANDROID();
static jboolean RxInternalUtilPlatformDependent_IS_ANDROID;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(RxInternalUtilPlatformDependent, IS_ANDROID, jboolean)

__attribute__((unused)) static jboolean RxInternalUtilPlatformDependent_isAndroid0();

@interface RxInternalUtilPlatformDependent_$1 : NSObject < JavaSecurityPrivilegedAction >

- (JavaLangClassLoader *)run;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalUtilPlatformDependent_$1)

__attribute__((unused)) static void RxInternalUtilPlatformDependent_$1_init(RxInternalUtilPlatformDependent_$1 *self);

__attribute__((unused)) static RxInternalUtilPlatformDependent_$1 *new_RxInternalUtilPlatformDependent_$1_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static RxInternalUtilPlatformDependent_$1 *create_RxInternalUtilPlatformDependent_$1_init();

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilPlatformDependent_$1)

J2OBJC_INITIALIZED_DEFN(RxInternalUtilPlatformDependent)

@implementation RxInternalUtilPlatformDependent

+ (jboolean)isAndroid {
  return RxInternalUtilPlatformDependent_isAndroid();
}

+ (jboolean)isAndroid0 {
  return RxInternalUtilPlatformDependent_isAndroid0();
}

+ (JavaLangClassLoader *)getSystemClassLoader {
  return RxInternalUtilPlatformDependent_getSystemClassLoader();
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RxInternalUtilPlatformDependent_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initialize {
  if (self == [RxInternalUtilPlatformDependent class]) {
    RxInternalUtilPlatformDependent_IS_ANDROID = RxInternalUtilPlatformDependent_isAndroid0();
    J2OBJC_SET_INITIALIZED(RxInternalUtilPlatformDependent)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "isAndroid", NULL, "Z", 0x9, NULL, NULL },
    { "isAndroid0", NULL, "Z", 0xa, NULL, NULL },
    { "getSystemClassLoader", NULL, "Ljava.lang.ClassLoader;", 0x8, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "IS_ANDROID", "IS_ANDROID", 0x1a, "Z", &RxInternalUtilPlatformDependent_IS_ANDROID, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _RxInternalUtilPlatformDependent = { 2, "PlatformDependent", "rx.internal.util", NULL, 0x11, 4, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_RxInternalUtilPlatformDependent;
}

@end

jboolean RxInternalUtilPlatformDependent_isAndroid() {
  RxInternalUtilPlatformDependent_initialize();
  return RxInternalUtilPlatformDependent_IS_ANDROID;
}

jboolean RxInternalUtilPlatformDependent_isAndroid0() {
  RxInternalUtilPlatformDependent_initialize();
  jboolean android;
  @try {
    (void) IOSClass_forName_initialize_classLoader_(@"android.app.Application", false, RxInternalUtilPlatformDependent_getSystemClassLoader());
    android = true;
  }
  @catch (JavaLangException *e) {
    android = false;
  }
  return android;
}

JavaLangClassLoader *RxInternalUtilPlatformDependent_getSystemClassLoader() {
  RxInternalUtilPlatformDependent_initialize();
  if (JavaLangSystem_getSecurityManager() == nil) {
    return JavaLangClassLoader_getSystemClassLoader();
  }
  else {
    return JavaSecurityAccessController_doPrivilegedWithJavaSecurityPrivilegedAction_(new_RxInternalUtilPlatformDependent_$1_init());
  }
}

void RxInternalUtilPlatformDependent_init(RxInternalUtilPlatformDependent *self) {
  NSObject_init(self);
}

RxInternalUtilPlatformDependent *new_RxInternalUtilPlatformDependent_init() {
  RxInternalUtilPlatformDependent *self = [RxInternalUtilPlatformDependent alloc];
  RxInternalUtilPlatformDependent_init(self);
  return self;
}

RxInternalUtilPlatformDependent *create_RxInternalUtilPlatformDependent_init() {
  return new_RxInternalUtilPlatformDependent_init();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalUtilPlatformDependent)

@implementation RxInternalUtilPlatformDependent_$1

- (JavaLangClassLoader *)run {
  return JavaLangClassLoader_getSystemClassLoader();
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RxInternalUtilPlatformDependent_$1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "run", NULL, "Ljava.lang.ClassLoader;", 0x1, NULL, NULL },
    { "init", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "RxInternalUtilPlatformDependent", "getSystemClassLoader" };
  static const J2ObjcClassInfo _RxInternalUtilPlatformDependent_$1 = { 2, "", "rx.internal.util", "PlatformDependent", 0x8008, 2, methods, 0, NULL, 0, NULL, 0, NULL, &enclosing_method, "Ljava/lang/Object;Ljava/security/PrivilegedAction<Ljava/lang/ClassLoader;>;" };
  return &_RxInternalUtilPlatformDependent_$1;
}

@end

void RxInternalUtilPlatformDependent_$1_init(RxInternalUtilPlatformDependent_$1 *self) {
  NSObject_init(self);
}

RxInternalUtilPlatformDependent_$1 *new_RxInternalUtilPlatformDependent_$1_init() {
  RxInternalUtilPlatformDependent_$1 *self = [RxInternalUtilPlatformDependent_$1 alloc];
  RxInternalUtilPlatformDependent_$1_init(self);
  return self;
}

RxInternalUtilPlatformDependent_$1 *create_RxInternalUtilPlatformDependent_$1_init() {
  return new_RxInternalUtilPlatformDependent_$1_init();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalUtilPlatformDependent_$1)
