//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/RxJava/src/main/java/rx/internal/util/PlatformDependent.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RxInternalUtilPlatformDependent_INCLUDE_ALL")
#ifdef RxInternalUtilPlatformDependent_RESTRICT
#define RxInternalUtilPlatformDependent_INCLUDE_ALL 0
#else
#define RxInternalUtilPlatformDependent_INCLUDE_ALL 1
#endif
#undef RxInternalUtilPlatformDependent_RESTRICT

#if !defined (RxInternalUtilPlatformDependent_) && (RxInternalUtilPlatformDependent_INCLUDE_ALL || defined(RxInternalUtilPlatformDependent_INCLUDE))
#define RxInternalUtilPlatformDependent_

@class JavaLangClassLoader;

@interface RxInternalUtilPlatformDependent : NSObject

#pragma mark Public

- (instancetype)init;

+ (jboolean)isAndroid;

#pragma mark Package-Private

+ (JavaLangClassLoader *)getSystemClassLoader;

@end

J2OBJC_STATIC_INIT(RxInternalUtilPlatformDependent)

FOUNDATION_EXPORT jboolean RxInternalUtilPlatformDependent_isAndroid();

FOUNDATION_EXPORT JavaLangClassLoader *RxInternalUtilPlatformDependent_getSystemClassLoader();

FOUNDATION_EXPORT void RxInternalUtilPlatformDependent_init(RxInternalUtilPlatformDependent *self);

FOUNDATION_EXPORT RxInternalUtilPlatformDependent *new_RxInternalUtilPlatformDependent_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalUtilPlatformDependent *create_RxInternalUtilPlatformDependent_init();

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilPlatformDependent)

#endif

#pragma pop_macro("RxInternalUtilPlatformDependent_INCLUDE_ALL")
