//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/RxJava/src/main/java/rx/functions/ActionN.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RxFunctionsActionN_INCLUDE_ALL")
#ifdef RxFunctionsActionN_RESTRICT
#define RxFunctionsActionN_INCLUDE_ALL 0
#else
#define RxFunctionsActionN_INCLUDE_ALL 1
#endif
#undef RxFunctionsActionN_RESTRICT

#if !defined (RxFunctionsActionN_) && (RxFunctionsActionN_INCLUDE_ALL || defined(RxFunctionsActionN_INCLUDE))
#define RxFunctionsActionN_

#define RxFunctionsAction_RESTRICT 1
#define RxFunctionsAction_INCLUDE 1
#include "rx/functions/Action.h"

@class IOSObjectArray;

@protocol RxFunctionsActionN < RxFunctionsAction, NSObject, JavaObject >

- (void)callWithNSObjectArray:(IOSObjectArray *)args;

@end

J2OBJC_EMPTY_STATIC_INIT(RxFunctionsActionN)

J2OBJC_TYPE_LITERAL_HEADER(RxFunctionsActionN)

#endif

#pragma pop_macro("RxFunctionsActionN_INCLUDE_ALL")
