//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/gson/gson/src/main/java/com/google/gson/annotations/Expose.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/google/gson/annotations/Expose.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation DPGSAnnotationsExpose

@synthesize serialize = serialize_;
@synthesize deserialize = deserialize_;

- (instancetype)initWithDeserialize:(jboolean)deserialize__ withSerialize:(jboolean)serialize__ {
  if ((self = [super init])) {
    self->deserialize_ = deserialize__;
    self->serialize_ = serialize__;
  }
  return self;
}

+ (jboolean)serializeDefault {
  return true;
}

+ (jboolean)deserializeDefault {
  return true;
}

- (IOSClass *)annotationType {
  return DPGSAnnotationsExpose_class_();
}

- (NSString *)description {
  return @"@com.google.gson.annotations.Expose()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicy_get_RUNTIME()], [[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementType_get_FIELD() } count:1 type:NSObject_class_()]] } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "serialize", "serialize", "Z", 0x401, NULL, NULL },
    { "serializeDefault", "serialize", "Z", 0x100a, NULL, NULL },
    { "deserialize", "deserialize", "Z", 0x401, NULL, NULL },
    { "deserializeDefault", "deserialize", "Z", 0x100a, NULL, NULL },
  };
  static const J2ObjcClassInfo _DPGSAnnotationsExpose = { 2, "Expose", "com.google.gson.annotations", NULL, 0x2609, 4, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_DPGSAnnotationsExpose;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(DPGSAnnotationsExpose)
