//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/RxJava/src/main/java/rx/schedulers/package-info.java
//

#include "J2ObjC_source.h"
#include "rx/schedulers/package-info.h"
