//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/squeaky/core/src/main/java/co/touchlab/squeaky/misc/IOUtils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("CoTouchlabSqueakyMiscIOUtils_INCLUDE_ALL")
#ifdef CoTouchlabSqueakyMiscIOUtils_RESTRICT
#define CoTouchlabSqueakyMiscIOUtils_INCLUDE_ALL 0
#else
#define CoTouchlabSqueakyMiscIOUtils_INCLUDE_ALL 1
#endif
#undef CoTouchlabSqueakyMiscIOUtils_RESTRICT

#if !defined (CoTouchlabSqueakyMiscIOUtils_) && (CoTouchlabSqueakyMiscIOUtils_INCLUDE_ALL || defined(CoTouchlabSqueakyMiscIOUtils_INCLUDE))
#define CoTouchlabSqueakyMiscIOUtils_

@protocol JavaIoCloseable;

@interface CoTouchlabSqueakyMiscIOUtils : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)closeQuietlyWithJavaIoCloseable:(id<JavaIoCloseable>)closeable;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyMiscIOUtils)

FOUNDATION_EXPORT void CoTouchlabSqueakyMiscIOUtils_closeQuietlyWithJavaIoCloseable_(id<JavaIoCloseable> closeable);

FOUNDATION_EXPORT void CoTouchlabSqueakyMiscIOUtils_init(CoTouchlabSqueakyMiscIOUtils *self);

FOUNDATION_EXPORT CoTouchlabSqueakyMiscIOUtils *new_CoTouchlabSqueakyMiscIOUtils_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyMiscIOUtils *create_CoTouchlabSqueakyMiscIOUtils_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyMiscIOUtils)

#endif

#pragma pop_macro("CoTouchlabSqueakyMiscIOUtils_INCLUDE_ALL")
