//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/retrofit/retrofit/src/main/java/retrofit/mime/TypedFile.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RetrofitMimeTypedFile_INCLUDE_ALL")
#ifdef RetrofitMimeTypedFile_RESTRICT
#define RetrofitMimeTypedFile_INCLUDE_ALL 0
#else
#define RetrofitMimeTypedFile_INCLUDE_ALL 1
#endif
#undef RetrofitMimeTypedFile_RESTRICT

#if !defined (RetrofitMimeTypedFile_) && (RetrofitMimeTypedFile_INCLUDE_ALL || defined(RetrofitMimeTypedFile_INCLUDE))
#define RetrofitMimeTypedFile_

#define RetrofitMimeTypedInput_RESTRICT 1
#define RetrofitMimeTypedInput_INCLUDE 1
#include "retrofit/mime/TypedInput.h"

#define RetrofitMimeTypedOutput_RESTRICT 1
#define RetrofitMimeTypedOutput_INCLUDE 1
#include "retrofit/mime/TypedOutput.h"

@class JavaIoFile;
@class JavaIoInputStream;
@class JavaIoOutputStream;

@interface RetrofitMimeTypedFile : NSObject < RetrofitMimeTypedInput, RetrofitMimeTypedOutput >

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)mimeType
                  withJavaIoFile:(JavaIoFile *)file;

- (jboolean)isEqual:(id)o;

- (JavaIoFile *)file;

- (NSString *)fileName;

- (NSUInteger)hash;

- (JavaIoInputStream *)in;

- (jlong)length;

- (NSString *)mimeType;

- (void)moveToWithRetrofitMimeTypedFile:(RetrofitMimeTypedFile *)destination;

- (NSString *)description;

- (void)writeToWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;

@end

J2OBJC_EMPTY_STATIC_INIT(RetrofitMimeTypedFile)

FOUNDATION_EXPORT void RetrofitMimeTypedFile_initWithNSString_withJavaIoFile_(RetrofitMimeTypedFile *self, NSString *mimeType, JavaIoFile *file);

FOUNDATION_EXPORT RetrofitMimeTypedFile *new_RetrofitMimeTypedFile_initWithNSString_withJavaIoFile_(NSString *mimeType, JavaIoFile *file) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RetrofitMimeTypedFile *create_RetrofitMimeTypedFile_initWithNSString_withJavaIoFile_(NSString *mimeType, JavaIoFile *file);

J2OBJC_TYPE_LITERAL_HEADER(RetrofitMimeTypedFile)

#endif

#pragma pop_macro("RetrofitMimeTypedFile_INCLUDE_ALL")
