//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/RxJava/src/main/java/rx/internal/util/unsafe/SpmcArrayQueue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL")
#ifdef RxInternalUtilUnsafeSpmcArrayQueue_RESTRICT
#define RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL 0
#else
#define RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL 1
#endif
#undef RxInternalUtilUnsafeSpmcArrayQueue_RESTRICT
#ifdef RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE
#define RxInternalUtilUnsafeSpmcArrayQueueL3Pad_INCLUDE 1
#endif
#ifdef RxInternalUtilUnsafeSpmcArrayQueueL3Pad_INCLUDE
#define RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField_INCLUDE 1
#endif
#ifdef RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField_INCLUDE
#define RxInternalUtilUnsafeSpmcArrayQueueMidPad_INCLUDE 1
#endif
#ifdef RxInternalUtilUnsafeSpmcArrayQueueMidPad_INCLUDE
#define RxInternalUtilUnsafeSpmcArrayQueueConsumerField_INCLUDE 1
#endif
#ifdef RxInternalUtilUnsafeSpmcArrayQueueConsumerField_INCLUDE
#define RxInternalUtilUnsafeSpmcArrayQueueL2Pad_INCLUDE 1
#endif
#ifdef RxInternalUtilUnsafeSpmcArrayQueueL2Pad_INCLUDE
#define RxInternalUtilUnsafeSpmcArrayQueueProducerField_INCLUDE 1
#endif
#ifdef RxInternalUtilUnsafeSpmcArrayQueueProducerField_INCLUDE
#define RxInternalUtilUnsafeSpmcArrayQueueL1Pad_INCLUDE 1
#endif

#if !defined (RxInternalUtilUnsafeSpmcArrayQueueL1Pad_) && (RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL || defined(RxInternalUtilUnsafeSpmcArrayQueueL1Pad_INCLUDE))
#define RxInternalUtilUnsafeSpmcArrayQueueL1Pad_

#define RxInternalUtilUnsafeConcurrentCircularArrayQueue_RESTRICT 1
#define RxInternalUtilUnsafeConcurrentCircularArrayQueue_INCLUDE 1
#include "rx/internal/util/unsafe/ConcurrentCircularArrayQueue.h"

@interface RxInternalUtilUnsafeSpmcArrayQueueL1Pad : RxInternalUtilUnsafeConcurrentCircularArrayQueue {
 @public
  jlong p10_, p11_, p12_, p13_, p14_, p15_, p16_;
  jlong p30_SpmcArrayQueueL1Pad_, p31_SpmcArrayQueueL1Pad_, p32_SpmcArrayQueueL1Pad_, p33_SpmcArrayQueueL1Pad_, p34_SpmcArrayQueueL1Pad_, p35_SpmcArrayQueueL1Pad_, p36_SpmcArrayQueueL1Pad_, p37_SpmcArrayQueueL1Pad_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)capacity;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalUtilUnsafeSpmcArrayQueueL1Pad)

FOUNDATION_EXPORT void RxInternalUtilUnsafeSpmcArrayQueueL1Pad_initWithInt_(RxInternalUtilUnsafeSpmcArrayQueueL1Pad *self, jint capacity);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilUnsafeSpmcArrayQueueL1Pad)

#endif

#if !defined (RxInternalUtilUnsafeSpmcArrayQueueProducerField_) && (RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL || defined(RxInternalUtilUnsafeSpmcArrayQueueProducerField_INCLUDE))
#define RxInternalUtilUnsafeSpmcArrayQueueProducerField_

@interface RxInternalUtilUnsafeSpmcArrayQueueProducerField : RxInternalUtilUnsafeSpmcArrayQueueL1Pad

#pragma mark Public

- (instancetype)initWithInt:(jint)capacity;

#pragma mark Protected

- (jlong)lvProducerIndex;

- (void)soTailWithLong:(jlong)v;

#pragma mark Package-Private

@end

J2OBJC_STATIC_INIT(RxInternalUtilUnsafeSpmcArrayQueueProducerField)

inline jlong RxInternalUtilUnsafeSpmcArrayQueueProducerField_get_P_INDEX_OFFSET();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jlong RxInternalUtilUnsafeSpmcArrayQueueProducerField_P_INDEX_OFFSET;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(RxInternalUtilUnsafeSpmcArrayQueueProducerField, P_INDEX_OFFSET, jlong)

FOUNDATION_EXPORT void RxInternalUtilUnsafeSpmcArrayQueueProducerField_initWithInt_(RxInternalUtilUnsafeSpmcArrayQueueProducerField *self, jint capacity);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilUnsafeSpmcArrayQueueProducerField)

#endif

#if !defined (RxInternalUtilUnsafeSpmcArrayQueueL2Pad_) && (RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL || defined(RxInternalUtilUnsafeSpmcArrayQueueL2Pad_INCLUDE))
#define RxInternalUtilUnsafeSpmcArrayQueueL2Pad_

@interface RxInternalUtilUnsafeSpmcArrayQueueL2Pad : RxInternalUtilUnsafeSpmcArrayQueueProducerField {
 @public
  jlong p20_, p21_, p22_, p23_, p24_, p25_, p26_;
  jlong p30_SpmcArrayQueueL2Pad_, p31_SpmcArrayQueueL2Pad_, p32_SpmcArrayQueueL2Pad_, p33_SpmcArrayQueueL2Pad_, p34_SpmcArrayQueueL2Pad_, p35_SpmcArrayQueueL2Pad_, p36_SpmcArrayQueueL2Pad_, p37_SpmcArrayQueueL2Pad_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)capacity;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalUtilUnsafeSpmcArrayQueueL2Pad)

FOUNDATION_EXPORT void RxInternalUtilUnsafeSpmcArrayQueueL2Pad_initWithInt_(RxInternalUtilUnsafeSpmcArrayQueueL2Pad *self, jint capacity);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilUnsafeSpmcArrayQueueL2Pad)

#endif

#if !defined (RxInternalUtilUnsafeSpmcArrayQueueConsumerField_) && (RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL || defined(RxInternalUtilUnsafeSpmcArrayQueueConsumerField_INCLUDE))
#define RxInternalUtilUnsafeSpmcArrayQueueConsumerField_

@interface RxInternalUtilUnsafeSpmcArrayQueueConsumerField : RxInternalUtilUnsafeSpmcArrayQueueL2Pad

#pragma mark Public

- (instancetype)initWithInt:(jint)capacity;

#pragma mark Protected

- (jboolean)casHeadWithLong:(jlong)expect
                   withLong:(jlong)newValue;

- (jlong)lvConsumerIndex;

#pragma mark Package-Private

@end

J2OBJC_STATIC_INIT(RxInternalUtilUnsafeSpmcArrayQueueConsumerField)

inline jlong RxInternalUtilUnsafeSpmcArrayQueueConsumerField_get_C_INDEX_OFFSET();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jlong RxInternalUtilUnsafeSpmcArrayQueueConsumerField_C_INDEX_OFFSET;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(RxInternalUtilUnsafeSpmcArrayQueueConsumerField, C_INDEX_OFFSET, jlong)

FOUNDATION_EXPORT void RxInternalUtilUnsafeSpmcArrayQueueConsumerField_initWithInt_(RxInternalUtilUnsafeSpmcArrayQueueConsumerField *self, jint capacity);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilUnsafeSpmcArrayQueueConsumerField)

#endif

#if !defined (RxInternalUtilUnsafeSpmcArrayQueueMidPad_) && (RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL || defined(RxInternalUtilUnsafeSpmcArrayQueueMidPad_INCLUDE))
#define RxInternalUtilUnsafeSpmcArrayQueueMidPad_

@interface RxInternalUtilUnsafeSpmcArrayQueueMidPad : RxInternalUtilUnsafeSpmcArrayQueueConsumerField {
 @public
  jlong p20_SpmcArrayQueueMidPad_, p21_SpmcArrayQueueMidPad_, p22_SpmcArrayQueueMidPad_, p23_SpmcArrayQueueMidPad_, p24_SpmcArrayQueueMidPad_, p25_SpmcArrayQueueMidPad_, p26_SpmcArrayQueueMidPad_;
  jlong p30_SpmcArrayQueueMidPad_, p31_SpmcArrayQueueMidPad_, p32_SpmcArrayQueueMidPad_, p33_SpmcArrayQueueMidPad_, p34_SpmcArrayQueueMidPad_, p35_SpmcArrayQueueMidPad_, p36_SpmcArrayQueueMidPad_, p37_SpmcArrayQueueMidPad_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)capacity;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalUtilUnsafeSpmcArrayQueueMidPad)

FOUNDATION_EXPORT void RxInternalUtilUnsafeSpmcArrayQueueMidPad_initWithInt_(RxInternalUtilUnsafeSpmcArrayQueueMidPad *self, jint capacity);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilUnsafeSpmcArrayQueueMidPad)

#endif

#if !defined (RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField_) && (RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL || defined(RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField_INCLUDE))
#define RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField_

@interface RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField : RxInternalUtilUnsafeSpmcArrayQueueMidPad

#pragma mark Public

- (instancetype)initWithInt:(jint)capacity;

#pragma mark Protected

- (jlong)lvProducerIndexCache;

- (void)svProducerIndexCacheWithLong:(jlong)v;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField)

FOUNDATION_EXPORT void RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField_initWithInt_(RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField *self, jint capacity);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField)

#endif

#if !defined (RxInternalUtilUnsafeSpmcArrayQueueL3Pad_) && (RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL || defined(RxInternalUtilUnsafeSpmcArrayQueueL3Pad_INCLUDE))
#define RxInternalUtilUnsafeSpmcArrayQueueL3Pad_

@interface RxInternalUtilUnsafeSpmcArrayQueueL3Pad : RxInternalUtilUnsafeSpmcArrayQueueProducerIndexCacheField {
 @public
  jlong p40_, p41_, p42_, p43_, p44_, p45_, p46_;
  jlong p30_SpmcArrayQueueL3Pad_, p31_SpmcArrayQueueL3Pad_, p32_SpmcArrayQueueL3Pad_, p33_SpmcArrayQueueL3Pad_, p34_SpmcArrayQueueL3Pad_, p35_SpmcArrayQueueL3Pad_, p36_SpmcArrayQueueL3Pad_, p37_SpmcArrayQueueL3Pad_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)capacity;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalUtilUnsafeSpmcArrayQueueL3Pad)

FOUNDATION_EXPORT void RxInternalUtilUnsafeSpmcArrayQueueL3Pad_initWithInt_(RxInternalUtilUnsafeSpmcArrayQueueL3Pad *self, jint capacity);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilUnsafeSpmcArrayQueueL3Pad)

#endif

#if !defined (RxInternalUtilUnsafeSpmcArrayQueue_) && (RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL || defined(RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE))
#define RxInternalUtilUnsafeSpmcArrayQueue_

@interface RxInternalUtilUnsafeSpmcArrayQueue : RxInternalUtilUnsafeSpmcArrayQueueL3Pad

#pragma mark Public

- (instancetype)initWithInt:(jint)capacity;

- (jboolean)isEmpty;

- (jboolean)offerWithId:(id)e;

- (id)peek;

- (id)poll;

- (jint)size;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalUtilUnsafeSpmcArrayQueue)

FOUNDATION_EXPORT void RxInternalUtilUnsafeSpmcArrayQueue_initWithInt_(RxInternalUtilUnsafeSpmcArrayQueue *self, jint capacity);

FOUNDATION_EXPORT RxInternalUtilUnsafeSpmcArrayQueue *new_RxInternalUtilUnsafeSpmcArrayQueue_initWithInt_(jint capacity) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalUtilUnsafeSpmcArrayQueue *create_RxInternalUtilUnsafeSpmcArrayQueue_initWithInt_(jint capacity);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilUnsafeSpmcArrayQueue)

#endif

#pragma pop_macro("RxInternalUtilUnsafeSpmcArrayQueue_INCLUDE_ALL")
