//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/squidb/squidb-ios/src/com/yahoo/android/sqlite/Printer.java
//

#include "J2ObjC_source.h"
#include "com/yahoo/android/sqlite/Printer.h"

@interface ComYahooAndroidSqlitePrinter : NSObject

@end

@implementation ComYahooAndroidSqlitePrinter

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "printlnWithNSString:", "println", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComYahooAndroidSqlitePrinter = { 2, "Printer", "com.yahoo.android.sqlite", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComYahooAndroidSqlitePrinter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComYahooAndroidSqlitePrinter)
