//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/squidb/squidb-ios/src/com/yahoo/android/sqlite/SQLiteDebug.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/yahoo/android/sqlite/Printer.h"
#include "com/yahoo/android/sqlite/SQLiteDatabase.h"
#include "com/yahoo/android/sqlite/SQLiteDebug.h"
#include "java/util/ArrayList.h"

@interface ComYahooAndroidSqliteSQLiteDebug ()

- (instancetype)init;

@end

__attribute__((unused)) static void ComYahooAndroidSqliteSQLiteDebug_init(ComYahooAndroidSqliteSQLiteDebug *self);

__attribute__((unused)) static ComYahooAndroidSqliteSQLiteDebug *new_ComYahooAndroidSqliteSQLiteDebug_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComYahooAndroidSqliteSQLiteDebug *create_ComYahooAndroidSqliteSQLiteDebug_init();

@implementation ComYahooAndroidSqliteSQLiteDebug

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComYahooAndroidSqliteSQLiteDebug_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (jboolean)shouldLogSlowQueryWithLong:(jlong)elapsedTimeMillis {
  return ComYahooAndroidSqliteSQLiteDebug_shouldLogSlowQueryWithLong_(elapsedTimeMillis);
}

+ (void)dumpWithComYahooAndroidSqlitePrinter:(id<ComYahooAndroidSqlitePrinter>)printer
                           withNSStringArray:(IOSObjectArray *)args {
  ComYahooAndroidSqliteSQLiteDebug_dumpWithComYahooAndroidSqlitePrinter_withNSStringArray_(printer, args);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "SQLiteDebug", NULL, 0x2, NULL, NULL },
    { "shouldLogSlowQueryWithLong:", "shouldLogSlowQuery", "Z", 0x19, NULL, NULL },
    { "dumpWithComYahooAndroidSqlitePrinter:withNSStringArray:", "dump", "V", 0x9, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "DEBUG_SQL_LOG", "DEBUG_SQL_LOG", 0x19, "Z", NULL, NULL, .constantValue.asBOOL = ComYahooAndroidSqliteSQLiteDebug_DEBUG_SQL_LOG },
    { "DEBUG_SQL_STATEMENTS", "DEBUG_SQL_STATEMENTS", 0x19, "Z", NULL, NULL, .constantValue.asBOOL = ComYahooAndroidSqliteSQLiteDebug_DEBUG_SQL_STATEMENTS },
    { "DEBUG_SQL_TIME", "DEBUG_SQL_TIME", 0x19, "Z", NULL, NULL, .constantValue.asBOOL = ComYahooAndroidSqliteSQLiteDebug_DEBUG_SQL_TIME },
    { "DEBUG_LOG_SLOW_QUERIES", "DEBUG_LOG_SLOW_QUERIES", 0x19, "Z", NULL, NULL, .constantValue.asBOOL = ComYahooAndroidSqliteSQLiteDebug_DEBUG_LOG_SLOW_QUERIES },
  };
  static const char *inner_classes[] = {"Lcom.yahoo.android.sqlite.SQLiteDebug$PagerStats;", "Lcom.yahoo.android.sqlite.SQLiteDebug$DbStats;"};
  static const J2ObjcClassInfo _ComYahooAndroidSqliteSQLiteDebug = { 2, "SQLiteDebug", "com.yahoo.android.sqlite", NULL, 0x11, 3, methods, 4, fields, 0, NULL, 2, inner_classes, NULL, NULL };
  return &_ComYahooAndroidSqliteSQLiteDebug;
}

@end

void ComYahooAndroidSqliteSQLiteDebug_init(ComYahooAndroidSqliteSQLiteDebug *self) {
  NSObject_init(self);
}

ComYahooAndroidSqliteSQLiteDebug *new_ComYahooAndroidSqliteSQLiteDebug_init() {
  ComYahooAndroidSqliteSQLiteDebug *self = [ComYahooAndroidSqliteSQLiteDebug alloc];
  ComYahooAndroidSqliteSQLiteDebug_init(self);
  return self;
}

ComYahooAndroidSqliteSQLiteDebug *create_ComYahooAndroidSqliteSQLiteDebug_init() {
  return new_ComYahooAndroidSqliteSQLiteDebug_init();
}

jboolean ComYahooAndroidSqliteSQLiteDebug_shouldLogSlowQueryWithLong_(jlong elapsedTimeMillis) {
  ComYahooAndroidSqliteSQLiteDebug_initialize();
  jint slowQueryMillis = 10000;
  return slowQueryMillis >= 0 && elapsedTimeMillis >= slowQueryMillis;
}

void ComYahooAndroidSqliteSQLiteDebug_dumpWithComYahooAndroidSqlitePrinter_withNSStringArray_(id<ComYahooAndroidSqlitePrinter> printer, IOSObjectArray *args) {
  ComYahooAndroidSqliteSQLiteDebug_initialize();
  jboolean verbose = false;
  {
    IOSObjectArray *a__ = args;
    NSString * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
    NSString * const *e__ = b__ + a__->size_;
    while (b__ < e__) {
      NSString *arg = *b__++;
      if ([((NSString *) nil_chk(arg)) isEqual:@"-v"]) {
        verbose = true;
      }
    }
  }
  ComYahooAndroidSqliteSQLiteDatabase_dumpAllWithComYahooAndroidSqlitePrinter_withBoolean_(printer, verbose);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComYahooAndroidSqliteSQLiteDebug)

@implementation ComYahooAndroidSqliteSQLiteDebug_PagerStats

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComYahooAndroidSqliteSQLiteDebug_PagerStats_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "memoryUsed_", NULL, 0x1, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "pageCacheOverflow_", NULL, 0x1, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "largestMemAlloc_", NULL, 0x1, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "dbStats_", NULL, 0x1, "Ljava.util.ArrayList;", NULL, "Ljava/util/ArrayList<Lcom/yahoo/android/sqlite/SQLiteDebug$DbStats;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComYahooAndroidSqliteSQLiteDebug_PagerStats = { 2, "PagerStats", "com.yahoo.android.sqlite", "SQLiteDebug", 0x9, 1, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComYahooAndroidSqliteSQLiteDebug_PagerStats;
}

@end

void ComYahooAndroidSqliteSQLiteDebug_PagerStats_init(ComYahooAndroidSqliteSQLiteDebug_PagerStats *self) {
  NSObject_init(self);
}

ComYahooAndroidSqliteSQLiteDebug_PagerStats *new_ComYahooAndroidSqliteSQLiteDebug_PagerStats_init() {
  ComYahooAndroidSqliteSQLiteDebug_PagerStats *self = [ComYahooAndroidSqliteSQLiteDebug_PagerStats alloc];
  ComYahooAndroidSqliteSQLiteDebug_PagerStats_init(self);
  return self;
}

ComYahooAndroidSqliteSQLiteDebug_PagerStats *create_ComYahooAndroidSqliteSQLiteDebug_PagerStats_init() {
  return new_ComYahooAndroidSqliteSQLiteDebug_PagerStats_init();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComYahooAndroidSqliteSQLiteDebug_PagerStats)

@implementation ComYahooAndroidSqliteSQLiteDebug_DbStats

- (instancetype)initWithNSString:(NSString *)dbName
                        withLong:(jlong)pageCount
                        withLong:(jlong)pageSize
                         withInt:(jint)lookaside
                         withInt:(jint)hits
                         withInt:(jint)misses
                         withInt:(jint)cachesize {
  ComYahooAndroidSqliteSQLiteDebug_DbStats_initWithNSString_withLong_withLong_withInt_withInt_withInt_withInt_(self, dbName, pageCount, pageSize, lookaside, hits, misses, cachesize);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withLong:withLong:withInt:withInt:withInt:withInt:", "DbStats", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "dbName_", NULL, 0x1, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "pageSize_", NULL, 0x1, "J", NULL, NULL, .constantValue.asLong = 0 },
    { "dbSize_", NULL, 0x1, "J", NULL, NULL, .constantValue.asLong = 0 },
    { "lookaside_", NULL, 0x1, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "cache_", NULL, 0x1, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComYahooAndroidSqliteSQLiteDebug_DbStats = { 2, "DbStats", "com.yahoo.android.sqlite", "SQLiteDebug", 0x9, 1, methods, 5, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComYahooAndroidSqliteSQLiteDebug_DbStats;
}

@end

void ComYahooAndroidSqliteSQLiteDebug_DbStats_initWithNSString_withLong_withLong_withInt_withInt_withInt_withInt_(ComYahooAndroidSqliteSQLiteDebug_DbStats *self, NSString *dbName, jlong pageCount, jlong pageSize, jint lookaside, jint hits, jint misses, jint cachesize) {
  NSObject_init(self);
  self->dbName_ = dbName;
  self->pageSize_ = pageSize / 1024;
  self->dbSize_ = (pageCount * pageSize) / 1024;
  self->lookaside_ = lookaside;
  self->cache_ = JreStrcat("ICICI", hits, '/', misses, '/', cachesize);
}

ComYahooAndroidSqliteSQLiteDebug_DbStats *new_ComYahooAndroidSqliteSQLiteDebug_DbStats_initWithNSString_withLong_withLong_withInt_withInt_withInt_withInt_(NSString *dbName, jlong pageCount, jlong pageSize, jint lookaside, jint hits, jint misses, jint cachesize) {
  ComYahooAndroidSqliteSQLiteDebug_DbStats *self = [ComYahooAndroidSqliteSQLiteDebug_DbStats alloc];
  ComYahooAndroidSqliteSQLiteDebug_DbStats_initWithNSString_withLong_withLong_withInt_withInt_withInt_withInt_(self, dbName, pageCount, pageSize, lookaside, hits, misses, cachesize);
  return self;
}

ComYahooAndroidSqliteSQLiteDebug_DbStats *create_ComYahooAndroidSqliteSQLiteDebug_DbStats_initWithNSString_withLong_withLong_withInt_withInt_withInt_withInt_(NSString *dbName, jlong pageCount, jlong pageSize, jint lookaside, jint hits, jint misses, jint cachesize) {
  return new_ComYahooAndroidSqliteSQLiteDebug_DbStats_initWithNSString_withLong_withLong_withInt_withInt_withInt_withInt_(dbName, pageCount, pageSize, lookaside, hits, misses, cachesize);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComYahooAndroidSqliteSQLiteDebug_DbStats)
