//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/squidb/squidb/src/com/yahoo/squidb/data/ValuesStorage.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComYahooSquidbDataValuesStorage_INCLUDE_ALL")
#ifdef ComYahooSquidbDataValuesStorage_RESTRICT
#define ComYahooSquidbDataValuesStorage_INCLUDE_ALL 0
#else
#define ComYahooSquidbDataValuesStorage_INCLUDE_ALL 1
#endif
#undef ComYahooSquidbDataValuesStorage_RESTRICT

#if !defined (ComYahooSquidbDataValuesStorage_) && (ComYahooSquidbDataValuesStorage_INCLUDE_ALL || defined(ComYahooSquidbDataValuesStorage_INCLUDE))
#define ComYahooSquidbDataValuesStorage_

@class IOSByteArray;
@class JavaLangBoolean;
@class JavaLangByte;
@class JavaLangDouble;
@class JavaLangFloat;
@class JavaLangInteger;
@class JavaLangLong;
@class JavaLangShort;
@protocol JavaUtilSet;

@interface ComYahooSquidbDataValuesStorage : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)containsKeyWithNSString:(NSString *)key;

- (jboolean)isEqual:(id)o;

- (id)getWithNSString:(NSString *)key;

- (NSUInteger)hash;

- (id<JavaUtilSet>)keySet;

- (void)putWithNSString:(NSString *)key
    withJavaLangBoolean:(JavaLangBoolean *)value;

- (void)putWithNSString:(NSString *)key
       withJavaLangByte:(JavaLangByte *)value;

- (void)putWithNSString:(NSString *)key
          withByteArray:(IOSByteArray *)value;

- (void)putWithNSString:(NSString *)key
     withJavaLangDouble:(JavaLangDouble *)value;

- (void)putWithNSString:(NSString *)key
      withJavaLangFloat:(JavaLangFloat *)value;

- (void)putWithNSString:(NSString *)key
    withJavaLangInteger:(JavaLangInteger *)value;

- (void)putWithNSString:(NSString *)key
       withJavaLangLong:(JavaLangLong *)value;

- (void)putWithNSString:(NSString *)key
                 withId:(id)value
            withBoolean:(jboolean)errorOnFail;

- (void)putWithNSString:(NSString *)key
      withJavaLangShort:(JavaLangShort *)value;

- (void)putWithNSString:(NSString *)key
           withNSString:(NSString *)value;

- (void)putAllWithComYahooSquidbDataValuesStorage:(ComYahooSquidbDataValuesStorage *)other;

- (void)putNullWithNSString:(NSString *)key;

- (void)removeWithNSString:(NSString *)key;

- (jint)size;

- (id<JavaUtilSet>)valueSet;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbDataValuesStorage)

FOUNDATION_EXPORT void ComYahooSquidbDataValuesStorage_init(ComYahooSquidbDataValuesStorage *self);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbDataValuesStorage)

#endif

#pragma pop_macro("ComYahooSquidbDataValuesStorage_INCLUDE_ALL")
