//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/gson/gson/src/main/java/com/google/gson/FieldNamingStrategy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleGsonFieldNamingStrategy_INCLUDE_ALL")
#ifdef ComGoogleGsonFieldNamingStrategy_RESTRICT
#define ComGoogleGsonFieldNamingStrategy_INCLUDE_ALL 0
#else
#define ComGoogleGsonFieldNamingStrategy_INCLUDE_ALL 1
#endif
#undef ComGoogleGsonFieldNamingStrategy_RESTRICT

#if !defined (DPGSFieldNamingStrategy_) && (ComGoogleGsonFieldNamingStrategy_INCLUDE_ALL || defined(DPGSFieldNamingStrategy_INCLUDE))
#define DPGSFieldNamingStrategy_

@class JavaLangReflectField;

@protocol DPGSFieldNamingStrategy < NSObject, JavaObject >

- (NSString *)translateNameWithJavaLangReflectField:(JavaLangReflectField *)f;

@end

J2OBJC_EMPTY_STATIC_INIT(DPGSFieldNamingStrategy)

J2OBJC_TYPE_LITERAL_HEADER(DPGSFieldNamingStrategy)

#define ComGoogleGsonFieldNamingStrategy DPGSFieldNamingStrategy

#endif

#pragma pop_macro("ComGoogleGsonFieldNamingStrategy_INCLUDE_ALL")
