//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/gson/gson/src/main/java/com/google/gson/TreeTypeAdapter.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/google/gson/Gson.h"
#include "com/google/gson/JsonDeserializationContext.h"
#include "com/google/gson/JsonDeserializer.h"
#include "com/google/gson/JsonElement.h"
#include "com/google/gson/JsonSerializationContext.h"
#include "com/google/gson/JsonSerializer.h"
#include "com/google/gson/TreeTypeAdapter.h"
#include "com/google/gson/TypeAdapter.h"
#include "com/google/gson/TypeAdapterFactory.h"
#include "com/google/gson/internal/$Gson$Preconditions.h"
#include "com/google/gson/internal/Streams.h"
#include "com/google/gson/reflect/TypeToken.h"
#include "com/google/gson/stream/JsonReader.h"
#include "com/google/gson/stream/JsonWriter.h"
#include "java/io/IOException.h"
#include "java/lang/reflect/Type.h"

@interface DPGSTreeTypeAdapter () {
 @public
  id<DPGSJsonSerializer> serializer_;
  id<DPGSJsonDeserializer> deserializer_;
  DPGSGson *gson_;
  DPGSReflectTypeToken *typeToken_;
  id<DPGSTypeAdapterFactory> skipPast_;
  DPGSTypeAdapter *delegate_;
}

- (DPGSTypeAdapter *)delegate;

@end

J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter, serializer_, id<DPGSJsonSerializer>)
J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter, deserializer_, id<DPGSJsonDeserializer>)
J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter, gson_, DPGSGson *)
J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter, typeToken_, DPGSReflectTypeToken *)
J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter, skipPast_, id<DPGSTypeAdapterFactory>)
J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter, delegate_, DPGSTypeAdapter *)

__attribute__((unused)) static DPGSTypeAdapter *DPGSTreeTypeAdapter_delegate(DPGSTreeTypeAdapter *self);

@interface DPGSTreeTypeAdapter_SingleTypeFactory : NSObject < DPGSTypeAdapterFactory > {
 @public
  DPGSReflectTypeToken *exactType_;
  jboolean matchRawType_;
  IOSClass *hierarchyType_;
  id<DPGSJsonSerializer> serializer_;
  id<DPGSJsonDeserializer> deserializer_;
}

- (instancetype)initWithId:(id)typeAdapter
  withDPGSReflectTypeToken:(DPGSReflectTypeToken *)exactType
               withBoolean:(jboolean)matchRawType
              withIOSClass:(IOSClass *)hierarchyType;

- (DPGSTypeAdapter *)createWithDPGSGson:(DPGSGson *)gson
               withDPGSReflectTypeToken:(DPGSReflectTypeToken *)type;

@end

J2OBJC_EMPTY_STATIC_INIT(DPGSTreeTypeAdapter_SingleTypeFactory)

J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter_SingleTypeFactory, exactType_, DPGSReflectTypeToken *)
J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter_SingleTypeFactory, hierarchyType_, IOSClass *)
J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter_SingleTypeFactory, serializer_, id<DPGSJsonSerializer>)
J2OBJC_FIELD_SETTER(DPGSTreeTypeAdapter_SingleTypeFactory, deserializer_, id<DPGSJsonDeserializer>)

__attribute__((unused)) static void DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(DPGSTreeTypeAdapter_SingleTypeFactory *self, id typeAdapter, DPGSReflectTypeToken *exactType, jboolean matchRawType, IOSClass *hierarchyType);

__attribute__((unused)) static DPGSTreeTypeAdapter_SingleTypeFactory *new_DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(id typeAdapter, DPGSReflectTypeToken *exactType, jboolean matchRawType, IOSClass *hierarchyType) NS_RETURNS_RETAINED;

__attribute__((unused)) static DPGSTreeTypeAdapter_SingleTypeFactory *create_DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(id typeAdapter, DPGSReflectTypeToken *exactType, jboolean matchRawType, IOSClass *hierarchyType);

J2OBJC_TYPE_LITERAL_HEADER(DPGSTreeTypeAdapter_SingleTypeFactory)

@implementation DPGSTreeTypeAdapter

- (instancetype)initWithDPGSJsonSerializer:(id<DPGSJsonSerializer>)serializer
                  withDPGSJsonDeserializer:(id<DPGSJsonDeserializer>)deserializer
                              withDPGSGson:(DPGSGson *)gson
                  withDPGSReflectTypeToken:(DPGSReflectTypeToken *)typeToken
                withDPGSTypeAdapterFactory:(id<DPGSTypeAdapterFactory>)skipPast {
  DPGSTreeTypeAdapter_initWithDPGSJsonSerializer_withDPGSJsonDeserializer_withDPGSGson_withDPGSReflectTypeToken_withDPGSTypeAdapterFactory_(self, serializer, deserializer, gson, typeToken, skipPast);
  return self;
}

- (id)readWithDPGSStreamJsonReader:(DPGSStreamJsonReader *)inArg {
  if (deserializer_ == nil) {
    return [((DPGSTypeAdapter *) nil_chk(DPGSTreeTypeAdapter_delegate(self))) readWithDPGSStreamJsonReader:inArg];
  }
  DPGSJsonElement *value = DPGSInternalStreams_parseWithDPGSStreamJsonReader_(inArg);
  if ([((DPGSJsonElement *) nil_chk(value)) isJsonNull]) {
    return nil;
  }
  return [((id<DPGSJsonDeserializer>) nil_chk(deserializer_)) deserializeWithDPGSJsonElement:value withJavaLangReflectType:[((DPGSReflectTypeToken *) nil_chk(typeToken_)) getType] withDPGSJsonDeserializationContext:((DPGSGson *) nil_chk(gson_))->deserializationContext_];
}

- (void)writeWithDPGSStreamJsonWriter:(DPGSStreamJsonWriter *)outArg
                               withId:(id)value {
  if (serializer_ == nil) {
    [((DPGSTypeAdapter *) nil_chk(DPGSTreeTypeAdapter_delegate(self))) writeWithDPGSStreamJsonWriter:outArg withId:value];
    return;
  }
  if (value == nil) {
    (void) [((DPGSStreamJsonWriter *) nil_chk(outArg)) nullValue];
    return;
  }
  DPGSJsonElement *tree = [((id<DPGSJsonSerializer>) nil_chk(serializer_)) serializeWithId:value withJavaLangReflectType:[((DPGSReflectTypeToken *) nil_chk(typeToken_)) getType] withDPGSJsonSerializationContext:((DPGSGson *) nil_chk(gson_))->serializationContext_];
  DPGSInternalStreams_writeWithDPGSJsonElement_withDPGSStreamJsonWriter_(tree, outArg);
}

- (DPGSTypeAdapter *)delegate {
  return DPGSTreeTypeAdapter_delegate(self);
}

+ (id<DPGSTypeAdapterFactory>)newFactoryWithDPGSReflectTypeToken:(DPGSReflectTypeToken *)exactType
                                                          withId:(id)typeAdapter {
  return DPGSTreeTypeAdapter_newFactoryWithDPGSReflectTypeToken_withId_(exactType, typeAdapter);
}

+ (id<DPGSTypeAdapterFactory>)newFactoryWithMatchRawTypeWithDPGSReflectTypeToken:(DPGSReflectTypeToken *)exactType
                                                                          withId:(id)typeAdapter {
  return DPGSTreeTypeAdapter_newFactoryWithMatchRawTypeWithDPGSReflectTypeToken_withId_(exactType, typeAdapter);
}

+ (id<DPGSTypeAdapterFactory>)newTypeHierarchyFactoryWithIOSClass:(IOSClass *)hierarchyType
                                                           withId:(id)typeAdapter {
  return DPGSTreeTypeAdapter_newTypeHierarchyFactoryWithIOSClass_withId_(hierarchyType, typeAdapter);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithDPGSJsonSerializer:withDPGSJsonDeserializer:withDPGSGson:withDPGSReflectTypeToken:withDPGSTypeAdapterFactory:", "TreeTypeAdapter", NULL, 0x0, NULL, "(Lcom/google/gson/JsonSerializer<TT;>;Lcom/google/gson/JsonDeserializer<TT;>;Lcom/google/gson/Gson;Lcom/google/gson/reflect/TypeToken<TT;>;Lcom/google/gson/TypeAdapterFactory;)V" },
    { "readWithDPGSStreamJsonReader:", "read", "TT;", 0x1, "Ljava.io.IOException;", "(Lcom/google/gson/stream/JsonReader;)TT;" },
    { "writeWithDPGSStreamJsonWriter:withId:", "write", "V", 0x1, "Ljava.io.IOException;", "(Lcom/google/gson/stream/JsonWriter;TT;)V" },
    { "delegate", NULL, "Lcom.google.gson.TypeAdapter;", 0x2, NULL, "()Lcom/google/gson/TypeAdapter<TT;>;" },
    { "newFactoryWithDPGSReflectTypeToken:withId:", "newFactory", "Lcom.google.gson.TypeAdapterFactory;", 0x9, NULL, "(Lcom/google/gson/reflect/TypeToken<*>;Ljava/lang/Object;)Lcom/google/gson/TypeAdapterFactory;" },
    { "newFactoryWithMatchRawTypeWithDPGSReflectTypeToken:withId:", "newFactoryWithMatchRawType", "Lcom.google.gson.TypeAdapterFactory;", 0x9, NULL, "(Lcom/google/gson/reflect/TypeToken<*>;Ljava/lang/Object;)Lcom/google/gson/TypeAdapterFactory;" },
    { "newTypeHierarchyFactoryWithIOSClass:withId:", "newTypeHierarchyFactory", "Lcom.google.gson.TypeAdapterFactory;", 0x9, NULL, "(Ljava/lang/Class<*>;Ljava/lang/Object;)Lcom/google/gson/TypeAdapterFactory;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serializer_", NULL, 0x12, "Lcom.google.gson.JsonSerializer;", NULL, "Lcom/google/gson/JsonSerializer<TT;>;", .constantValue.asLong = 0 },
    { "deserializer_", NULL, 0x12, "Lcom.google.gson.JsonDeserializer;", NULL, "Lcom/google/gson/JsonDeserializer<TT;>;", .constantValue.asLong = 0 },
    { "gson_", NULL, 0x12, "Lcom.google.gson.Gson;", NULL, NULL, .constantValue.asLong = 0 },
    { "typeToken_", NULL, 0x12, "Lcom.google.gson.reflect.TypeToken;", NULL, "Lcom/google/gson/reflect/TypeToken<TT;>;", .constantValue.asLong = 0 },
    { "skipPast_", NULL, 0x12, "Lcom.google.gson.TypeAdapterFactory;", NULL, NULL, .constantValue.asLong = 0 },
    { "delegate_", NULL, 0x2, "Lcom.google.gson.TypeAdapter;", NULL, "Lcom/google/gson/TypeAdapter<TT;>;", .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"TT;"};
  static const char *inner_classes[] = {"Lcom.google.gson.TreeTypeAdapter$SingleTypeFactory;"};
  static const J2ObjcClassInfo _DPGSTreeTypeAdapter = { 2, "TreeTypeAdapter", "com.google.gson", NULL, 0x10, 7, methods, 6, fields, 1, superclass_type_args, 1, inner_classes, NULL, "<T:Ljava/lang/Object;>Lcom/google/gson/TypeAdapter<TT;>;" };
  return &_DPGSTreeTypeAdapter;
}

@end

void DPGSTreeTypeAdapter_initWithDPGSJsonSerializer_withDPGSJsonDeserializer_withDPGSGson_withDPGSReflectTypeToken_withDPGSTypeAdapterFactory_(DPGSTreeTypeAdapter *self, id<DPGSJsonSerializer> serializer, id<DPGSJsonDeserializer> deserializer, DPGSGson *gson, DPGSReflectTypeToken *typeToken, id<DPGSTypeAdapterFactory> skipPast) {
  DPGSTypeAdapter_init(self);
  self->serializer_ = serializer;
  self->deserializer_ = deserializer;
  self->gson_ = gson;
  self->typeToken_ = typeToken;
  self->skipPast_ = skipPast;
}

DPGSTreeTypeAdapter *new_DPGSTreeTypeAdapter_initWithDPGSJsonSerializer_withDPGSJsonDeserializer_withDPGSGson_withDPGSReflectTypeToken_withDPGSTypeAdapterFactory_(id<DPGSJsonSerializer> serializer, id<DPGSJsonDeserializer> deserializer, DPGSGson *gson, DPGSReflectTypeToken *typeToken, id<DPGSTypeAdapterFactory> skipPast) {
  DPGSTreeTypeAdapter *self = [DPGSTreeTypeAdapter alloc];
  DPGSTreeTypeAdapter_initWithDPGSJsonSerializer_withDPGSJsonDeserializer_withDPGSGson_withDPGSReflectTypeToken_withDPGSTypeAdapterFactory_(self, serializer, deserializer, gson, typeToken, skipPast);
  return self;
}

DPGSTreeTypeAdapter *create_DPGSTreeTypeAdapter_initWithDPGSJsonSerializer_withDPGSJsonDeserializer_withDPGSGson_withDPGSReflectTypeToken_withDPGSTypeAdapterFactory_(id<DPGSJsonSerializer> serializer, id<DPGSJsonDeserializer> deserializer, DPGSGson *gson, DPGSReflectTypeToken *typeToken, id<DPGSTypeAdapterFactory> skipPast) {
  return new_DPGSTreeTypeAdapter_initWithDPGSJsonSerializer_withDPGSJsonDeserializer_withDPGSGson_withDPGSReflectTypeToken_withDPGSTypeAdapterFactory_(serializer, deserializer, gson, typeToken, skipPast);
}

DPGSTypeAdapter *DPGSTreeTypeAdapter_delegate(DPGSTreeTypeAdapter *self) {
  DPGSTypeAdapter *d = self->delegate_;
  return d != nil ? d : (self->delegate_ = [((DPGSGson *) nil_chk(self->gson_)) getDelegateAdapterWithDPGSTypeAdapterFactory:self->skipPast_ withDPGSReflectTypeToken:self->typeToken_]);
}

id<DPGSTypeAdapterFactory> DPGSTreeTypeAdapter_newFactoryWithDPGSReflectTypeToken_withId_(DPGSReflectTypeToken *exactType, id typeAdapter) {
  DPGSTreeTypeAdapter_initialize();
  return new_DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(typeAdapter, exactType, false, nil);
}

id<DPGSTypeAdapterFactory> DPGSTreeTypeAdapter_newFactoryWithMatchRawTypeWithDPGSReflectTypeToken_withId_(DPGSReflectTypeToken *exactType, id typeAdapter) {
  DPGSTreeTypeAdapter_initialize();
  jboolean matchRawType = [((DPGSReflectTypeToken *) nil_chk(exactType)) getType] == [exactType getRawType];
  return new_DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(typeAdapter, exactType, matchRawType, nil);
}

id<DPGSTypeAdapterFactory> DPGSTreeTypeAdapter_newTypeHierarchyFactoryWithIOSClass_withId_(IOSClass *hierarchyType, id typeAdapter) {
  DPGSTreeTypeAdapter_initialize();
  return new_DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(typeAdapter, nil, false, hierarchyType);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSTreeTypeAdapter)

@implementation DPGSTreeTypeAdapter_SingleTypeFactory

- (instancetype)initWithId:(id)typeAdapter
  withDPGSReflectTypeToken:(DPGSReflectTypeToken *)exactType
               withBoolean:(jboolean)matchRawType
              withIOSClass:(IOSClass *)hierarchyType {
  DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(self, typeAdapter, exactType, matchRawType, hierarchyType);
  return self;
}

- (DPGSTypeAdapter *)createWithDPGSGson:(DPGSGson *)gson
               withDPGSReflectTypeToken:(DPGSReflectTypeToken *)type {
  jboolean matches = exactType_ != nil ? [exactType_ isEqual:type] || (matchRawType_ && [exactType_ getType] == [((DPGSReflectTypeToken *) nil_chk(type)) getRawType]) : [((IOSClass *) nil_chk(hierarchyType_)) isAssignableFrom:[((DPGSReflectTypeToken *) nil_chk(type)) getRawType]];
  return matches ? new_DPGSTreeTypeAdapter_initWithDPGSJsonSerializer_withDPGSJsonDeserializer_withDPGSGson_withDPGSReflectTypeToken_withDPGSTypeAdapterFactory_(serializer_, deserializer_, gson, type, self) : nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithId:withDPGSReflectTypeToken:withBoolean:withIOSClass:", "SingleTypeFactory", NULL, 0x0, NULL, "(Ljava/lang/Object;Lcom/google/gson/reflect/TypeToken<*>;ZLjava/lang/Class<*>;)V" },
    { "createWithDPGSGson:withDPGSReflectTypeToken:", "create", "Lcom.google.gson.TypeAdapter;", 0x1, NULL, "<T:Ljava/lang/Object;>(Lcom/google/gson/Gson;Lcom/google/gson/reflect/TypeToken<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "exactType_", NULL, 0x12, "Lcom.google.gson.reflect.TypeToken;", NULL, "Lcom/google/gson/reflect/TypeToken<*>;", .constantValue.asLong = 0 },
    { "matchRawType_", NULL, 0x12, "Z", NULL, NULL, .constantValue.asLong = 0 },
    { "hierarchyType_", NULL, 0x12, "Ljava.lang.Class;", NULL, "Ljava/lang/Class<*>;", .constantValue.asLong = 0 },
    { "serializer_", NULL, 0x12, "Lcom.google.gson.JsonSerializer;", NULL, "Lcom/google/gson/JsonSerializer<*>;", .constantValue.asLong = 0 },
    { "deserializer_", NULL, 0x12, "Lcom.google.gson.JsonDeserializer;", NULL, "Lcom/google/gson/JsonDeserializer<*>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _DPGSTreeTypeAdapter_SingleTypeFactory = { 2, "SingleTypeFactory", "com.google.gson", "TreeTypeAdapter", 0xa, 2, methods, 5, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_DPGSTreeTypeAdapter_SingleTypeFactory;
}

@end

void DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(DPGSTreeTypeAdapter_SingleTypeFactory *self, id typeAdapter, DPGSReflectTypeToken *exactType, jboolean matchRawType, IOSClass *hierarchyType) {
  NSObject_init(self);
  self->serializer_ = [DPGSJsonSerializer_class_() isInstance:typeAdapter] ? (id<DPGSJsonSerializer>) cast_check(typeAdapter, DPGSJsonSerializer_class_()) : nil;
  self->deserializer_ = [DPGSJsonDeserializer_class_() isInstance:typeAdapter] ? (id<DPGSJsonDeserializer>) cast_check(typeAdapter, DPGSJsonDeserializer_class_()) : nil;
  DPGSInternal$Gson$Preconditions_checkArgumentWithBoolean_(self->serializer_ != nil || self->deserializer_ != nil);
  self->exactType_ = exactType;
  self->matchRawType_ = matchRawType;
  self->hierarchyType_ = hierarchyType;
}

DPGSTreeTypeAdapter_SingleTypeFactory *new_DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(id typeAdapter, DPGSReflectTypeToken *exactType, jboolean matchRawType, IOSClass *hierarchyType) {
  DPGSTreeTypeAdapter_SingleTypeFactory *self = [DPGSTreeTypeAdapter_SingleTypeFactory alloc];
  DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(self, typeAdapter, exactType, matchRawType, hierarchyType);
  return self;
}

DPGSTreeTypeAdapter_SingleTypeFactory *create_DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(id typeAdapter, DPGSReflectTypeToken *exactType, jboolean matchRawType, IOSClass *hierarchyType) {
  return new_DPGSTreeTypeAdapter_SingleTypeFactory_initWithId_withDPGSReflectTypeToken_withBoolean_withIOSClass_(typeAdapter, exactType, matchRawType, hierarchyType);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DPGSTreeTypeAdapter_SingleTypeFactory)
