//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/RxJava/src/main/java/rx/internal/operators/OnSubscribeTimerOnce.java
//

#include "J2ObjC_source.h"
#include "java/lang/Long.h"
#include "java/util/concurrent/TimeUnit.h"
#include "rx/Scheduler.h"
#include "rx/Subscriber.h"
#include "rx/Subscription.h"
#include "rx/functions/Action0.h"
#include "rx/internal/operators/OnSubscribeTimerOnce.h"

@interface RxInternalOperatorsOnSubscribeTimerOnce_$1 : NSObject < RxFunctionsAction0 > {
 @public
  RxSubscriber *val$child_;
}

- (void)call;

- (instancetype)initWithRxSubscriber:(RxSubscriber *)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOnSubscribeTimerOnce_$1)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOnSubscribeTimerOnce_$1, val$child_, RxSubscriber *)

__attribute__((unused)) static void RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(RxInternalOperatorsOnSubscribeTimerOnce_$1 *self, RxSubscriber *capture$0);

__attribute__((unused)) static RxInternalOperatorsOnSubscribeTimerOnce_$1 *new_RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(RxSubscriber *capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static RxInternalOperatorsOnSubscribeTimerOnce_$1 *create_RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(RxSubscriber *capture$0);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOnSubscribeTimerOnce_$1)

@implementation RxInternalOperatorsOnSubscribeTimerOnce

- (instancetype)initWithLong:(jlong)time
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit
             withRxScheduler:(RxScheduler *)scheduler {
  RxInternalOperatorsOnSubscribeTimerOnce_initWithLong_withJavaUtilConcurrentTimeUnit_withRxScheduler_(self, time, unit, scheduler);
  return self;
}

- (void)callWithId:(RxSubscriber *)child {
  RxScheduler_Worker *worker = [((RxScheduler *) nil_chk(scheduler_)) createWorker];
  [((RxSubscriber *) nil_chk(child)) addWithRxSubscription:worker];
  (void) [((RxScheduler_Worker *) nil_chk(worker)) scheduleWithRxFunctionsAction0:new_RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(child) withLong:time_ withJavaUtilConcurrentTimeUnit:unit_];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithLong:withJavaUtilConcurrentTimeUnit:withRxScheduler:", "OnSubscribeTimerOnce", NULL, 0x1, NULL, NULL },
    { "callWithId:", "call", "V", 0x1, NULL, "(Lrx/Subscriber<-Ljava/lang/Long;>;)V" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "time_", NULL, 0x10, "J", NULL, NULL, .constantValue.asLong = 0 },
    { "unit_", NULL, 0x10, "Ljava.util.concurrent.TimeUnit;", NULL, NULL, .constantValue.asLong = 0 },
    { "scheduler_", NULL, 0x10, "Lrx.Scheduler;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _RxInternalOperatorsOnSubscribeTimerOnce = { 2, "OnSubscribeTimerOnce", "rx.internal.operators", NULL, 0x11, 2, methods, 3, fields, 0, NULL, 0, NULL, NULL, "Ljava/lang/Object;Lrx/Observable$OnSubscribe<Ljava/lang/Long;>;" };
  return &_RxInternalOperatorsOnSubscribeTimerOnce;
}

@end

void RxInternalOperatorsOnSubscribeTimerOnce_initWithLong_withJavaUtilConcurrentTimeUnit_withRxScheduler_(RxInternalOperatorsOnSubscribeTimerOnce *self, jlong time, JavaUtilConcurrentTimeUnit *unit, RxScheduler *scheduler) {
  NSObject_init(self);
  self->time_ = time;
  self->unit_ = unit;
  self->scheduler_ = scheduler;
}

RxInternalOperatorsOnSubscribeTimerOnce *new_RxInternalOperatorsOnSubscribeTimerOnce_initWithLong_withJavaUtilConcurrentTimeUnit_withRxScheduler_(jlong time, JavaUtilConcurrentTimeUnit *unit, RxScheduler *scheduler) {
  RxInternalOperatorsOnSubscribeTimerOnce *self = [RxInternalOperatorsOnSubscribeTimerOnce alloc];
  RxInternalOperatorsOnSubscribeTimerOnce_initWithLong_withJavaUtilConcurrentTimeUnit_withRxScheduler_(self, time, unit, scheduler);
  return self;
}

RxInternalOperatorsOnSubscribeTimerOnce *create_RxInternalOperatorsOnSubscribeTimerOnce_initWithLong_withJavaUtilConcurrentTimeUnit_withRxScheduler_(jlong time, JavaUtilConcurrentTimeUnit *unit, RxScheduler *scheduler) {
  return new_RxInternalOperatorsOnSubscribeTimerOnce_initWithLong_withJavaUtilConcurrentTimeUnit_withRxScheduler_(time, unit, scheduler);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOnSubscribeTimerOnce)

@implementation RxInternalOperatorsOnSubscribeTimerOnce_$1

- (void)call {
  @try {
    [((RxSubscriber *) nil_chk(val$child_)) onNextWithId:JavaLangLong_valueOfWithLong_(0LL)];
  }
  @catch (NSException *t) {
    [((RxSubscriber *) nil_chk(val$child_)) onErrorWithNSException:t];
    return;
  }
  [((RxSubscriber *) nil_chk(val$child_)) onCompleted];
}

- (instancetype)initWithRxSubscriber:(RxSubscriber *)capture$0 {
  RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(self, capture$0);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "call", NULL, "V", 0x1, NULL, NULL },
    { "initWithRxSubscriber:", "", NULL, 0x0, NULL, "(Lrx/Subscriber<-Ljava/lang/Long;>;)V" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "val$child_", NULL, 0x1012, "Lrx.Subscriber;", NULL, "Lrx/Subscriber<-Ljava/lang/Long;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "RxInternalOperatorsOnSubscribeTimerOnce", "callWithId:" };
  static const J2ObjcClassInfo _RxInternalOperatorsOnSubscribeTimerOnce_$1 = { 2, "", "rx.internal.operators", "OnSubscribeTimerOnce", 0x8008, 2, methods, 1, fields, 0, NULL, 0, NULL, &enclosing_method, NULL };
  return &_RxInternalOperatorsOnSubscribeTimerOnce_$1;
}

@end

void RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(RxInternalOperatorsOnSubscribeTimerOnce_$1 *self, RxSubscriber *capture$0) {
  self->val$child_ = capture$0;
  NSObject_init(self);
}

RxInternalOperatorsOnSubscribeTimerOnce_$1 *new_RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(RxSubscriber *capture$0) {
  RxInternalOperatorsOnSubscribeTimerOnce_$1 *self = [RxInternalOperatorsOnSubscribeTimerOnce_$1 alloc];
  RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(self, capture$0);
  return self;
}

RxInternalOperatorsOnSubscribeTimerOnce_$1 *create_RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(RxSubscriber *capture$0) {
  return new_RxInternalOperatorsOnSubscribeTimerOnce_$1_initWithRxSubscriber_(capture$0);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOnSubscribeTimerOnce_$1)
