//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/RxJava/src/main/java/rx/internal/operators/OperatorMapNotification.java
//

#include "J2ObjC_source.h"
#include "rx/Subscriber.h"
#include "rx/exceptions/OnErrorThrowable.h"
#include "rx/functions/Func0.h"
#include "rx/functions/Func1.h"
#include "rx/internal/operators/OperatorMapNotification.h"

@interface RxInternalOperatorsOperatorMapNotification () {
 @public
  id<RxFunctionsFunc1> onNext_;
  id<RxFunctionsFunc1> onError_;
  id<RxFunctionsFunc0> onCompleted_;
}

@end

J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorMapNotification, onNext_, id<RxFunctionsFunc1>)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorMapNotification, onError_, id<RxFunctionsFunc1>)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorMapNotification, onCompleted_, id<RxFunctionsFunc0>)

@interface RxInternalOperatorsOperatorMapNotification_$1 : RxSubscriber {
 @public
  RxInternalOperatorsOperatorMapNotification *this$0_;
  RxSubscriber *val$o_;
}

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;
#ifdef J2OBJC_RENAME_ALIASES
#define onErrorWithJavaLangThrowable onErrorWithNSException
#endif // J2OBJC_RENAME_ALIASES

- (void)onNextWithId:(id)t;

- (instancetype)initWithRxInternalOperatorsOperatorMapNotification:(RxInternalOperatorsOperatorMapNotification *)outer$
                                                  withRxSubscriber:(RxSubscriber *)capture$0
                                                  withRxSubscriber:(RxSubscriber *)arg$0;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOperatorMapNotification_$1)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorMapNotification_$1, this$0_, RxInternalOperatorsOperatorMapNotification *)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorMapNotification_$1, val$o_, RxSubscriber *)

__attribute__((unused)) static void RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorMapNotification_$1 *self, RxInternalOperatorsOperatorMapNotification *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0);

__attribute__((unused)) static RxInternalOperatorsOperatorMapNotification_$1 *new_RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorMapNotification *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static RxInternalOperatorsOperatorMapNotification_$1 *create_RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorMapNotification *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOperatorMapNotification_$1)

@implementation RxInternalOperatorsOperatorMapNotification

- (instancetype)initWithRxFunctionsFunc1:(id<RxFunctionsFunc1>)onNext
                    withRxFunctionsFunc1:(id<RxFunctionsFunc1>)onError
                    withRxFunctionsFunc0:(id<RxFunctionsFunc0>)onCompleted {
  RxInternalOperatorsOperatorMapNotification_initWithRxFunctionsFunc1_withRxFunctionsFunc1_withRxFunctionsFunc0_(self, onNext, onError, onCompleted);
  return self;
}

- (RxSubscriber *)callWithId:(RxSubscriber *)o {
  return new_RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(self, o, o);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithRxFunctionsFunc1:withRxFunctionsFunc1:withRxFunctionsFunc0:", "OperatorMapNotification", NULL, 0x1, NULL, "(Lrx/functions/Func1<-TT;+TR;>;Lrx/functions/Func1<-Ljava/lang/Throwable;+TR;>;Lrx/functions/Func0<+TR;>;)V" },
    { "callWithId:", "call", "Lrx.Subscriber;", 0x1, NULL, "(Lrx/Subscriber<-TR;>;)Lrx/Subscriber<-TT;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "onNext_", NULL, 0x12, "Lrx.functions.Func1;", NULL, "Lrx/functions/Func1<-TT;+TR;>;", .constantValue.asLong = 0 },
    { "onError_", NULL, 0x12, "Lrx.functions.Func1;", NULL, "Lrx/functions/Func1<-Ljava/lang/Throwable;+TR;>;", .constantValue.asLong = 0 },
    { "onCompleted_", NULL, 0x12, "Lrx.functions.Func0;", NULL, "Lrx/functions/Func0<+TR;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _RxInternalOperatorsOperatorMapNotification = { 2, "OperatorMapNotification", "rx.internal.operators", NULL, 0x11, 2, methods, 3, fields, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;R:Ljava/lang/Object;>Ljava/lang/Object;Lrx/Observable$Operator<TR;TT;>;" };
  return &_RxInternalOperatorsOperatorMapNotification;
}

@end

void RxInternalOperatorsOperatorMapNotification_initWithRxFunctionsFunc1_withRxFunctionsFunc1_withRxFunctionsFunc0_(RxInternalOperatorsOperatorMapNotification *self, id<RxFunctionsFunc1> onNext, id<RxFunctionsFunc1> onError, id<RxFunctionsFunc0> onCompleted) {
  NSObject_init(self);
  self->onNext_ = onNext;
  self->onError_ = onError;
  self->onCompleted_ = onCompleted;
}

RxInternalOperatorsOperatorMapNotification *new_RxInternalOperatorsOperatorMapNotification_initWithRxFunctionsFunc1_withRxFunctionsFunc1_withRxFunctionsFunc0_(id<RxFunctionsFunc1> onNext, id<RxFunctionsFunc1> onError, id<RxFunctionsFunc0> onCompleted) {
  RxInternalOperatorsOperatorMapNotification *self = [RxInternalOperatorsOperatorMapNotification alloc];
  RxInternalOperatorsOperatorMapNotification_initWithRxFunctionsFunc1_withRxFunctionsFunc1_withRxFunctionsFunc0_(self, onNext, onError, onCompleted);
  return self;
}

RxInternalOperatorsOperatorMapNotification *create_RxInternalOperatorsOperatorMapNotification_initWithRxFunctionsFunc1_withRxFunctionsFunc1_withRxFunctionsFunc0_(id<RxFunctionsFunc1> onNext, id<RxFunctionsFunc1> onError, id<RxFunctionsFunc0> onCompleted) {
  return new_RxInternalOperatorsOperatorMapNotification_initWithRxFunctionsFunc1_withRxFunctionsFunc1_withRxFunctionsFunc0_(onNext, onError, onCompleted);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOperatorMapNotification)

@implementation RxInternalOperatorsOperatorMapNotification_$1

- (void)onCompleted {
  @try {
    [((RxSubscriber *) nil_chk(val$o_)) onNextWithId:[((id<RxFunctionsFunc0>) nil_chk(this$0_->onCompleted_)) call]];
    [val$o_ onCompleted];
  }
  @catch (NSException *e) {
    [((RxSubscriber *) nil_chk(val$o_)) onErrorWithNSException:e];
  }
}

- (void)onErrorWithNSException:(NSException *)e {
  @try {
    [((RxSubscriber *) nil_chk(val$o_)) onNextWithId:[((id<RxFunctionsFunc1>) nil_chk(this$0_->onError_)) callWithId:e]];
    [val$o_ onCompleted];
  }
  @catch (NSException *e2) {
    [((RxSubscriber *) nil_chk(val$o_)) onErrorWithNSException:e];
  }
}

- (void)onNextWithId:(id)t {
  @try {
    [((RxSubscriber *) nil_chk(val$o_)) onNextWithId:[((id<RxFunctionsFunc1>) nil_chk(this$0_->onNext_)) callWithId:t]];
  }
  @catch (NSException *e) {
    [((RxSubscriber *) nil_chk(val$o_)) onErrorWithNSException:RxExceptionsOnErrorThrowable_addValueAsLastCauseWithNSException_withId_(e, t)];
  }
}

- (instancetype)initWithRxInternalOperatorsOperatorMapNotification:(RxInternalOperatorsOperatorMapNotification *)outer$
                                                  withRxSubscriber:(RxSubscriber *)capture$0
                                                  withRxSubscriber:(RxSubscriber *)arg$0 {
  RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(self, outer$, capture$0, arg$0);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onCompleted", NULL, "V", 0x1, NULL, NULL },
    { "onErrorWithNSException:", "onError", "V", 0x1, NULL, NULL },
    { "onNextWithId:", "onNext", "V", 0x1, NULL, "(TT;)V" },
    { "initWithRxInternalOperatorsOperatorMapNotification:withRxSubscriber:withRxSubscriber:", "", NULL, 0x0, NULL, "(Lrx/internal/operators/OperatorMapNotification;Lrx/Subscriber<-TR;>;Lrx/Subscriber<*>;)V" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lrx.internal.operators.OperatorMapNotification;", NULL, NULL, .constantValue.asLong = 0 },
    { "val$o_", NULL, 0x1012, "Lrx.Subscriber;", NULL, "Lrx/Subscriber<-TR;>;", .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"TT;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "RxInternalOperatorsOperatorMapNotification", "callWithId:" };
  static const J2ObjcClassInfo _RxInternalOperatorsOperatorMapNotification_$1 = { 2, "", "rx.internal.operators", "OperatorMapNotification", 0x8008, 4, methods, 2, fields, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lrx/Subscriber<TT;>;" };
  return &_RxInternalOperatorsOperatorMapNotification_$1;
}

@end

void RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorMapNotification_$1 *self, RxInternalOperatorsOperatorMapNotification *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0) {
  self->this$0_ = outer$;
  self->val$o_ = capture$0;
  RxSubscriber_initWithRxSubscriber_(self, arg$0);
}

RxInternalOperatorsOperatorMapNotification_$1 *new_RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorMapNotification *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0) {
  RxInternalOperatorsOperatorMapNotification_$1 *self = [RxInternalOperatorsOperatorMapNotification_$1 alloc];
  RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(self, outer$, capture$0, arg$0);
  return self;
}

RxInternalOperatorsOperatorMapNotification_$1 *create_RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(RxInternalOperatorsOperatorMapNotification *outer$, RxSubscriber *capture$0, RxSubscriber *arg$0) {
  return new_RxInternalOperatorsOperatorMapNotification_$1_initWithRxInternalOperatorsOperatorMapNotification_withRxSubscriber_withRxSubscriber_(outer$, capture$0, arg$0);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOperatorMapNotification_$1)
