//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/RxJava/src/main/java/rx/internal/operators/OperatorMaterialize.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RxInternalOperatorsOperatorMaterialize_INCLUDE_ALL")
#ifdef RxInternalOperatorsOperatorMaterialize_RESTRICT
#define RxInternalOperatorsOperatorMaterialize_INCLUDE_ALL 0
#else
#define RxInternalOperatorsOperatorMaterialize_INCLUDE_ALL 1
#endif
#undef RxInternalOperatorsOperatorMaterialize_RESTRICT

#if !defined (RxInternalOperatorsOperatorMaterialize_) && (RxInternalOperatorsOperatorMaterialize_INCLUDE_ALL || defined(RxInternalOperatorsOperatorMaterialize_INCLUDE))
#define RxInternalOperatorsOperatorMaterialize_

#define RxObservable_RESTRICT 1
#define RxObservable_Operator_INCLUDE 1
#include "rx/Observable.h"

@class RxSubscriber;

@interface RxInternalOperatorsOperatorMaterialize : NSObject < RxObservable_Operator >

#pragma mark Public

- (instancetype)init;

- (RxSubscriber *)callWithId:(RxSubscriber *)child;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOperatorMaterialize)

FOUNDATION_EXPORT void RxInternalOperatorsOperatorMaterialize_init(RxInternalOperatorsOperatorMaterialize *self);

FOUNDATION_EXPORT RxInternalOperatorsOperatorMaterialize *new_RxInternalOperatorsOperatorMaterialize_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOperatorMaterialize *create_RxInternalOperatorsOperatorMaterialize_init();

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOperatorMaterialize)

#endif

#pragma pop_macro("RxInternalOperatorsOperatorMaterialize_INCLUDE_ALL")
