//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel/xp/sourcejava/RxJava/src/main/java/rx/internal/operators/OperatorWindowWithObservable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("RxInternalOperatorsOperatorWindowWithObservable_INCLUDE_ALL")
#ifdef RxInternalOperatorsOperatorWindowWithObservable_RESTRICT
#define RxInternalOperatorsOperatorWindowWithObservable_INCLUDE_ALL 0
#else
#define RxInternalOperatorsOperatorWindowWithObservable_INCLUDE_ALL 1
#endif
#undef RxInternalOperatorsOperatorWindowWithObservable_RESTRICT

#if !defined (RxInternalOperatorsOperatorWindowWithObservable_) && (RxInternalOperatorsOperatorWindowWithObservable_INCLUDE_ALL || defined(RxInternalOperatorsOperatorWindowWithObservable_INCLUDE))
#define RxInternalOperatorsOperatorWindowWithObservable_

#define RxObservable_RESTRICT 1
#define RxObservable_Operator_INCLUDE 1
#include "rx/Observable.h"

@class RxInternalOperatorsNotificationLite;
@class RxObservable;
@class RxSubscriber;
@protocol RxFunctionsFunc0;

@interface RxInternalOperatorsOperatorWindowWithObservable : NSObject < RxObservable_Operator > {
 @public
  id<RxFunctionsFunc0> otherFactory_;
}

#pragma mark Public

- (instancetype)initWithRxFunctionsFunc0:(id<RxFunctionsFunc0>)otherFactory;

- (instancetype)initWithRxObservable:(RxObservable *)other;

- (RxSubscriber *)callWithId:(RxSubscriber *)child;

@end

J2OBJC_STATIC_INIT(RxInternalOperatorsOperatorWindowWithObservable)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorWindowWithObservable, otherFactory_, id<RxFunctionsFunc0>)

inline id RxInternalOperatorsOperatorWindowWithObservable_get_NEXT_SUBJECT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id RxInternalOperatorsOperatorWindowWithObservable_NEXT_SUBJECT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(RxInternalOperatorsOperatorWindowWithObservable, NEXT_SUBJECT, id)

inline RxInternalOperatorsNotificationLite *RxInternalOperatorsOperatorWindowWithObservable_get_nl();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT RxInternalOperatorsNotificationLite *RxInternalOperatorsOperatorWindowWithObservable_nl;
J2OBJC_STATIC_FIELD_OBJ_FINAL(RxInternalOperatorsOperatorWindowWithObservable, nl, RxInternalOperatorsNotificationLite *)

FOUNDATION_EXPORT void RxInternalOperatorsOperatorWindowWithObservable_initWithRxFunctionsFunc0_(RxInternalOperatorsOperatorWindowWithObservable *self, id<RxFunctionsFunc0> otherFactory);

FOUNDATION_EXPORT RxInternalOperatorsOperatorWindowWithObservable *new_RxInternalOperatorsOperatorWindowWithObservable_initWithRxFunctionsFunc0_(id<RxFunctionsFunc0> otherFactory) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOperatorWindowWithObservable *create_RxInternalOperatorsOperatorWindowWithObservable_initWithRxFunctionsFunc0_(id<RxFunctionsFunc0> otherFactory);

FOUNDATION_EXPORT void RxInternalOperatorsOperatorWindowWithObservable_initWithRxObservable_(RxInternalOperatorsOperatorWindowWithObservable *self, RxObservable *other);

FOUNDATION_EXPORT RxInternalOperatorsOperatorWindowWithObservable *new_RxInternalOperatorsOperatorWindowWithObservable_initWithRxObservable_(RxObservable *other) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOperatorWindowWithObservable *create_RxInternalOperatorsOperatorWindowWithObservable_initWithRxObservable_(RxObservable *other);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOperatorWindowWithObservable)

#endif

#if !defined (RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber_) && (RxInternalOperatorsOperatorWindowWithObservable_INCLUDE_ALL || defined(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber_INCLUDE))
#define RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber_

#define RxSubscriber_RESTRICT 1
#define RxSubscriber_INCLUDE 1
#include "rx/Subscriber.h"

@class RxObservable;
@protocol JavaUtilList;
@protocol RxObserver;

@interface RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber : RxSubscriber {
 @public
  RxSubscriber *child_;
  id guard_;
  id<RxObserver> consumer_;
  RxObservable *producer_;
  jboolean emitting_;
  id<JavaUtilList> queue_;
}

#pragma mark Public

- (instancetype)initWithRxSubscriber:(RxSubscriber *)child;

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;
#ifdef J2OBJC_RENAME_ALIASES
#define onErrorWithJavaLangThrowable onErrorWithNSException
#endif // J2OBJC_RENAME_ALIASES

- (void)onNextWithId:(id)t;

- (void)onStart;

#pragma mark Package-Private

- (void)complete;

- (void)createNewWindow;

- (void)drainWithJavaUtilList:(id<JavaUtilList>)queue;

- (void)emitValueWithId:(id)t;

- (void)errorWithNSException:(NSException *)e;
#ifdef J2OBJC_RENAME_ALIASES
#define errorWithJavaLangThrowable errorWithNSException
#endif // J2OBJC_RENAME_ALIASES

- (void)replaceSubject;

- (void)replaceWindow;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber, child_, RxSubscriber *)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber, guard_, id)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber, consumer_, id<RxObserver>)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber, producer_, RxObservable *)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber, queue_, id<JavaUtilList>)

FOUNDATION_EXPORT void RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber_initWithRxSubscriber_(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber *self, RxSubscriber *child);

FOUNDATION_EXPORT RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber *new_RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber_initWithRxSubscriber_(RxSubscriber *child) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber *create_RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber_initWithRxSubscriber_(RxSubscriber *child);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber)

#endif

#if !defined (RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber_) && (RxInternalOperatorsOperatorWindowWithObservable_INCLUDE_ALL || defined(RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber_INCLUDE))
#define RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber_

#define RxSubscriber_RESTRICT 1
#define RxSubscriber_INCLUDE 1
#include "rx/Subscriber.h"

@class RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber;

@interface RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber : RxSubscriber {
 @public
  RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber *sub_;
}

#pragma mark Public

- (instancetype)initWithRxSubscriber:(RxSubscriber *)child
withRxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber:(RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber *)sub;

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;
#ifdef J2OBJC_RENAME_ALIASES
#define onErrorWithJavaLangThrowable onErrorWithNSException
#endif // J2OBJC_RENAME_ALIASES

- (void)onNextWithId:(id)t;

- (void)onStart;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber, sub_, RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber *)

FOUNDATION_EXPORT void RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber_initWithRxSubscriber_withRxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber_(RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber *self, RxSubscriber *child, RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber *sub);

FOUNDATION_EXPORT RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber *new_RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber_initWithRxSubscriber_withRxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber_(RxSubscriber *child, RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber *sub) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber *create_RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber_initWithRxSubscriber_withRxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber_(RxSubscriber *child, RxInternalOperatorsOperatorWindowWithObservable_SourceSubscriber *sub);

J2OBJC_TYPE_LITERAL_HEADER(RxInternalOperatorsOperatorWindowWithObservable_BoundarySubscriber)

#endif

#pragma pop_macro("RxInternalOperatorsOperatorWindowWithObservable_INCLUDE_ALL")
